= Quản lý extension

Mỗi extension được quản lý ở database level, nghĩa là mọi database cần extension đều phải quản lý lifecycle của extension đó. Nói cách khác, không có cách quản lý extension ở per-cluster level rồi áp dụng extension cho mọi database bên trong cluster.

Extension chủ yếu được quản lý bằng ba SQL statement: `CREATE EXTENSION`, `DROP EXTENSION` và `ALTER EXTENSION`, lần lượt dùng để cài đặt extension vào database, remove extension khỏi database và sửa đổi attribute hoặc upgrade extension.

Mỗi extension được xác định bằng một mnemonic và một version; nếu không chỉ định version, PostgreSQL giả định rằng bạn muốn làm việc với version mới nhất hiện có hoặc version đã được cài đặt.

Trong các subsection tiếp theo, từng management statement trong ba statement trên sẽ được giải thích.

== Tạo extension

Statement `CREATE EXTENSION` cho phép bạn cài đặt một extension hiện có vào database hiện tại.

Synopsis của statement như sau:

[source,sql]
....
CREATE EXTENSION [ IF NOT EXISTS ] extension_name
     [ WITH ] [ SCHEMA schema_name ]
                [ VERSION version ]
                [ CASCADE ]
....

Tên extension là mnemonic của extension; như bạn thấy, bạn có thể chỉ định version number của extension cần cài đặt. Nếu extension phụ thuộc vào extension khác, option `CASCADE` cho phép system tự động thực thi một `CREATE EXTENSION` đệ quy cho dependency đó. Bạn có thể quyết định schema nơi các extension object phải được đặt vào; tất nhiên, điều này chỉ có ý nghĩa đối với những extension có thể relocate.

Như bạn có thể hình dung, `IF NOT EXISTS` cho phép command xử lý êm thấm nếu extension đã được cài đặt. Chính xác hơn, nó không làm gì nếu extension đã được cài đặt trong database.

Để thấy rõ hơn cách `CREATE EXTENSION` hoạt động, hãy giả sử chúng ta muốn cài đặt procedural language PL/Perl trong database `forumdb`; vì extension PL/Perl có sẵn dưới dạng PostgreSQL contrib module, extension này đáng lẽ đã có sẵn bên trong cluster.

Vì vậy, để cài đặt nó, bạn phải thực hiện như sau:

[source,text]
....
forumdb=# CREATE EXTENSION plperl;
CREATE EXTENSION
....

Lưu ý rằng extension PL/Perl (mnemonic `plperl`) yêu cầu được cài đặt bởi database administrator. Nếu bạn thử cài đặt lại extension đó, command sẽ fail trừ khi bạn sử dụng clause `IF NOT EXISTS`:

[source,text]
....
forumdb=# CREATE EXTENSION plperl;
ERROR:    extension "plperl" already exists

forumdb=# CREATE EXTENSION IF NOT EXISTS plperl;
NOTICE:    extension "plperl" already exists, skipping
CREATE EXTENSION
....

Một ví dụ đơn giản khác là cài đặt một version cụ thể của extension `pg_stat_statements`:

[source,text]
....
forumdb=# CREATE EXTENSION pg_stat_statements VERSION '1.10';
CREATE EXTENSION
....

[quote]
____
Lưu ý rằng `pg_stat_statements` yêu cầu thay đổi configuration parameter `shared_preload_libraries`, và thay đổi đó lại yêu cầu cluster phải được restart. Trong Docker image của chapter này, setting `shared_preload_libraries` đã được cấu hình phù hợp để bạn sử dụng extension `pg_stat_statements`. Nếu muốn thay đổi PostgreSQL configuration thủ công để sử dụng `pg_stat_statements`, bạn cần sửa configuration file `postgresql.conf` hoặc thực thi:

[source,sql]
....
ALTER SYSTEM SET shared_preload_libraries TO 'pg_stat_statements';
....

Sau đó restart cluster.

____
== Xem các extension đã cài đặt

Trong `psql` terminal, bạn có thể lấy danh sách các extension đã cài đặt bằng special command `\dx`:

[source,text]
....
forumdb=# \dx
                                      List of installed extensions
       Name             | Version |      Schema      |
Description
--------------------+---------+------------+------------------------------
-----------------------------
 pg_stat_statements | 1.10     | public               | track execution statistics
of all SQL statements executed
 plperl                 | 1.0       | pg_catalog | PL/Perl procedural language
 plpgsql                | 1.0       | pg_catalog | PL/pgSQL procedural language
(3 rows)
....

Có thể lấy chính thông tin này từ catalog đặc biệt `pg_extension`, bằng cách join với `pg_namespace` để trích xuất thông tin dễ đọc về schema nơi extension đang tồn tại:

[source,text]
....
forumdb=# SELECT x.extname, x.extversion, n.nspname
              FROM pg_extension x JOIN pg_namespace n
              ON n.oid = x.extnamespace;

            extname       | extversion | nspname
--------------------+------------+------------
 plpgsql                | 1.0           | pg_catalog
 plperl                 | 1.0           | pg_catalog
 pg_stat_statements | 1.10               | public
(3 rows)
....

== Tìm các version extension hiện có

Bạn có thể inspect cluster để lấy thông tin về các version extension hiện có, tức các version mà bạn thực sự có thể cài đặt trong một database. Catalog đặc biệt `pg_available_extension_versions` cho phép lấy tất cả version hiện có của mọi extension khả dụng. Ví dụ, extension `pg_stat_statements` có các value sau trong cluster:

[source,text]
....
forumdb=# SELECT name, version
              FROM pg_available_extension_versions
              WHERE name = 'pg_stat_statements';

            name        | version
--------------------+---------
            name        | version
--------------------+---------
pg_stat_statements | 1.4
pg_stat_statements | 1.5
pg_stat_statements | 1.6
pg_stat_statements | 1.8
pg_stat_statements | 1.9
pg_stat_statements | 1.7
pg_stat_statements | 1.10
....

Điều hữu ích cần biết là extension `pg_stat_statements` có thể được cài đặt ở một version trong khoảng từ 1.4 đến 1.10, tùy nhu cầu của bạn.

[quote]
____
Bạn nên luôn cài đặt version mới nhất của một extension, tức version có number cao nhất, trừ khi bị buộc phải cài một version cụ thể vì backward compatibility.

____
== Sửa đổi extension hiện có

Statement `ALTER EXTENSION` rất phong phú và phức tạp, cho phép bạn sửa đổi hoàn toàn một extension hiện có. Statement này cho phép thực hiện bốn thay đổi chính đối với một extension hiện có:

* Upgrade extension lên version mới.
* Set schema của một relocatable extension.
* Add một database object vào extension.
* Remove một database object khỏi extension.

Để upgrade một extension đã cài đặt, bạn phải chỉ định clause `UPDATE`, đồng thời chỉ định target version number. Ví dụ, hãy xét extension `pg_stat_statements` đã trình bày trước đó và giả sử chúng ta cài version 1.6 của nó để upgrade. Để update extension lên version 1.10, có thể phát hành một statement `ALTER EXTENSION` như ví dụ sau:

[source,text]
....
forumdb=# CREATE EXTENSION
            pg_stat_statements WITH VERSION '1.6';
CREATE EXTENSION

forumdb=# ALTER EXTENSION pg_stat_statements
            UPDATE TO '1.10';
ALTER EXTENSION
....

[source,text]
....
forumdb=# \dx pg_stat_statements
                                      List of installed extensions
       Name             | Version | Schema |
Description
--------------------+---------+--------+----------------------------------
-------------------------
 pg_stat_statements | 1.10            | public | track execution statistics of
all SQL statements executed
(1 row)
....

Di chuyển một relocatable extension từ schema này sang schema khác được thực hiện bằng cách chỉ định clause `SET SCHEMA`, ví dụ:

[source,text]
....
forumdb=# ALTER EXTENSION pg_stat_statements SET SCHEMA my_schema;
ALTER EXTENSION

forumdb=# \dx pg_stat_statements
                                      List of installed extensions
       Name             | Version |     Schema     |
Description
--------------------+---------+-----------+-------------------------------
----------------------------
 pg_stat_statements | 1.10            | my_schema | track execution statistics of
all SQL statements executed
(1 row)
....

Command đó sẽ chuyển tất cả extension object vào schema `my_schema`, schema này phải tồn tại trước khi extension được relocate.

Nếu muốn remove một database object hiện có khỏi một extension, chẳng hạn một table, bạn có thể sử dụng clause `DROP`, theo sau là type của object và tất nhiên là tên của nó. Điều quan trọng là phải hiểu rằng việc remove một object khỏi extension sẽ không remove object khỏi database; thay vào đó, nó unlink object lifecycle khỏi lifecycle của extension. Nói cách khác, một object bị loại khỏi extension sẽ trở thành một database object thông thường. Ví dụ, nếu remove view `pg_stat_statements` khỏi extension cùng tên, bạn có thể chỉ định object type (`VIEW`) sau clause `DROP`, như sau:

[source,text]
....
forumdb=# ALTER EXTENSION pg_stat_statements
            DROP VIEW pg_stat_statements;
ALTER EXTENSION
....

Nếu extension đã được relocate, cần chỉ định qualified name cho mọi object, tức đặt schema hiện tại của extension trước tên object. Ví dụ, sau khi relocate extension vào namespace `my_schema`, command trên trở thành:

[source,text]
....
forumdb=# ALTER EXTENSION pg_stat_statements
            DROP VIEW my_schema.pg_stat_statements;
ALTER EXTENSION
....

Kết quả của command `DROP VIEW` trên là view vốn được tạo tại thời điểm deployment extension vẫn còn trong database và có thể được query như bình thường; nhưng view này hiện là một object có lifecycle độc lập với chính extension.

Có thể dễ dàng thấy view vẫn khả dụng bằng cách query nó:

[source,text]
....
forumdb=# SELECT count(*) FROM pg_stat_statements;
 count
-------
     2
(1 row)
....

Tất nhiên, có thể add một object mới vào extension bằng clause `ADD`, hoạt động như điều ngược lại với `DROP` và yêu cầu type cùng tên của object. Ví dụ, để add view `pg_stat_statements` trở lại extension, có thể thực hiện như sau:

[source,text]
....
forumdb=# ALTER EXTENSION pg_stat_statements
            ADD VIEW pg_stat_statements;
ALTER EXTENSION
....

Bạn cũng có thể add các object của riêng mình vào extension. Chẳng hạn, việc add một table mới vào extension có nghĩa là table đó sẽ trải qua lifecycle của extension:

[source,text]
....
forumdb=# CREATE TABLE t_ext( i int, t text );
forumdb=# ALTER EXTENSION pg_stat_statements
            ADD TABLE t_ext;
ALTER EXTENSION
....

Table `t_ext` hiện là một phần của extension, do đó nó không thể tiếp tục được thao tác bằng các statement không tính đến extension.

Ví dụ, nếu bạn cố delete table, PostgreSQL sẽ ngăn bạn làm hỏng extension:

[source,text]
....
forumdb=# DROP TABLE t_ext;
ERROR: cannot drop table t_ext because extension pg_stat_statements
requires it
HINT: You can drop extension pg_stat_statements instead.
....

Ví dụ cuối này cho thấy rõ sức mạnh của extension: mọi object thuộc một extension được quản lý như một thể thống nhất, vì vậy không thể vô tình quản lý hoặc remove chúng, do chúng phụ thuộc lẫn nhau. Điều này có nghĩa là để delete table nói trên, bạn phải remove table khỏi extension trước khi tự drop table, hoặc delete toàn bộ extension.

== Remove extension hiện có

`DROP EXTENSION` delete một extension khỏi database hiện tại. Synopsis của statement như sau:

[source,sql]
....
DROP EXTENSION [ IF EXISTS ] name [, ...] [ CASCADE | RESTRICT ]
....

Command hỗ trợ clause `IF EXISTS`, giống như nhiều statement khác. Ngoài ra, có thể chỉ định nhiều hơn một extension cần remove khỏi database.

Option `CASCADE` cũng remove các database object phụ thuộc vào object của extension, trong khi option đối lập là `RESTRICT` khiến command fail nếu vẫn còn các object khác phụ thuộc vào extension này. Ngoài ra, có thể drop nhiều extension cùng lúc.

Ví dụ, statement sau remove hai extension trong một lần, đồng thời remove tất cả object phụ thuộc vào các extension đó:

[source,text]
....
forumdb=# DROP EXTENSION plperl, plpgsql CASCADE;
NOTICE: drop cascades to function get_max(integer,integer)
DROP EXTENSION
....

Như bạn thấy, vì user-defined function `get_max()` phụ thuộc vào một trong hai extension, option `CASCADE` đã khiến process drop cả function đó.
[quote]
____
Function `get_max()` là một function PL/PgSQL đơn giản được cài đặt trong Docker container của chapter này và chỉ được dùng để minh họa rằng PostgreSQL đủ thông minh để xóa mọi object phụ thuộc khi drop một extension.

____
Tóm lại, bạn đã học cách quản lý một extension theo cách thủ công, từ cài đặt đến upgrade hoặc xóa nó; trong section tiếp theo, bạn sẽ học cách thực hiện các bước tương tự theo cách tự động hơn.
