= Tìm hiểu các statement cơ bản để thao tác với table

Bây giờ bạn đã biết cách tạo table, bạn cần hiểu cách chèn, xem, sửa đổi và xóa dữ liệu trong table. Điều này sẽ giúp bạn cập nhật các row không chính xác hoặc cập nhật các row hiện có khi cần. Có nhiều lệnh có thể dùng cho việc này; sau đây chúng ta sẽ lần lượt xem xét chúng.

== INSERT và SELECT dữ liệu

Trong phần này, chúng ta sẽ học cách chèn dữ liệu vào table. Để chèn dữ liệu vào table, bạn cần sử dụng lệnh `INSERT`. Lệnh `INSERT` sẽ chèn các row mới vào table.

Bạn có thể chèn một hoặc nhiều row được chỉ định bằng các value expression, hoặc chèn các row được tạo ra từ một query, kể cả trường hợp query không tạo ra row nào. Sau đây là một số trường hợp sử dụng:

. Để chèn một user mới vào table `users`, hãy thực thi lệnh sau:

[source,console,role="transcript"]
....
forumdb=> insert into users (username,gecos,email) values
('myusername','mygecos','myemail');
INSERT 0 1
....

.SQL
[source,sql]
....
INSERT INTO users (username, gecos, email)
VALUES ('myusername', 'mygecos', 'myemail');
....

.Output
[source,output]
....
INSERT 0 1
....


Kết quả này cho thấy PostgreSQL đã chèn một row vào table `users`. Số đầu tiên là OID của row được chèn; trong các phiên bản PostgreSQL mới hơn, table mặc định được tạo mà không có OID trên các row, vì vậy giá trị được trả về là 0.

[%start=2]
. Bây giờ, nếu muốn xem row vừa chèn vào table `users`, chúng ta phải thực thi lệnh SELECT:

[source,console,role="transcript"]
....
forumdb=> select * from users;
 pk | username       | gecos     | email
----+------------+---------+---------
  1 | myusername | mygecos | myemail
(1 row)
....

.SQL
[source,sql]
....
SELECT *
FROM users;
....

.Output
[source,output]
....
 pk | username       | gecos     | email
----+------------+---------+---------
  1 | myusername | mygecos | myemail
(1 row)
....


Lệnh SELECT dùng để lấy các row từ một table. Với SQL statement này, PostgreSQL trả về toàn bộ dữ liệu trong tất cả column của table. Giá trị `*` chỉ định tất cả column hiện có. Câu lệnh này cũng có thể viết như sau:

[source,console,role="transcript"]
....
forumdb=> select pk,username,gecos,email from users;
 pk | username       | gecos     | email
----+------------+---------+---------
 1   | myusername | mygecos | myemail
(1 row)
....

.SQL
[source,sql]
....
SELECT
    pk,
    username,
    gecos,
    email
FROM users;
....

.Output
[source,output]
....
 pk | username       | gecos     | email
----+------------+---------+---------
 1   | myusername | mygecos | myemail
(1 row)
....


[%start=3]
. Bây giờ hãy chèn một user khác vào table `users`; chẳng hạn, chèn user `'scotty'` với tất cả column của user đó:

[source,console,role="transcript"]
....
forumdb=> insert into users (username,gecos,email) values
('scotty','scotty_gecos','scotty_email');
INSERT 0 1
....

.SQL
[source,sql]
....
INSERT INTO users (username, gecos, email)
VALUES ('scotty', 'scotty_gecos', 'scotty_email');
....

.Output
[source,output]
....
INSERT 0 1
....


. Nếu muốn thực hiện query như trước nhưng sắp xếp dữ liệu theo column `username`, hãy thực thi như sau:

[source,console,role="transcript"]
....
forumdb=> select pk,username,gecos,email from users order by
username;
 pk | username       | gecos            | email
----+------------+--------------+--------------
 1 | myusername | mygecos             | myemail
 2 | scotty        | scotty_gecos | scotty_email
(2 rows)
....

.SQL
[source,sql]
....
SELECT
    pk,
    username,
    gecos,
    email
FROM users
ORDER BY username;
....

.Output
[source,output]
....
 pk | username       | gecos            | email
----+------------+--------------+--------------
 1 | myusername | mygecos             | myemail
 2 | scotty        | scotty_gecos | scotty_email
(2 rows)
....


[quote]
____
Trong SQL, nếu không có tùy chọn `ORDER BY`, dữ liệu không được trả về theo thứ tự.

____
Trong PostgreSQL, điều này cũng có thể được viết như sau:

[source,console,role="transcript"]
....
forumdb=> select pk,username,gecos,email from users order by 2;
 pk | username      | gecos             | email
----+------------+--------------+--------------
  1 | myusername | mygecos              | myemail
  2 | scotty        | scotty_gecos | scotty_email
(2 rows)
....

.SQL
[source,sql]
....
SELECT
    pk,
    username,
    gecos,
    email
FROM users
ORDER BY 2;
....

.Output
[source,output]
....
 pk | username      | gecos             | email
----+------------+--------------+--------------
  1 | myusername | mygecos              | myemail
  2 | scotty        | scotty_gecos | scotty_email
(2 rows)
....


[quote]
____
PostgreSQL cũng cho phép dùng vị trí của column trong query làm tiêu chí sắp xếp.

____
[%start=5]
. Bây giờ hãy xem cách chèn nhiều row bằng một single-row statement. Ví dụ, statement sau sẽ chèn ba row vào table `categories`:

[source,console,role="transcript"]
....
forumdb=> insert into categories (title,description) values ('C
Language', 'Languages'), ('Python Language','Languages');
INSERT 0 2
....

.SQL
[source,sql]
....
INSERT INTO categories (title, description)
VALUES
    ('C Language', 'Languages'),
    ('Python Language', 'Languages');
....

.Output
[source,output]
....
INSERT 0 2
....


Đây là một biến thể nhỏ của lệnh `INSERT`. Bây giờ table `categories` sẽ chứa các giá trị sau:

[source,console,role="transcript"]
....
forumdb=> select * from categories;
 pk |            title            |               description
----+-----------------------+---------------------------------
  1 | Database                    | Database related discussions
  2 | Unix                        | Unix and Linux discussions
  3 | Programming Languages | All about programming languages
  4 | C Language                  | Languages
  5 | Python Language             | Languages
(5 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM categories;
....

.Output
[source,output]
....
 pk |            title            |               description
----+-----------------------+---------------------------------
  1 | Database                    | Database related discussions
  2 | Unix                        | Unix and Linux discussions
  3 | Programming Languages | All about programming languages
  4 | C Language                  | Languages
  5 | Python Language             | Languages
(5 rows)
....


[%start=6]
. Bây giờ, nếu chỉ muốn SELECT các tuple có description bằng `Database related discussions`, hãy sử dụng điều kiện WHERE:

[source,console,role="transcript"]
....
forumdb=> select * from categories where description ='Database
related discussions';
 pk |   title     |          description
----+----------+------------------------------
  1 | Database | Database related discussions
(1 row)
....

.SQL
[source,sql]
....
SELECT *
FROM categories
WHERE description = 'Database related discussions';
....

.Output
[source,output]
....
 pk |   title     |          description
----+----------+------------------------------
  1 | Database | Database related discussions
(1 row)
....


. Điều kiện WHERE lọc theo một hoặc nhiều column của table. Ví dụ, nếu muốn tìm tất cả topic có title là orange và description là fruits, chúng ta sẽ viết như sau:

[source,console,role="transcript"]
....
forumdb=> select * from categories where description = 'Languages'
and title='C Language';
 pk |     title       | description
----+------------+-------------
  4 | C Language | Languages
(1 row)
....

.SQL
[source,sql]
....
SELECT *
FROM categories
WHERE description = 'Languages' AND title = 'C Language';
....

.Output
[source,output]
....
 pk |     title       | description
----+------------+-------------
  4 | C Language | Languages
(1 row)
....


. Ví dụ, nếu muốn SELECT tất cả tuple có column description bằng `Languages` và sắp xếp theo column title theo thứ tự giảm dần, hãy thực thi như sau:

[source,console,role="transcript"]
....
forumdb=> select * from categories where description ='Languages'
order by title desc;
 pk |        title         | description
----+-----------------+-------------
  5 | Python Language | Languages
  4 | C Language           | Languages
(2 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM categories
WHERE description = 'Languages'
ORDER BY title DESC;
....

.Output
[source,output]
....
 pk |        title         | description
----+-----------------+-------------
  5 | Python Language | Languages
  4 | C Language           | Languages
(2 rows)
....


Hoặc chúng ta cũng có thể viết như sau:

[source,console,role="transcript"]
....
forumdb=> select * from categories where description ='Languages'
order by 2 desc;
 pk |        title         | description
----+-----------------+-------------
  5 | Python Language | Languages
  4 | C Language           | Languages
(2 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM categories
WHERE description = 'Languages'
ORDER BY 2 DESC;
....

.Output
[source,output]
....
 pk |        title         | description
----+-----------------+-------------
  5 | Python Language | Languages
  4 | C Language           | Languages
(2 rows)
....


Các tùy chọn `ASC` và `DESC` sắp xếp kết quả query theo thứ tự tăng dần hoặc giảm dần; nếu không chỉ định, `ASC` là mặc định.

== Giá trị NULL

Trong phần này, chúng ta sẽ tìm hiểu về giá trị `NULL`. Trong SQL, giá trị `NULL` được định nghĩa như sau:

[quote]
____
Null (hoặc NULL) là một ký hiệu đặc biệt được sử dụng trong Structured Query Language để chỉ ra rằng một giá trị dữ liệu không tồn tại trong database. Được E. F. Codd, người tạo ra relational database model, giới thiệu, SQL NULL đáp ứng yêu cầu rằng mọi Relational Database Management System (RDBMS) thực sự đều hỗ trợ việc biểu diễn thông tin bị thiếu.

____
Bây giờ hãy xem `NULL` được sử dụng trong PostgreSQL như thế nào:

. Hãy bắt đầu bằng cách chèn một tuple như sau:

[source,console,role="transcript"]
....
forumdb=> insert into categories (title) values ('A new
discussion');
INSERT 0 1
....

.SQL
[source,sql]
....
INSERT INTO categories (title)
VALUES ('A new discussion');
....

.Output
[source,output]
....
INSERT 0 1
....


. Bây giờ hãy xem các tuple hiện có trong table `categories`:

[source,console,role="transcript"]
....
forumdb=> select * from categories;
 pk |             title             |               description
----+-----------------------+---------------------------------
  1 | Database                      | Database related discussions
  2 | Unix                          | Unix and Linux discussions
  3 | Programming Languages | All about programming languages
  4 | C Language                    | Languages
  5 | Python Language               | Languages
  6 | A new discussion              |
(6 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM categories;
....

.Output
[source,output]
....
 pk |             title             |               description
----+-----------------------+---------------------------------
  1 | Database                      | Database related discussions
  2 | Unix                          | Unix and Linux discussions
  3 | Programming Languages | All about programming languages
  4 | C Language                    | Languages
  5 | Python Language               | Languages
  6 | A new discussion              |
(6 rows)
....


. Bây giờ, nếu muốn SELECT tất cả tuple không có giá trị trong column description, hãy dùng query sau:

[source,console,role="transcript"]
....
forumdb=> select * from categories where description ='';
 pk | title | description
----+-------+-------------
(0 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM categories
WHERE description = '';
....

.Output
[source,output]
....
 pk | title | description
----+-------+-------------
(0 rows)
....


Như bạn thấy, PostgreSQL không trả về tuple nào. Lý do là lần INSERT gần nhất đã đưa giá trị `NULL` vào column description.

[%start=4]
. Để xem các giá trị `NULL` hiện có trong table, hãy thực thi lệnh sau:

[source,console,role="transcript"]
....
forumdb=> \pset null NULL
Null display is "NULL".
....

.SQL
[source,sql]
....
\pset NULL NULL
....

.Output
[source,output]
....
Null display is "NULL".
....


. Lệnh này yêu cầu `psql` hiển thị các giá trị `NULL` trong table dưới dạng `NULL`, như sau:

[source,console,role="transcript"]
....
forumdb=> select * from categories;
 pk |           title             |              description
----+-----------------------+----------------------------
  1 | Database                    | Database related discussions
  2 | Unix                        | Unix and Linux discussions
  3 | Programming Languages | All about programming languages
  4 | C Language                  | Languages
  5 | Python Language             | Languages
  6 | A new discussion            | NULL
(6 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM categories;
....

.Output
[source,output]
....
 pk |           title             |              description
----+-----------------------+----------------------------
  1 | Database                    | Database related discussions
  2 | Unix                        | Unix and Linux discussions
  3 | Programming Languages | All about programming languages
  4 | C Language                  | Languages
  5 | Python Language             | Languages
  6 | A new discussion            | NULL
(6 rows)
....


Như bạn thấy, giá trị trong column description tương ứng với title `A new discussion` không phải là chuỗi rỗng (empty string) mà là giá trị `NULL`.

[%start=6]
. Bây giờ, nếu muốn xem tất cả row có giá trị `NULL` trong column description, chúng ta phải sử dụng operator `IS NULL`:

[source,console,role="transcript"]
....
forumdb=> select title,description from categories where description
is null;
       title        | description
------------------+-------------
 A new discussion | NULL
(1 row)
....

.SQL
[source,sql]
....
SELECT
    title,
    description
FROM categories
WHERE description IS NULL;
....

.Output
[source,output]
....
       title        | description
------------------+-------------
 A new discussion | NULL
(1 row)
....


Query trước đó tìm tất cả tuple không có giá trị trong column description.

[%start=7]
. Bây giờ hãy tìm tất cả tuple có giá trị trong column description bằng query sau:

[source,console,role="transcript"]
....
forumdb=> select title,description from categories where description
is not null;
           title             |               description
-----------------------+---------------------------------
 Database                    | Database related discussions
 Unix                          | Unix and Linux discussions
 Programming Languages | All about programming languages
 C Language                  | Languages
 Python Language             | Languages
(5 rows)
....

.SQL
[source,sql]
....
SELECT
    title,
    description
FROM categories
WHERE description IS NOT NULL;
....

.Output
[source,output]
....
           title             |               description
-----------------------+---------------------------------
 Database                    | Database related discussions
 Unix                          | Unix and Linux discussions
 Programming Languages | All about programming languages
 C Language                  | Languages
 Python Language             | Languages
(5 rows)
....


Để tìm kiếm giá trị `NULL` trong các column, chúng ta phải sử dụng các operator `IS NULL` / `IS NOT NULL`. Chuỗi rỗng (empty string) khác với giá trị `NULL`.

== Sắp xếp với giá trị NULL

Bây giờ hãy xem điều gì xảy ra khi sắp xếp một table có các giá trị `NULL`:

. Hãy lặp lại query sắp xếp mà chúng ta đã thực hiện trước đó:

[source,console,role="transcript"]
....
forumdb=> select * from categories order by description ;
 pk |             title             |              description
----+-----------------------+----------------------------
  3 | Programming Languages | All about programming languages
  1 | Database                      | Database related discussions
  4 | C Language                   | Languages
  5 | Python Language               | Languages
  2 | Unix                          | Unix and Linux discussions
  6 | A new discussion              | NULL
(6 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM categories
ORDER BY description;
....

.Output
[source,output]
....
 pk |             title             |              description
----+-----------------------+----------------------------
  3 | Programming Languages | All about programming languages
  1 | Database                      | Database related discussions
  4 | C Language                   | Languages
  5 | Python Language               | Languages
  2 | Unix                          | Unix and Linux discussions
  6 | A new discussion              | NULL
(6 rows)
....


Như bạn thấy, tất cả giá trị trong column description được sắp xếp và giá trị `NULL` được đặt ở cuối tập kết quả. Có thể đạt được kết quả tương tự bằng cách chạy query sau:

[source,console,role="transcript"]
....
forumdb=> select * from categories order by description NULLS last;
 pk |           title              |              description
----+----------------------------+----------------------------
  3 | Programming Languages | All about programming languages
  1 | Database                     | Database related discussions
  4 | C Language                   | Languages
  5 | Python Language              | Languages
  2 | Unix                         | Unix and Linux discussions
  6 | A new discussion             | NULL
(6 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM categories
ORDER BY description NULLS last;
....

.Output
[source,output]
....
 pk |           title              |              description
----+----------------------------+----------------------------
  3 | Programming Languages | All about programming languages
  1 | Database                     | Database related discussions
  4 | C Language                   | Languages
  5 | Python Language              | Languages
  2 | Unix                         | Unix and Linux discussions
  6 | A new discussion             | NULL
(6 rows)
....


[%start=2]
. Nếu muốn đặt giá trị `NULL` ở đầu, chúng ta phải thực hiện như sau:

[source,console,role="transcript"]
....
forumdb=> select * from categories order by description NULLS first;
 pk |           title         |              description
----+-----------------+---------------------------------
  6 | A new discussion             | NULL
  3 | Programming Languages | All about programming languages
  1 | Database                     | Database related discussions
  4 | C Language                   | Languages
  5 | Python Language              | Languages
  2 | Unix                         | Unix and Linux discussions
(6 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM categories
ORDER BY description NULLS first;
....

.Output
[source,output]
....
 pk |           title         |              description
----+-----------------+---------------------------------
  6 | A new discussion             | NULL
  3 | Programming Languages | All about programming languages
  1 | Database                     | Database related discussions
  4 | C Language                   | Languages
  5 | Python Language              | Languages
  2 | Unix                         | Unix and Linux discussions
(6 rows)
....


Nếu không chỉ định, query dùng `ORDER BY` sẽ mặc định áp dụng các quy tắc sau:

`ORDER BY NULLS LAST` là mặc định khi dùng `ASC` (cũng là mặc định), còn `NULLS FIRST` là mặc định khi dùng `DESC`.

== Tạo table từ một table khác

Bây giờ chúng ta sẽ xem cách tạo một table mới từ dữ liệu của một table khác. Để làm việc này, bạn cần tạo một temporary table chứa dữ liệu hiện có trong table `categories`, như sau:

[source,console,role="transcript"]
....
forumdb=> create temp table temp_categories as select * from categories;
SELECT 6
....

.SQL
[source,sql]
....
CREATE TEMP TABLE temp_categories AS SELECT * FROM categories;
....

.Output
[source,output]
....
SELECT 6
....


Lệnh này tạo một table có tên `temp_data` với cùng cấu trúc dữ liệu và dữ liệu như table `categories`:

[source,console,role="transcript"]
....
forumdb=> select * from temp_categories ;
 pk |              title            |              description
----+-----------------------+----------------------------
     1 | Database                   | Database related discussions
     2 | Unix                       | Unix and Linux discussions
     3 | Programming Languages | All about programming languages
     4 | C Language                 | Languages
     5 | Python Language            | Languages
     6 | A new discussion           | NULL
(6 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM temp_categories;
....

.Output
[source,output]
....
 pk |              title            |              description
----+-----------------------+----------------------------
     1 | Database                   | Database related discussions
     2 | Unix                       | Unix and Linux discussions
     3 | Programming Languages | All about programming languages
     4 | C Language                 | Languages
     5 | Python Language            | Languages
     6 | A new discussion           | NULL
(6 rows)
....


== Cập nhật dữ liệu

Bây giờ hãy thử cập nhật một số dữ liệu:

. Nếu muốn đổi giá trị Unix thành Linux, bạn cần chạy statement sau:

[source,console,role="transcript"]
....
   forumdb=> update temp_categories set title='Linux' where pk = 2;
   UPDATE 1
....

.SQL
[source,sql]
....
UPDATE temp_categories
SET
    title = 'Linux'
WHERE pk = 2;
....

.Output
[source,output]
....
   UPDATE 1
....


   Statement này sẽ đổi giá trị Unix thành Linux trong column `title` của mọi row trong table `temp_categories` có `pk=2`, như sau:

[source,console,role="transcript"]
....
   forumdb=> select * from temp_categories where pk=2;
    pk | title |             description
   ----+-------+----------------------------
     2 | Linux | Unix and Linux discussions
   (1 row)
....

.SQL
[source,sql]
....
SELECT *
FROM temp_categories
WHERE pk = 2;
....

.Output
[source,output]
....
    pk | title |             description
   ----+-------+----------------------------
     2 | Linux | Unix and Linux discussions
   (1 row)
....


[%start=2]
. Nếu muốn đổi giá trị `title` của tất cả row có giá trị `description` là Languages, bạn cần chạy statement sau:

[source,console,role="transcript"]
....
   forumdb=> update temp_categories set title = 'no title' where
   description = 'Languages';
   UPDATE 2
....

.SQL
[source,sql]
....
UPDATE temp_categories
SET
    title = 'no title'
WHERE description = 'Languages';
....

.Output
[source,output]
....
   UPDATE 2
....


`UPDATE 2` cho biết chỉ có hai row được sửa đổi, như minh họa sau:

[source,console,role="transcript"]
....
forumdb=> select * from temp_categories order by description;
 pk |           title            |             description
----+----------------------------+----------------------------
  3 | Programming Languages | All about programming languages
  1 | Database                   | Database related discussions
  4 | no title                   | Languages
  5 | no title                   | Languages
  2 | Linux                      | Unix and Linux discussions
  6 | A new discussion           | NULL
(6 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM temp_categories
ORDER BY description;
....

.Output
[source,output]
....
 pk |           title            |             description
----+----------------------------+----------------------------
  3 | Programming Languages | All about programming languages
  1 | Database                   | Database related discussions
  4 | no title                   | Languages
  5 | no title                   | Languages
  2 | Linux                      | Unix and Linux discussions
  6 | A new discussion           | NULL
(6 rows)
....


Bạn phải hết sức cẩn thận khi sử dụng lệnh `UPDATE`. Nếu làm việc ở chế độ auto-commit, bạn sẽ không thể hoàn tác sau khi cập nhật hoàn tất. Auto-commit là chế độ mặc định trong `psql`.

== Xóa dữ liệu

Trong phần này, chúng ta sẽ xem cách xóa dữ liệu khỏi một table. Lệnh cần dùng để xóa dữ liệu là `delete`. Hãy bắt đầu:

. Nếu muốn xóa tất cả row trong table `temp_categories` có `pk=5`, chúng ta phải thực hiện lệnh sau:

[source,console,role="transcript"]
....
   forumdb=> delete from temp_categories where pk=5;
   DELETE 1
....

.SQL
[source,sql]
....
DELETE FROM temp_categories WHERE pk = 5;
....

.Output
[source,output]
....
   DELETE 1
....


   Statement trên xóa tất cả row có `pk=5`. `DELETE 1` có nghĩa là một row đã bị xóa. Như bạn thấy, row có giá trị `pk=5` không còn trong `temp_categories`:

[source,console,role="transcript"]
....
   forumdb=>   select * from temp_categories where pk=5;
    pk | title | description
   ----+-------+-------------
   (0 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM temp_categories
WHERE pk = 5;
....

.Output
[source,output]
....
    pk | title | description
   ----+-------+-------------
   (0 rows)
....


[%start=2]
. Bây giờ, nếu muốn xóa tất cả row có giá trị `description` bằng `NULL`, chúng ta phải thực thi statement này:

[source,console,role="transcript"]
....
   forumdb=> delete from temp_categories where description is null;
   DELETE 1
....

.SQL
[source,sql]
....
DELETE FROM temp_categories WHERE description IS NULL;
....

.Output
[source,output]
....
   DELETE 1
....


Statement này sử dụng lệnh `DELETE` kết hợp với operator `IS NULL`.

[%start=3]
. Nếu muốn xóa tất cả row khỏi một table, bạn phải thực thi lệnh sau:

[source,console,role="transcript"]
....
   forumdb=> delete from temp_categories ;
   DELETE 4
....

.SQL
[source,sql]
....
DELETE FROM temp_categories;
....

.Output
[source,output]
....
   DELETE 4
....


[quote]
____
Hãy hết sức cẩn thận khi sử dụng lệnh này - tất cả row hiện có trong table sẽ bị xóa!

____
Bây giờ table `temp_categories` trống, như minh họa sau:

[source,console,role="transcript"]
....
forumdb=> select * from temp_categories;
 pk | title | description
----+-------+-------------
(0 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM temp_categories;
....

.Output
[source,output]
....
 pk | title | description
----+-------+-------------
(0 rows)
....


[%start=4]
. Nếu muốn nạp lại toàn bộ dữ liệu từ table `categories` vào table `temp_categories`, chúng ta phải thực thi statement này:

[source,console,role="transcript"]
....
   forumdb=> insert into temp_categories select * from categories;
   INSERT 0 6
....

.SQL
[source,sql]
....
INSERT INTO temp_categories SELECT * FROM categories;
....

.Output
[source,output]
....
   INSERT 0 6
....


   Statement trên lấy tất cả giá trị từ table `categories` và đưa chúng vào table `temp_categories`, như bạn thấy ở đây:

[source,console,role="transcript"]
....
   forumdb=> select * from temp_categories order by description;
    pk |            title            |              description
   ----+----------------------------+----------------------------
     3 | Programming Languages | All about programming languages
     1 | Database                    | Database related discussions
     4 | C Language                  | Languages
     5 | Python Language             | Languages
     2 | Unix                        | Unix and Linux discussions
     6 | A new discussion            | NULL
   (6 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM temp_categories
ORDER BY description;
....

.Output
[source,output]
....
    pk |            title            |              description
   ----+----------------------------+----------------------------
     3 | Programming Languages | All about programming languages
     1 | Database                    | Database related discussions
     4 | C Language                  | Languages
     5 | Python Language             | Languages
     2 | Unix                        | Unix and Linux discussions
     6 | A new discussion            | NULL
   (6 rows)
....


[%start=5]
. Một cách khác để xóa dữ liệu là sử dụng lệnh `TRUNCATE`. Khi muốn xóa toàn bộ dữ liệu khỏi một table mà không cung cấp điều kiện `where`, chúng ta có thể sử dụng lệnh `TRUNCATE`:

[source,console,role="transcript"]
....
   forumdb=> truncate table temp_categories ;
   TRUNCATE TABLE
....

.SQL
[source,sql]
....
truncate TABLE temp_categories;
....

.Output
[source,output]
....
   TRUNCATE TABLE
....


Lệnh `TRUNCATE` xóa toàn bộ dữ liệu trong một table. Như bạn thấy, table `temp_categories` hiện đã trống:

[source,console,role="transcript"]
....
forumdb=> select * from temp_categories;
 pk | title | description
 ----+-------+-------------
(0 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM temp_categories;
....

.Output
[source,output]
....
 pk | title | description
 ----+-------+-------------
(0 rows)
....


Sau đây là một số thông tin quan trọng về lệnh `TRUNCATE`:

* `TRUNCATE` xóa tất cả row trong một table, tương tự lệnh `DELETE`.
* Trong lệnh `TRUNCATE`, không thể sử dụng điều kiện WHERE.
* Lệnh `TRUNCATE` xóa row nhanh hơn nhiều so với lệnh `DELETE`.
