= Thống kê nâng cao với pg_stat_statements

Mặc dù statistics collector của PostgreSQL rất phong phú và hoàn thiện, việc theo dõi activity của connection có thể hơi phức tạp vì catalog `pg_stat_activity` không cung cấp thông tin lịch sử. Như đã giải thích trước đó, catalog này chỉ có một tuple chứa statement được thực thi gần nhất, nên không cung cấp lịch sử hoặc các chi tiết mở rộng khác.

Extension `pg_stat_statements` giải quyết vấn đề này bằng cách cung cấp một view duy nhất cho phép xem lịch sử các statement đã thực thi, timing và một số chi tiết khác có thể rất hữu ích cho việc introspection. Ngoài ra, `pg_stat_statements` cung cấp số lần mỗi statement được thực thi, từ đó tạo ra thông tin quan trọng để xác định những query có thể cần được chú ý nhằm phục vụ việc tối ưu hóa.

Một số công cụ monitoring yêu cầu cài đặt `pg_stat_statements` để thu thập dữ liệu.

Trong các phần tiếp theo, bạn sẽ học cách cài đặt và sử dụng extension này.

== Cài đặt extension pg_stat_statements

Extension này được đóng gói cùng PostgreSQL, vì vậy bạn chỉ cần cấu hình database cluster để sử dụng nó. Vì `pg_stat_statements` yêu cầu một shared library, bạn cần cấu hình parameter `shared_preload_libraries` trong file `postgresql.conf` rồi restart cluster.

Trước hết, đặt giá trị sau trong `postgresql.conf`:

[source,text]
....
shared_preload_libraries = 'pg_stat_statements'
....

Hoặc sử dụng `ALTER SYSTEM` như sau:

[source,sql]
....
ALTER SYSTEM SET shared_preload_libraries to 'pg_stat_statements';
....

Vì `pg_shared_preload_libraries` là một parameter có context `postmaster`, bạn cần restart cluster để các thay đổi có hiệu lực.

`pg_stat_statements` thu thập thông tin về toàn bộ database trong cluster, nhưng chỉ cung cấp thông tin đó trong database nơi bạn tạo extension; trong ví dụ này, đó là database `forumdb`:

[source,console,role="transcript"]
....
$ psql -U postgres -c "CREATE EXTENSION pg_stat_statements;" forumdb
CREATE EXTENSION
....

.Command
[source,bash]
....
psql -U postgres -c "CREATE EXTENSION pg_stat_statements;" forumdb
....

.Output
[source,output]
....
CREATE EXTENSION
....


Extension hiện đã sẵn sàng để sử dụng.

[quote]
____
Trong Docker image của chương này, extension `pg_stat_statements` đã được cài đặt và load vào database `forumdb`.

____
== Sử dụng pg_stat_statements

Khi `pg_stat_statements` được enable, extension bắt đầu thu thập thông tin. Runtime overhead của extension thực sự rất nhỏ, vì vậy bạn có thể giữ extension enable trong production system.

Vì `pg_stat_statements` thu thập dữ liệu trên toàn bộ cluster, việc join view chuyên dụng `pg_stat_statements` với các catalog khác, chẳng hạn `pg_database` và `pg_authid`, sẽ hữu ích để biết statement được thực thi trong database nào và bởi username nào. Query sau đây là một ví dụ:

[source,console,role="transcript"]
....
forumdb=# SELECT auth.rolname,query, db.datname, calls, min_exec_time,
max_exec_time
 FROM pg_stat_statements
          JOIN pg_authid auth ON auth.oid = userid
          JOIN pg_database db ON db.oid = dbid
 ORDER BY calls DESC;
...
rolname            | postgres
query         | SELECT count(*) FROM forum.posts WHERE last_edited_on >=
CURRENT_DATE - $1
datname            | forumdb
calls              | 17
min_exec_time | 0.037292
max_exec_time | 0.04165
....

.SQL
[source,sql]
....
SELECT
    auth.rolname,
    query,
    db.datname,
    calls,
    min_exec_time,
    max_exec_time
FROM pg_stat_statements JOIN pg_authid auth ON auth.oid = userid JOIN pg_database db ON db.oid = dbid
ORDER BY calls DESC;
....

.Output
[source,output]
....
...
rolname            | postgres
query         | SELECT count(*) FROM forum.posts WHERE last_edited_on >=
CURRENT_DATE - $1
datname            | forumdb
calls              | 17
min_exec_time | 0.037292
max_exec_time | 0.04165
....


Ví dụ trước cho thấy query đã được thực thi 17 lần kể từ khi `pg_stat_statements` bắt đầu thu thập dữ liệu, và có execution time từ 0.037 đến 0.042 milliseconds. Tùy thuộc vào tần suất và execution time của từng query, việc kiểm tra và tối ưu query bằng index có thể đáng cân nhắc.

Trong ví dụ trên, query được báo cáo dưới dạng normalized query: mọi parameter, kể cả literal, đều bị loại bỏ và thay thế bằng placeholder `$1` (các parameter khác sẽ được đánh dấu là `$2`, `$3`, v.v.): `SELECT count(*) FROM forum.posts WHERE last_edited_on >= CURRENT_DATE - $1`.

Ý tưởng là theo dõi một nhóm query có cùng normalized text, để biết nhóm đó đã được thực thi bao nhiêu lần, ngay cả khi các query có argument khác nhau.

View chuyên dụng `pg_stat_statements` theo dõi các query được thực thi thường xuyên nhất, với số lượng tối đa bằng giá trị của configuration parameter `pg_stat_statements.max`, mặc định là 5000. Khi đạt đến giới hạn, các query ít được thực thi nhất sẽ bị loại bỏ để nhường chỗ cho các query mới. Điều này bảo đảm không gian mà view `pg_stat_statements` chiếm dụng gần như không đổi, bất kể số statement đã được thực thi.

View `pg_stat_statements` cung cấp nhiều column mà ở đây không thể thảo luận chi tiết, từ planning time đến buffer và I/O activity. Extension này rất hữu ích khi bạn muốn xử lý workload của cluster.

== Reset dữ liệu do pg_stat_statements thu thập

Database administrator có thể reset toàn bộ dữ liệu mà extension đã thu thập bất cứ lúc nào bằng cách gọi function `pg_stat_statements_reset()`. Function này xóa toàn bộ dữ liệu đã thu thập và cho phép extension bắt đầu lại từ đầu. Điều này có thể hữu ích khi bạn muốn test configuration hoặc hardware mới mà không để statistics cũ làm bias dữ liệu mới:

[source,console,role="transcript"]
....
forumdb=# SELECT pg_stat_statements_reset();
....

.SQL
[source,sql]
....
SELECT pg_stat_statements_reset();
....


Theo mặc định, dữ liệu của `pg_stat_statements` được giữ lại qua các lần shutdown và restart database thông thường.

== Tinh chỉnh pg_stat_statements

Extension cho phép database administrator giới hạn lượng dữ liệu được thu thập. Cụ thể, bạn có thể điều chỉnh các parameter sau trong configuration file `postgresql.conf`:

* `pg_stat_statements.max` cho biết số lượng query riêng lẻ tối đa cần thu thập.
* `pg_stat_statements.save` là một Boolean cho biết dữ liệu đã thu thập có được giữ lại sau một lần reboot hệ thống thông thường hay không. Theo mặc định, setting này là true.
* `pg_stat_statements.track` cho phép bạn chỉ định nesting level cần theo dõi. Với giá trị `top`, extension chỉ thu thập dữ liệu về query do client issue trực tiếp; các nested statement, chẳng hạn statement bên trong function, không được theo dõi. Với giá trị `all`, extension theo dõi mọi statement và các descendant của chúng, còn với `none`, extension không thu thập dữ liệu về user statement.
* `pg_stat_statements.track_utility` theo dõi mọi statement không phải `SELECT`, `INSERT`, `UPDATE` hoặc `DELETE` - nói cách khác là các statement “non-ordinary”. Theo mặc định, setting này là `on`.

Thông thường, bạn không cần điều chỉnh các setting này vì `pg_stat_statements` đã được cấu hình sẵn để theo dõi đủ thông tin cho hầu hết use case.
