= Partitioning và tablespace

Bây giờ giả sử chúng ta muốn sử dụng các tablespace đã xem trong Chapter 2 cùng với cách partitioning vừa thực hiện. Bằng kỹ thuật này, chúng ta có thể đặt các child table trên những tablespace khác nhau, và do đó trên những directory khác nhau có thể được mount trên các volume khác nhau.

Cách làm này có thể tăng read/write performance. Trong ví dụ sau, chúng ta sẽ chỉ tạo hai tablespace trên các local directory. Tuy nhiên, không khó để sử dụng command `mount` nhằm map hai directory này vào các volume khác nhau. Nếu đang sử dụng Docker image được cung cấp cùng chapter này, hai directory chúng ta sẽ dùng đã có sẵn.

Nếu không sử dụng Docker image, trước tiên bạn cần tạo hai directory, `/data/tablespaces/ts_b` và `/data/tablespaces/ts_b`, nơi system user `postgres` có thể read và write data.

Bây giờ hãy connect tới database `forumdb` với tư cách user `postgres` và tạo hai tablespace có tên `ts_a` và `ts_b`:

[source,text]
....
   postgres@learn_postgresql:~$ psql -U postgres forumdb


   forumdb=# create tablespace ts_a location '/data/tablespaces/ts_a';
   CREATE TABLESPACE
   forumdb=# create tablespace ts_b location '/data/tablespaces/ts_b';
   CREATE TABLESPACE
....

Hãy gán ownership cho user `postgres`:

[source,text]
....
   forumdb=# alter tablespace ts_a owner to forum ;
   ALTER TABLESPACE
   forumdb=#      alter tablespace ts_b owner to forum ;
   ALTER TABLESPACE
....

Bây giờ hãy connect lại tới database `forumdb` với tư cách user `forum`:

[source,text]
....
   forumdb=# \q
   postgres@learn_postgresql:~$ psql -U forum forumdb
....

Như trong trường hợp trước, hãy tạo lại parent table:

[source,text]
....
   forumdb=> CREATE TABLE tablespace_part_tags (
            pk serial NOT NULL,
            ins_date date not null default now()::date,
            tag VARCHAR (255) NOT NULL,
            level INTEGER NOT NULL DEFAULT 0,

          primary key (pk,ins_date)
   )
   PARTITION BY RANGE (ins_date);
   CREATE TABLE
....

Bây giờ hãy tạo hai child table và một default table. Child table đầu tiên sẽ được tạo trên tablespace `ts_a` và child table thứ hai trên tablespace `ts_b`:

[source,text]
....
   forumdb=> CREATE TABLE tablespace_part_tags_date_2022 PARTITION OF
   tablespace_part_tags FOR VALUES FROM ('2021-01-01') TO ('2022-12-31')
   TABLESPACE ts_a;
   CREATE TABLE
   forumdb=> CREATE TABLE tablespace_part_tags_date_2023 PARTITION OF
   tablespace_part_tags FOR VALUES FROM ('2023-01-01') TO ('2023-12-31')
   TABLESPACE ts_b;
   CREATE TABLE
   forumdb=> CREATE TABLE tablespace_part_tags_date_default PARTITION OF
   tablespace_part_tags default;
   CREATE TABLE
....

Bây giờ, hãy insert một số data:

[source,text]
....
   forumdb=> insert into tablespace_part_tags (tag,ins_date,level) values
   ('Operating Systems','2022-01-01',0), ('Linux','2022-02-01',1),('BSD
   Unix','2023-03-01',1),('Rocky Linux Distro','2018-04-01',2);
   INSERT 0 4
....

Sau đó, hãy xem các record đã được lưu ở đâu:

[source,text]
....
   forumdb=> select * from tablespace_part_tags;
      pk |   ins_date   |         tag            | level


   ----+------------+--------------------+-------
       1 | 2022-01-01 | Operating Systems        |      0
       2 | 2022-02-01 | Linux                    |      1
       3 | 2023-03-01 | BSD Unix                 |      1
       4 | 2018-04-01 | Rocky Linux Distro |            2
   (4 rows)


   forumdb=> select * from tablespace_part_tags_date_2022 ;
      pk |   ins_date   |         tag           | level


   ----+------------+-------------------+-------
      1 | 2022-01-01 | Operating Systems |               0
      2 | 2022-02-01 | Linux                      |      1
   (2 rows)


   forumdb=> select * from tablespace_part_tags_date_2023 ;
    pk |    ins_date    |     tag     | level


   ----+------------+----------+-------
      3 | 2023-03-01 | BSD Unix |             1
   (1 row)


   forumdb=>select * from tablespace_part_tags_date_default;
    pk |    ins_date    |           tag            | level


   ----+------------+--------------------+-------
      4 | 2018-04-01 | Rocky Linux Distro |                2
   (1 row)
....

Như chúng ta đã thấy trong exercise này, data đã được chia vào các tablespace khác nhau, và kết quả là tốc độ đã tăng gấp đôi. Đây là một kỹ thuật rất hiệu quả.
