= 10 Users, Roles và Database Security

PostgreSQL là một database mạnh và ổn định, đặc biệt chú trọng đến security, đồng thời cung cấp một infrastructure phong phú để quản lý privilege và security policy. Chương này dựa trên các khái niệm cơ bản được giới thiệu trong Chapter 3, *Managing Users and Connections*, ôn lại khái niệm role và mở rộng kiến thức, tập trung vào security và các privilege được cấp cho role. Một role có thể vừa là một user, vừa là một group gồm nhiều user. Bạn sẽ học cách cấu hình các khía cạnh của role để quản lý security cẩn thận, từ connection đến quyền truy cập data trong database.

PostgreSQL cũng cung cấp một cơ chế mạnh có tên là Row-Level Security (RLS), cho phép định nghĩa policy chi tiết để giới hạn phần data mà một số user có thể truy cập.

Trong chương này, bạn cũng sẽ tìm hiểu về Access Control List (ACL) và cách PostgreSQL biểu diễn, xử lý các privilege nội bộ do thao tác GRANT và REVOKE tạo ra. Cuối cùng, bạn sẽ xem xét ngắn gọn các thuật toán mã hóa password mà PostgreSQL cung cấp để lưu password của role một cách an toàn.

Chương này bao gồm các chủ đề sau:

* Tìm hiểu về role
* ACL
* GRANT và REVOKE privilege
* RLS
* Mã hóa password của role
* SSL connection
