= 17. Physical Replication

Khi một database, sau khi trải qua các giai đoạn development và testing, đi vào production, vấn đề đầu tiên DBA phải giải quyết là quản lý replica. Replica phải được quản lý theo real time và tự động update. Replica cho phép chúng ta luôn có một bản sao data được update theo real time trên một machine khác. Machine này có thể nằm trong cùng data center với data của chúng ta hoặc ở một data center khác. Chapter này khác với mọi nội dung chúng ta đã xem trước đó ở chỗ chúng ta sẽ nói về physical replication. Trong PostgresSQL, bắt đầu từ version 9.x, physical replication được hỗ trợ native. Chúng ta sẽ nói về physical replication nghĩa là gì, và xem cách tạo replica server cũng như cách quản lý nó. Chúng ta cũng sẽ thấy có thể có replica synchronous hoặc asynchronous, có thể có nhiều replica của cùng một database, cũng như khả năng có các replica theo mô hình cascade.

Trong chapter này, chúng ta sẽ quay lại chủ đề WAL, điều đã được thảo luận trong Chapter 11, Transactions, MVCC, WAL, and Checkpoints. Để thực thi các command sẽ được trình bày trong chapter này, chúng ta cần cài đặt một PostgreSQL server trên hai machine, hoặc cài đặt hai instance PostgreSQL trên cùng một machine nhưng chạy trên các port khác nhau. Trong phần còn lại của chapter, giả định là bạn có hai PostgreSQL installation trên các machine khác nhau để mô phỏng tốt hơn tình huống của một production environment thực tế; bắt đầu từ chapter này, chúng ta sẽ học cách cài đặt và cấu hình một physical replication.
Trong chương này, khi nói về cách cài đặt một hệ thống replication, chúng ta sẽ không sử dụng Docker container; lý do là để cài đặt một replication service, cần tắt postgresql service trên replica server, và việc tắt một service trong môi trường Docker sẽ tắt toàn bộ container. Tuy nhiên, trên Docker, việc tắt postgresql và khởi động lại nó cùng lúc có thể được thực hiện khi Docker container khởi động lần đầu, vì vậy để hiểu rõ hơn cách cài đặt một replica trên production server, tốt hơn là không sử dụng Docker container (ngay cả khi trong GitLab repo có một số container mà bạn có thể sử dụng). Trong chương này, Docker chỉ được dùng để hỗ trợ người đọc không muốn cài đặt một replica server nhưng muốn tìm hiểu bằng cách xem physical replication hoạt động như thế nào; đối với mọi nội dung liên quan đến phần cài đặt, chúng ta sẽ tham chiếu đến các path của Debian server thay vì các path của Docker image.
