= Ví dụ về query tuning

Trong section trước, bạn đã tìm hiểu cách `EXPLAIN` có thể hiển thị plan mà PostgreSQL sẽ dùng để truy cập underlying data; bây giờ là lúc dùng `EXPLAIN` để tune một số slow query và cải thiện performance.

Section này sẽ trình bày một số concept cơ bản trong việc sử dụng `EXPLAIN` hằng ngày như một tool mạnh để xác định PostgreSQL nên được instrument ở đâu và bằng cách nào để truy cập data nhanh hơn. Dĩ nhiên, query tuning là một chủ đề rất phức tạp và thường đòi hỏi optimization dựa trên việc thử nghiệm lặp lại, vì vậy mục tiêu của section này không phải là cung cấp cho bạn kiến thức chuyên sâu về query tuning, mà là giúp bạn có hiểu biết cơ bản về cách cải thiện database và query của chính mình.

Đôi khi, tuning một query chỉ đơn giản là viết lại query theo cách PostgreSQL thấy dễ xử lý hơn hoặc, chính xác hơn, dễ hiểu hơn; nhưng thường thì query tuning có nghĩa là sử dụng một index phù hợp để tăng tốc việc truy cập underlying data.

Một điều quan trọng cần tính đến khi query tuning là cache effect: khi PostgreSQL truy cập một phần data, nó load data đó vào memory trong shared buffers. Vùng memory này hoạt động như một cache; vì vậy, nếu PostgreSQL lại cần cùng data đó, nó sẽ lấy data từ memory thay vì đi tới disk storage. Hệ quả là query có thể chậm ở lần đầu, nhưng nếu được thực thi lần thứ hai và nói chung là thực thi lặp đi lặp lại, thời gian cần thiết có thể nhỏ hơn lần đầu. Vì vậy, khi kiểm tra một slow query, hãy thử thực thi nó nhiều lần hơn để xem caching effect có thể ảnh hưởng đến thời gian thực thi như thế nào.

Database của chúng ta được giả định là chứa một nghìn author, mỗi author publish năm trăm post, tổng cộng nửa triệu post:

[source,text]
....
forumdb=> SELECT reltuples, pg_size_pretty( pg_relation_size( oid ) ),
relname FROM pg_class
WHERE relname IN ( 'posts', 'users' ) AND relkind = 'r';
reltuples | pg_size_pretty | relname
-----------+----------------+---------
    500000 | 59 MB                 | posts
      1000 | 88 kB                 | users
....

[quote]
____
Docker image cho chapter này đã được populate sẵn với lượng data trên. Hãy cẩn thận, vì lượng data đó sẽ yêu cầu bạn có khoảng 60 MB free disk space.

____
Hãy bắt đầu với một ví dụ đơn giản; chúng ta muốn lấy tất cả post theo thứ tự ngày tạo, vì vậy query là:

[source,sql]
....
SELECT * FROM posts ORDER BY created_on;
....

Chúng ta có thể truyền query này cho `EXPLAIN` để có được hình dung về cách PostgreSQL sẽ thực thi nó:

[source,text]
....
forumdb=> EXPLAIN SELECT * FROM posts ORDER BY created_on;
                                         QUERY PLAN
---------------------------------------------------------------------
Sort       (cost=83838.92..85088.92 rows=500000 width=81)
   Sort Key: created_on
   ->      Seq Scan on posts     (cost=0.00..12584.00 rows=500000 width=81)
....

Như bạn có thể thấy, node đầu tiên được thực thi là sequential scan (initial cost là 0), node này sẽ tạo ra 500.000 tuple làm output. Tại sao lại là sequential scan? Trước hết, không có filtering clause nào, vì chúng ta muốn lấy toàn bộ data được lưu trong table; thứ hai, table không có access method nào (không có index).

Vì chúng ta yêu cầu sort output, node tiếp theo được thực thi là một Sorting node, node này tạo ra đúng cùng số tuple trong result.

Mất bao nhiêu thời gian để hoàn tất query trước đó? `EXPLAIN ANALYZE` có thể giúp chúng ta trả lời câu hỏi đó:

[source,text]
....
forumdb=> EXPLAIN ANALYZE SELECT * FROM posts ORDER BY created_on;
                                                           ------------------
--------------------------------------------------------------------------
-------------------------
Sort (cost=83838.92..85088.92 rows=500000 width=81) (actual
time=304.283..393.395 rows=500000 loops=1)
   Sort Key: created_on
   Sort Method: external merge       Disk: 51192kB
     -> Seq Scan on posts (cost=0.00..12584.00 rows=500000 width=81)
(actual time=0.045..63.449 rows=500000 loops=1)
Planning Time: 0.059 ms
Execution Time: 429.838 ms
....

Pure execution time gần nửa giây. Có thể giảm tổng thời gian bằng cách build một index riêng trên field `created_on` hay không:

[source,text]
....
forumdb=> CREATE INDEX idx_posts_date ON posts( created_on );
CREATE INDEX
forumdb=> EXPLAIN ANALYZE SELECT * FROM posts ORDER BY created_on;


QUERY PLAN
--------------------------------------------------------------------------
-------------------------------------------------------------
Index Scan using idx_posts_date on posts (cost=0.42..16887.80 rows=500000
width=81) (actual time=0.079..133.305 rows=500000 loops=1)
Planning Time: 0.203 ms
Execution Time: 162.143 ms
(3 rows)
....

Query hiện chạy trong gần một phần ba thời gian cần thiết khi không có index, và trên thực tế query plan đã thay đổi từ sequential scan thành index scan với index mới được tạo.

Dĩ nhiên, index mới được tạo có penalty về storage space; như bạn có thể hình dung, tốc độ tăng lên đi kèm một space cost bổ sung, có thể kiểm tra như sau:

[source,text]
....
forumdb=> SELECT pg_size_pretty( pg_relation_size( 'posts' ) ) AS table_
size,
    pg_size_pretty( pg_relation_size( 'idx_posts_date' ) ) AS index_size;
   table_size | index_size
-------------+------------
59 MB         | 3600 kB
(1 row)
....

Việc space disk bổ sung này có quá nhiều hay không phụ thuộc vào resource và mục tiêu cuối cùng của bạn; trong trường hợp trước, giả sử bạn thực thi query khá thường xuyên, tốc độ tăng lên là xứng đáng với space bổ sung.

Bây giờ hãy tập trung vào một query điển hình hơn: tìm tất cả post của một user cụ thể trong một khoảng thời gian cụ thể. Query kết quả sẽ giống như sau, với giả định khoảng thời gian là 2 ngày:

[source,sql]
....
SELECT p.title, u.username
FROM posts p
JOIN users u ON u.pk = p.author
WHERE u.username = 'fluca1978'
AND       daterange( CURRENT_DATE - 20, CURRENT_DATE ) @> p.created_on::date
....

PostgreSQL thực thi query trước đó như thế nào? Một lần nữa, `EXPLAIN` có thể giúp chúng ta hiểu database cho rằng query plan tốt nhất là gì:

[source,text]
....
forumdb=> EXPLAIN
      SELECT p.title, u.username
      FROM posts p
      JOIN users u ON u.pk = p.author
      WHERE u.username = 'fluca1978'
    AND   daterange( CURRENT_DATE - 20, CURRENT_DATE ) @> p.created_
on::date;


                                              QUERY PLAN
--------------------------------------------------------------------------
---------------------------
Gather      (cost=1008.30..13803.58 rows=2 width=26)
   Workers Planned: 2
   ->     Hash Join     (cost=8.30..12803.38 rows=1 width=26)
            Hash Cond: (p.author = u.pk)
        ->       Parallel Seq Scan on posts p     (cost=0.00..12792.33 rows=1042
width=15)
              Filter: (daterange((CURRENT_DATE - 2), CURRENT_DATE) @>
(created_on)::date)
            ->   Hash    (cost=8.29..8.29 rows=1 width=19)
              -> Index Scan using users_username_key on users u
(cost=0.28..8.29 rows=1 width=19)
                         Index Cond: (username = 'fluca1978'::text)
....

Planner đã chọn khởi chạy parallel query execution: node ở trên cùng là một Gather node, vì vậy nó hoạt động như một synchronization point cho các parallel worker. Cụ thể, planner quyết định sử dụng hai parallel process để hoàn tất query. Node ngoài cùng bên phải, và do đó là node đầu tiên được thực thi, là một Index Scan node trên table users. Các result được hash, đồng thời một Parallel Seq Scan được khởi chạy để lấy data từ table posts. Các result được join và Gather thu thập final result set. Tổng execution time của query này có thể dễ dàng lấy được bằng `EXPLAIN ANALYZE`, cho thấy query mất khoảng 140 millisecond để hoàn tất:

[source,text]
....
forumdb=> EXPLAIN ANALYZE
     SELECT p.title, u.username
     FROM posts p
     JOIN users u ON u.pk = p.author
     WHERE u.username = 'fluca1978'
    AND   daterange( CURRENT_DATE - 20, CURRENT_DATE ) @> p.created_
on::date;




   QUERY PLAN
--------------------------------------------------------------------------
---------------------------------------------------------------------
Gather (cost=1008.30..13803.58 rows=2 width=26) (actual
time=0.856..141.434 rows=20 loops=1)
   Workers Planned: 2
   Workers Launched: 2
  -> Hash Join (cost=8.30..12803.38 rows=1 width=26) (actual
time=0.968..135.209 rows=7 loops=3)
          Hash Cond: (p.author = u.pk)
        -> Parallel Seq Scan on posts p (cost=0.00..12792.33 rows=1042
width=15) (actual time=0.076..133.975 rows=6667 loops=3)
              Filter: (daterange((CURRENT_DATE - 20), CURRENT_DATE) @>
(created_on)::date)
                 Rows Removed by Filter: 160000
        -> Hash (cost=8.29..8.29 rows=1 width=19) (actual
time=0.053..0.054 rows=1 loops=3)
                 Buckets: 1024      Batches: 1     Memory Usage: 9kB
             -> Index Scan using users_username_key on users u
(cost=0.28..8.29 rows=1 width=19) (actual time=0.047..0.048 rows=1
loops=3)
                      Index Cond: (username = 'fluca1978'::text)
Planning Time: 0.188 ms
Execution Time: 141.471 ms
....

Điều gì xảy ra nếu chúng ta thêm một index vào column `author` của table posts?

[source,text]
....
forumdb=> CREATE INDEX idx_posts_author ON posts( author );
CREATE INDEX
forumdb=> EXPLAIN ANALYZE
     SELECT p.title, u.username
     FROM posts p
     JOIN users u ON u.pk = p.author
     WHERE u.username = 'fluca1978'
    AND   daterange( CURRENT_DATE - 20, CURRENT_DATE ) @> p.created_
on::date;



   QUERY PLAN
--------------------------------------------------------------------------
---------------------------------------------------------
Nested Loop (cost=8.45..1602.29 rows=2 width=26) (actual
time=0.145..0.926 rows=20 loops=1)
  -> Index Scan using users_username_key on users u (cost=0.28..8.29
rows=1 width=19) (actual time=0.011..0.012 rows=1 loops=1)
            Index Cond: (username = 'fluca1978'::text)
  -> Bitmap Heap Scan on posts p (cost=8.17..1593.98 rows=2 width=15)
(actual time=0.129..0.904 rows=20 loops=1)
            Recheck Cond: (author = u.pk)
            Filter: (daterange((CURRENT_DATE - 20), CURRENT_DATE) @> (created_
on)::date)
            Rows Removed by Filter: 480
            Heap Blocks: exact=500
         -> Bitmap Index Scan on idx_posts_author (cost=0.00..8.17
rows=500 width=0) (actual time=0.059..0.059 rows=500 loops=1)
                   Index Cond: (author = u.pk)
Planning Time: 0.401 ms
Execution Time: 0.954 ms
(12 rows)
....

Trước hết, query hiện chạy tuần tự vì không có Gather node nào: điều này có nghĩa là bây giờ PostgreSQL có thể giảm result set cần kiểm tra ngay từ trước. Ngoài ra, execution time hiện nhỏ hơn một millisecond.

Như bạn có thể thấy, node đầu tiên được thực thi là một Index Scan node trên table posts, hiện được dùng trước, không giống plan song song trước đó, sau đó result set sau khi được giảm sẽ được join bằng một Nested Loop với table authors. Việc sử dụng Nested Loop xác nhận rằng PostgreSQL đã có thể giảm result set, lấy trước chỉ những tuple cần thiết từ table posts.

Cũng cần lưu ý rằng không còn lý do để giữ index trên column `created_on`, vì query plan trước đó không còn sử dụng nó nữa.

Cần bao nhiêu space cho các index bây giờ? Một lần nữa, việc kiểm tra khá đơn giản:

[source,text]
....
forumdb=> SELECT pg_size_pretty( pg_relation_size( 'posts') ) AS table_
size,
         pg_size_pretty( pg_relation_size( 'idx_posts_date' ) ) AS idx_date_
size,
        pg_size_pretty( pg_relation_size( 'idx_posts_author' ) ) AS idx_
author_size;


      table_size | idx_date_size | idx_author_size
   ------------+---------------+-----------------
   59 MB         | 3600 kB            | 3600 kB


   (1 row)
....

Cả hai index yêu cầu cùng một lượng space, nhưng như đã nói, chúng ta có thể drop date-based index vì nó không còn cần thiết. Thực tế, ngay cả với một date clause cụ thể, index cũng không còn được sử dụng:

[source,text]
....
forumdb=> EXPLAIN ANALYZE
      SELECT p.title, u.username
      FROM posts p
      JOIN users u ON u.pk = p.author
      WHERE u.username = 'fluca1978'
        AND     p.created_on::date = CURRENT_DATE -2;


                                                                            QUERY PLAN
--------------------------------------------------------------------------
---------------------------------------------------------
Nested Loop (cost=8.45..1599.79 rows=2 width=26) (actual
time=0.132..0.737 rows=1 loops=1)
  -> Index Scan using users_username_key on users u (cost=0.28..8.29
rows=1 width=19) (actual time=0.009..0.010 rows=1 loops=1)
           Index Cond: (username = 'fluca1978'::text)
  -> Bitmap Heap Scan on posts p (cost=8.17..1591.48 rows=2 width=15)
(actual time=0.119..0.723 rows=1 loops=1)
           Recheck Cond: (author = u.pk)
           Filter: ((created_on)::date = (CURRENT_DATE - 2))
           Rows Removed by Filter: 499
           Heap Blocks: exact=500
        -> Bitmap Index Scan on idx_posts_author (cost=0.00..8.17
rows=500 width=0) (actual time=0.053..0.053 rows=500 loops=1)
                  Index Cond: (author = u.pk)
Planning Time: 0.237 ms
Execution Time: 0.763 ms
....

Việc xác định các index không được sử dụng rất quan trọng vì nó cho phép chúng ta thu hồi disk space và đơn giản hóa việc management cũng như data insertion: hãy nhớ rằng mỗi khi table thay đổi, index phải được update, và việc này cũng yêu cầu thêm resource như time và disk space.

Vì vậy, như bạn có thể thấy, việc phân tích các query được các application của bạn thực thi thường xuyên nhất và xác định liệu một index có thể giúp cải thiện execution speed hay không thực sự quan trọng; nhưng cũng hãy nhớ rằng index có extra cost cả về space lẫn maintenance, vì vậy đừng lạm dụng việc sử dụng index.

Nhưng làm thế nào bạn có thể xác định các index không được sử dụng mà không cần biết các query đang diễn ra?

May mắn là PostgreSQL cung cấp thông tin chi tiết về việc sử dụng mọi index: view đặc biệt `pg_stat_user_indexes` cung cấp thông tin về số lần một index đã được sử dụng và cách nó được sử dụng. Ví dụ, để lấy thông tin về các index trên table posts, bạn có thể thực thi một query như sau:

[source,text]
....
forumdb=> SELECT indexrelname, idx_scan, idx_tup_read, idx_tup_fetch FROM
pg_stat_user_indexes WHERE relname = 'posts';
....
[source,text]
....
   indexrelname      | idx_scan | idx_tup_read | idx_tup_fetch
------------------+----------+--------------+---------------
posts_pkey           |          5 |                5 |                 5
idx_posts_date       |          1 |          500000 |            500000
idx_posts_author |             51 |            8534 |                  0
....

Điều này cho chúng ta biết rằng `idx_posts_date` đã được sử dụng 1 lần và cung cấp 500000 tuple, trong khi `idx_posts_author` đã được sử dụng 51 lần và cũng cung cấp ít tuple hơn nhiều (chỉ 8534), nghĩa là nó rất hiệu quả.

Sau khi quan sát xu hướng này theo thời gian, nếu `idx_posts_date` hiếm khi được sử dụng, bạn có thể an toàn drop nó.

Ví dụ cuối cùng, hãy xem xét một query được viết kém và vấn đề mà nó kéo theo: giả sử chúng ta muốn lấy tất cả author đã tạo post vào một ngày nhất định và trong cùng ngày đó nhận được một số lượng like cụ thể. Một query tệ có thể là query sau:

[source,sql]
....
   SELECT u.username
   FROM users u JOIN posts p ON p.author = u.pk WHERE p.created_on = CURRENT_
   DATE - 5
   AND u.pk IN ( SELECT pp.author FROM posts pp WHERE likes = 5 and
   p.created_on = created_on );
....

Rõ ràng không cần subquery trên table `posts`, nhưng đây là một ví dụ cụ thể cho thấy vì sao việc hiểu cách viết query tốt lại quan trọng.

Thoạt nhìn, query trước đó chạy đủ nhanh; nó mất 190 millisecond để thực thi, như được minh họa bởi `EXPLAIN ANALYZE`:

[source,text]
....
   forumdb=> EXPLAIN ANALYZE SELECT u.username
   FROM users u JOIN posts p ON p.author = u.pk WHERE p.created_on = CURRENT_
   DATE - 5
   AND u.pk IN ( SELECT pp.author FROM posts pp WHERE likes = 5 and
   p.created_on = created_on );
                                                                               QUERY PLAN
   --------------------------------------------------------------------------
   -------------------------------------------------------------
   Hash Join (cost=33.93..92.04 rows=498 width=15) (actual
   time=1.351..189.308 rows=100 loops=1)
   Hash Cond: (p.author = u.pk)
      Join Filter: (SubPlan 1)
      Rows Removed by Join Filter: 900
     -> Index Scan using idx_posts_date on posts p (cost=0.43..55.92
   rows=996 width=12) (actual time=0.029..0.254 rows=1000 loops=1)
              Index Cond: (created_on = (CURRENT_DATE - 5))
     -> Hash (cost=21.00..21.00 rows=1000 width=19) (actual
   time=0.345..0.345 rows=1000 loops=1)
              Buckets: 1024    Batches: 1    Memory Usage: 59kB
           -> Seq Scan on users u (cost=0.00..21.00 rows=1000 width=19)
   (actual time=0.006..0.151 rows=1000 loops=1)
      SubPlan 1
       -> Index Scan using idx_posts_date on posts pp (cost=0.42..58.49
   rows=99 width=4) (actual time=0.005..0.176 rows=95 loops=1000)
                Index Cond: (created_on = p.created_on)
                Filter: (likes = 5)
                Rows Removed by Filter: 855
   Planning Time: 0.393 ms
   Execution Time: 189.439 ms
....

Tuy nhiên, khi xem output, bạn có thể thấy node *Index Scan* sử dụng `idx_posts_date` trên `pp posts` có counter `loops` được đặt là 1000: điều này nghĩa là node này được thực thi 1.000 lần trong query. Node này là subquery, và đó là cách SQL đạt được kết quả: mỗi khi tìm thấy một tuple từ outer query, inner query phải được chạy và các kết quả phải được join. Một lựa chọn có thể là rewrite query để PostgreSQL không phải looping, chẳng hạn dùng subquery với expression `GROUP BY`:

[source,text]
....
   forumdb=> EXPLAIN ANALYZE
   WITH likes AS (
             SELECT pp.author, pp.created_on FROM posts pp
             WHERE likes = 5
             GROUP BY pp.author, pp.created_on
                  )
   SELECT u.username
   FROM users u JOIN posts p ON p.author = u.pk
   JOIN likes l ON l.created_on = p.created_on AND l.author = u.pk
   WHERE p.created_on = CURRENT_DATE - 5;
....

[source,text]
....
  --------------------------------------------------------------------------
  -------------------------------------------------------------------------
  ---------------
  Hash Join (cost=89.47..149.68 rows=98 width=15) (actual time=0.581..0.896
  rows=100 loops=1)
      Hash Cond: (p.author = u.pk)
    -> Index Scan using idx_posts_date on posts p (cost=0.43..55.92
  rows=996 width=12) (actual time=0.012..0.167 rows=1000 loops=1)
            Index Cond: (created_on = (CURRENT_DATE - 5))
    -> Hash (cost=87.82..87.82 rows=98 width=31) (actual time=0.561..0.562
  rows=100 loops=1)
            Buckets: 1024   Batches: 1   Memory Usage: 15kB
          -> Hash Join (cost=62.09..87.82 rows=98 width=31) (actual
  time=0.305..0.540 rows=100 loops=1)
                  Hash Cond: (u.pk = l.author)
                -> Seq Scan on users u (cost=0.00..21.00 rows=1000
  width=19) (actual time=0.005..0.094 rows=1000 loops=1)
                -> Hash (cost=60.86..60.86 rows=98 width=12) (actual
  time=0.294..0.294 rows=100 loops=1)
                        Buckets: 1024   Batches: 1   Memory Usage: 13kB
                      -> Subquery Scan on l (cost=58.90..60.86 rows=98
  width=12) (actual time=0.243..0.276 rows=100 loops=1)
                            -> HashAggregate (cost=58.90..59.88 rows=98
  width=12) (actual time=0.242..0.260 rows=100 loops=1)
                                     Group Key: pp.author, pp.created_on
                                     Batches: 1   Memory Usage: 24kB
                                    -> Index Scan using idx_posts_date on
  posts pp    (cost=0.43..58.41 rows=98 width=12) (actual time=0.009..0.208
  rows=100 loops=1)
                                            Index Cond: (created_on = (CURRENT_
  DATE - 5))
                                            Filter: (likes = 5)
                                            Rows Removed by Filter: 900
  Planning Time: 0.455 ms
  Execution Time: 0.954 ms
....

Output này báo thời gian chưa đến một millisecond, và đáng chú ý nhất là không khiến PostgreSQL loop qua cùng subquery nhiều lần.

Rõ ràng, viết query hoàn toàn không có subquery là cách hiệu quả nhất để cho PostgreSQL hiểu nó phải làm gì:

[source,text]
....
   forumdb=> EXPLAIN ANALYZE
   SELECT u.username
   FROM users u JOIN posts p ON p.author = u.pk
   WHERE p.created_on = CURRENT_DATE - 5
   AND p.likes = 5;
                                                                           QUERY PLAN
   --------------------------------------------------------------------------
   --------------------------------------------------------
   Hash Join (cost=33.93..92.17 rows=98 width=15) (actual time=0.413..0.638
   rows=100 loops=1)
      Hash Cond: (p.author = u.pk)
     -> Index Scan using idx_posts_date on posts p (cost=0.43..58.41
   rows=98 width=4) (actual time=0.015..0.212 rows=100 loops=1)
             Index Cond: (created_on = (CURRENT_DATE - 5))
             Filter: (likes = 5)
             Rows Removed by Filter: 900
     -> Hash (cost=21.00..21.00 rows=1000 width=19) (actual
   time=0.393..0.394 rows=1000 loops=1)
           Buckets: 1024     Batches: 1     Memory Usage: 59kB
         -> Seq Scan on users u (cost=0.00..21.00 rows=1000 width=19)
   (actual time=0.007..0.173 rows=1000 loops=1)
   Planning Time: 0.263 ms
   Execution Time: 0.666 ms
....

Ví dụ đơn giản trước đó cho thấy vì sao việc hiểu output của `EXPLAIN` và `EXPLAIN ANALYZE` lại quan trọng, để hiểu rõ hơn liệu query có đang thiếu index hay cần rewrite để PostgreSQL thực hiện công việc của nó tốt nhất hay không.
