= Khám phá PGXN client

PGXN client là một application bên ngoài, được viết bằng Python, hoạt động như một command-line interface cho PGXN. Application này có tên `pgxnclient`, hoạt động thông qua các command, là những action như install, download, uninstall, v.v., cho phép database administrator tương tác với PGXN và các extension.

[quote]
____
Ở một mức độ nào đó, `pgxnclient` hoạt động giống command `cpan` (hoặc `cpanm`) dành cho Perl, `zef` dành cho Raku, `pip` dành cho Python, v.v.

Vì là một application bên ngoài, `pgxnclient` không được phân phối cùng PostgreSQL, do đó bạn cần cài đặt nó trên machine trước khi có thể sử dụng. Việc cài đặt `pgxnclient` không bắt buộc để sử dụng các PostgreSQL extension, nhưng có thể giúp công việc của bạn dễ dàng hơn nhiều.

____
Trong các subsection tiếp theo, bạn sẽ thấy cách cài đặt `pgxnclient` trên các operating system Unix và Unix-like chính, nhưng trước hết, điều quan trọng là bạn cần biết rằng sau khi được cài đặt, bạn sẽ tìm thấy hai executable trên system: `pgxn` và `pgxnclient`. Bạn có thể xem chúng như alias của nhau, dù điều này không hoàn toàn đúng (một cái bọc cái kia); tuy nhiên, bạn có thể dùng bất kỳ executable nào mình muốn và nhận được cùng một kết quả. Trong chapter này, chúng ta sẽ dùng `pgxn` làm executable chính.

[quote]
____
Trong các Docker image của repository cuốn sách, program `pgxnclient` đã được cài đặt sẵn, nên bạn không cần cài đặt nó.

Hướng dẫn chi tiết về cách cài đặt `pgxnclient` nằm ngoài phạm vi của cuốn sách này; vì vậy nếu bạn không thể làm cho application hoạt động đúng, hãy kiểm tra lại documentation của project và hướng dẫn cài đặt.

____
== Cài đặt pgxnclient trên Debian GNU/Linux và các derivative

`pgxnclient` được đóng gói cho Debian GNU/Linux và các derivative, nghĩa là bạn chỉ cần yêu cầu `apt` cài đặt nó:

[source,text]
....
$ sudo apt install pgxnclient
....

Sau khi program được cài đặt, bạn có thể test nó bằng option `--version`, option này sẽ in ra version number mà bạn đã cài đặt:

[source,text]
....
$ pgxn --version
pgxnclient 1.3.2
....

== Cài đặt pgxnclient trên Fedora Linux và các distribution dựa trên Red Hat

`pgxnclient` cũng được đóng gói cho Fedora, vì vậy bạn có thể cài đặt nó bằng package manager của operating system:

[source,text]
....
$ sudo dnf install -y pgxnclient
....

Sau khi process hoàn tất, bạn có thể query application để xác minh rằng nó thực sự hoạt động:

[source,text]
....
$ pgxn --version
pgxnclient 1.3.2
....

== Cài đặt pgxnclient trên FreeBSD

`pgxnclient` được đóng gói cho FreeBSD, vì vậy bạn có thể cài đặt nó thông qua tool `pkg` hoặc software port. Cách nhanh nhất là dùng `pkg`; tất cả những gì bạn cần làm là yêu cầu cài đặt program:

[source,text]
....
$ sudo pkg install --yes pgxnclient
....

== Cài đặt pgxnclient từ source

Bạn luôn có thể cài đặt `pgxnclient` từ source, dù cách này chỉ được đề xuất khi bạn đang dùng một operating system không cung cấp version được đóng gói, hoặc version hiện tại đã quá cũ so với nhu cầu của bạn. Bạn có thể download version nén của release mới nhất từ repository GitHub chính thức của project, chẳng hạn:

[source,text]
....
$ wget https://github.com/pgxn/pgxnclient/archive/refs/tags/v1.3.2.zip
....

Sau khi có compressed archive, bạn cần decompress nó và đi vào directory sẽ được tạo ra, directory này được đặt tên theo version của PXGN mà bạn đã download, trong trường hợp của chúng ta là `pgxnclient-3.1.2`. Khi đã ở trong directory, việc thực thi Python script `setup.py` sẽ cho phép bạn cài đặt application:

[source,text]
....
$ unzip v1.3.2.zip
$ cd pgxnclient-1.3.2
$ sudo python setup.py install
...
Finished processing dependencies for pgxnclient==1.3.2
....

Sau khi hoàn tất việc cài đặt, bạn có thể query application để xác minh rằng nó đang hoạt động:

[source,text]
....
$ pgxn --version
pgxnclient 1.3.2
....

== Command-line interface của pgxnclient

PGXN client application cung cấp một command-line interface tương tự các application dựa trên command khác, chẳng hạn như `cpanm` và `git`. Bạn có thể lấy danh sách các command chính bằng cách yêu cầu trợ giúp:

[source,text]
....
$ pgxn help
usage: pgxn [--version] [--help] COMMAND ...


Interact with the PostgreSQL Extension Network (PGXN).


optional arguments:
   --version     print the version number and exit
   --help        show this help message and exit


available commands:
   COMMAND       the command to execute. The complete list is available using
                 'pgxn help --all'. Builtin commands are:
      check      run a distribution's test
      download
                 download a distribution from the network
      help       display help and other program information
      info       print information about a distribution
      install    download, build and install a distribution
      load       load a distribution's extensions into a database
      mirror      return information about the available mirrors
      search      search in the available extensions
      uninstall
                 remove a distribution from the system
      unload      unload a distribution's extensions from a database
....

Thông thường, bạn sẽ dùng tập con command sau:

* `search` để search distribution bằng keyword
* `info` để xem xét kỹ hơn một extension
* `download` để download (nhưng không install) một extension
* `install` để download và install một extension vào cluster
* `load` để thực thi `CREATE EXTENSION` trên một database cụ thể
* `unload` để thực thi `DROP EXTENSION` trên một database cụ thể
* `uninstall` để xóa một extension khỏi cluster

Tập command nhỏ nhất mà có lẽ bạn sẽ dùng là `search`, `install` và `uninstall`.

Với mỗi command, bạn có thể nhận được help chi tiết hơn nếu chỉ định command đó làm argument cho command `help`. Ví dụ, để biết thêm thông tin về command `search`, bạn có thể làm như sau:

[source,text]
....
$ pgxn help search
usage: pgxn search [--help] [--mirror URL] [--verbose] [--yes]
                       [--docs | --dist | --ext]
                       TERM [TERM ...]


search in the available extensions


positional arguments:
    TERM            a string to search


optional arguments:
    --help          show this help message and exit
    --docs          search in documentation [default]
    --dist          search in distributions
    --ext           search in extensions
....

[source,text]
....
global options:
  --mirror URL    the mirror to interact with [default: https://api.pgxn.
org/]
  --verbose       print more information
  --yes           assume affirmative answer to all questions
....

Trong các section tiếp theo, bạn sẽ thấy cách sử dụng PXGN hiệu quả để cài đặt một extension.
