= Migrate từ MySQL/MariaDB sang PostgreSQL bằng pgloader

Trong section này, chúng ta sẽ xem cách migrate một database từ thế giới MySQL/MariaDB sang thế giới PostgreSQL theo một cách rất đơn giản. Tool chúng ta sẽ sử dụng có tên là pgloader. Có thể tìm thấy tài liệu tham khảo để biết thêm thông tin về section này tại https://pgloader.io.

Có hai Docker container dành cho section này, một container chứa MariaDB server và một container chứa PostgreSQL server. MariaDB server có tên mariadb-source chứa một bản sao của database forumdb được sử dụng trong Chapter 4; PostgreSQL server có tên pg-destination chứa một database forumdb trống. Mục tiêu của chúng ta là migrate toàn bộ nội dung của database forumdb từ mariadb-source server sang postgresql-destination server bằng pgloader tool.

Hãy mở hai Bash terminal và thực thi lệnh sau trong terminal thứ nhất:

[source,text]
....
chapter19$ bash run-pg-docker-mariadb.sh
....

Sau khi container đã khởi động, hãy thực thi statement dưới đây bằng LearnPostgreSQL làm password:

[source,text]
....
root@mariadb-source:~# mysql -D forumdb -p
[...]
Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.


Type 'help;' or '\h' for help. Type '\c' to clear the current input
statement.


MariaDB [forumdb]>
....

Bây giờ chúng ta đang ở bên trong database forumdb và có thể thực hiện query trên đó:

[source,text]
....
MariaDB [forumdb]> show tables;
+-------------------+
| Tables_in_forumdb |
+-------------------+
| categories             |
| j_posts_tags           |
| posts                  |
| tags                   |
| users                  |
+-------------------+
5 rows in set (0.000 sec)
....

[source,text]
....
MariaDB [forumdb]> select * from categories;
+----+-----------------------+---------------------------------+
| pk | title                        | description                            |
+----+-----------------------+---------------------------------+
|   1 | Database                    | Database related discussions           |
|   2 | Unix                        | Unix and Linux discussions             |
|   3 | Programming Languages | All about programming languages |
+----+-----------------------+---------------------------------+
3 rows in set (0.002 sec)
....

[source,text]
....
MariaDB [forumdb]> select * from users;
+----+-----------+----------------+---------------------+
| pk | username      | gecos             | email                    |
+----+-----------+----------------+---------------------+
|   1 | fluca1978 | Luca Ferrari         | fluca1978@gmail.com |
|   2 | sscotty71 | Enrico Pirozzi | sscptty71@gmail.com |
+----+-----------+----------------+---------------------+
2 rows in set (0.001 sec)
....

Như có thể thấy, database này giống database chúng ta đã sử dụng trong Chapter 4, Basic Statements.

Bây giờ hãy chuyển sang Bash terminal thứ hai và thực thi:

[source,text]
....
chapter19$ bash run-pg-docker-postgresql.sh
....

Sau khi container khởi động, hãy thực thi:

[source,text]
....
postgres@pg-destination:~$ psql forumdb
....

Như thấy dưới đây, PostgreSQL database của chúng ta đang trống:

[source,text]
....
postgres@pg-destination:~$ psql forumdb
forumdb=# \d
Did not find any relations.
....

Bây giờ hãy thoát khỏi psql client và thực thi pgloader command:

[source,text]
....
forumdb=# \q
ppostgres@pg-destination:~$ pgloader mysql://root:LearnPostgreSQL@mariadb-
source/forumdb pgsql://postgres@127.0.0.1/forumdb


              table name       errors         rows        bytes        total time
-----------------------      ---------    ---------    ---------    --------------
          fetch meta data             0           22                          0.104s
           Create Schemas             0            0                          0.000s
         Create SQL Types             0            0                          0.004s
            Create tables             0           10                          0.056s
           Set Table OIDs             0            5                          0.020s
-----------------------      ---------    ---------    ---------    --------------
       forumdb.categories             0            3      0.1 kB              0.020s
            forumdb.users             0            2      0.1 kB              0.016s
     forumdb.j_posts_tags             0            0                          0.012s
             forumdb.tags             0            0                          0.016s
            forumdb.posts             0            0                          0.012s
-----------------------      ---------    ---------    ---------    --------------
COPY Threads Completion               0            4                          0.024s
   Index Build Completion             0           11                          0.048s
           Create Indexes             0           11                          0.092s
          Reset Sequences             0            4                          0.012s
             Primary Keys             0            4                          0.004s
      Create Foreign Keys             0            6                          0.004s
          Create Triggers             0            0                          0.000s
          Set Search Path             0            1                          0.000s
         Install Comments             0            0                          0.000s
-----------------------      ---------    ---------    ---------    --------------
        Total import time             ✓            5      0.2 kB              0.184s
....

Bằng command đơn giản trên, chúng ta đã migrate MariaDB database forumdb vào PostgreSQL database forumdb. Bây giờ hãy kiểm tra xem mọi thứ đã được migrate chưa; hãy kết nối lại với forumdb trên PostgreSQL server:

[source,text]
....
postgres@pg-destination:~$ psql forumdb
....

[source,text]
....
forumdb=# \dn
          List of schemas
   Name     |       Owner
---------+-------------------
 forumdb | postgres
 public     | pg_database_owner
(2 rows)


forumdb=# \dt forumdb.*
                    List of relations
     Schema     |     Name       | Type    |   Owner
    ---------+--------------+-------+----------
     forumdb | categories        | table | postgres
     forumdb | j_posts_tags | table | postgres
     forumdb | posts             | table | postgres
     forumdb | tags              | table | postgres
     forumdb | users             | table | postgres
(5 rows)
....

Như có thể thấy ở trên, MariaDB database có tên forumdb đã được migrate sang PostgreSQL database có tên forumdb. pgloader tự động tạo một schema có tên forumdb, nơi chúng ta có thể tìm thấy tất cả table và data đến từ MariaDB database forumdb ban đầu; bây giờ điều duy nhất chúng ta cần là tạo một user có tên forumdb, user này có đủ permission để sử dụng toàn bộ data vừa import:

[source,text]
....
forumdb=# create role forumdb with password 'LearnPostgreSQL' login;
CREATE ROLE


forumdb=# grant usage on schema forumdb to forumdb ;
GRANT
forumdb=# grant all on all tables in schema forumdb to forumdb ;
GRANT


forumdb=# \q
....
Giờ đây, chúng ta có thể truy cập database `forumdb` của postgresql bằng user có tên `forumdb`:

[source,text]
....
postgres@pg-destination:~$ psql -U forumdb forumdb

forumdb=> select * from categories;
    pk |          title             |             description
----+-----------------------+---------------------------------
     1 | Database                   | Database related discussions
     2 | Unix                       | Unix and Linux discussions
     3 | Programming Languages | All about programming languages
(3 rows)

forumdb=> select * from users;
    pk | username    |      gecos         |          email
----+-----------+----------------+---------------------
     1 | fluca1978 | Luca Ferrari         | fluca1978@gmail.com
     2 | sscotty71 | Enrico Pirozzi | sscptty71@gmail.com
(2 rows)
....
