= Xử lý các vấn đề connection thường gặp

Khi làm việc với database connection, bạn có thể gặp một số vấn đề phổ biến. Phần này giải thích các vấn đề đó để giúp bạn kết nối với cluster dễ dàng hơn.

Lưu ý rằng các giải pháp dưới đây chỉ dành cho testing, không dùng trong production. Toàn bộ thiết lập bảo mật sẽ được giải thích ở các chương sau, nên mục tiêu của tiểu mục này chỉ là giúp bạn sử dụng được môi trường test.

== Database “foo” không tồn tại

Điều này có nghĩa là bạn đã viết sai tên database trong connection string hoặc đang cố kết nối mà không chỉ định tên database.

Chẳng hạn, connection dưới đây sẽ thất bại nếu được thực hiện bởi operating system user có tên `luca`, vì theo mặc định, nó giả định rằng user `luca` đang cố kết nối tới database cùng tên (tức là `luca`) do chưa có tên database nào được chỉ định rõ ràng:

[source,console,role="transcript"]
....
     $ psql
     psql: error: could not connect to server: FATAL:            database "luca" does not
     exist
....

.Command
[source,bash]
....
psql
....

.Output
[source,output]
....
     psql: error: could not connect to server: FATAL:            database "luca" does not
     exist
....


Giải pháp là cung cấp tên của một database đang tồn tại thông qua option `-d`, hoặc tạo database có cùng tên với user.

== Connection refused

Điều này thường có nghĩa là kết nối mạng gặp vấn đề: hoặc host mà bạn đang cố kết nối tới không thể truy cập được, hoặc cluster không listen trên network.

Ví dụ, hãy hình dung PostgreSQL đang chạy trên một máy có tên `venkman`, còn bạn đang cố kết nối từ một host khác trong cùng network:

[source,console,role="transcript"]
....
     $ psql -h venkman -U luca template1
     psql: error: could not connect to server: could not connect to server:
     Connection refused
             Is the server running on host "venkman" (192.168.222.123) and
     accepting
              TCP/IP connections on port 5432?
....

.Command
[source,bash]
....
psql -h venkman -U luca template1
....

.Output
[source,output]
....
     psql: error: could not connect to server: could not connect to server:
     Connection refused
             Is the server running on host "venkman" (192.168.222.123) and
     accepting
              TCP/IP connections on port 5432?
....


Trong trường hợp này, database cluster đang chạy trên host từ xa nhưng không chấp nhận connection từ bên ngoài. Thông thường, bạn phải chỉnh sửa configuration của server hoặc kết nối tới máy từ xa (chẳng hạn qua SSH), rồi mở một connection cục bộ từ máy đó.

Để nhanh chóng giải quyết vấn đề, bạn phải chỉnh sửa file `postgresql.conf` (thường nằm trong thư mục `PGDATA`) và bảo đảm option `listen_address` được đặt thành dấu hoa thị (hoặc tên interface mạng bên ngoài của bạn), để server listen trên mọi network address hiện có:

[source,text]
....
   listen_addresses = '*'
....

Sau khi khởi động lại service bằng command `restart` của `pg_ctl`, client sẽ có thể kết nối. Lưu ý rằng việc cho phép server listen trên mọi network address hiện có có thể không phải là giải pháp tối ưu và có thể khiến server gặp rủi ro trong môi trường production. Ở các phần sau của cuốn sách, bạn sẽ học cách cấu hình cụ thể các thuộc tính của connection cho server.

== No `pg_hba.conf` entry

Lỗi này có nghĩa là server đang hoạt động và có thể chấp nhận yêu cầu của bạn, nhưng cơ chế kiểm soát Host-Based Access (HBA) tích hợp sẵn trong PostgreSQL không cho phép bạn truy cập.

Lỗi này không bao giờ nên xảy ra trong Docker container dùng cho chương này, vì configuration của container đã cho phép các connection dạng trusted. Tuy nhiên, các bản cài đặt PostgreSQL khác có thể nghiêm ngặt hơn; vì vậy, hiểu loại thông báo lỗi này có thể giúp bạn nhanh chóng xác định vấn đề nằm ở đâu trong configuration.

Ví dụ, connection dưới đây bị từ chối:

[source,console,role="transcript"]
....
   $   psql -h localhost -U luca template1
   psql: error: could not connect to server: FATAL: no pg_hba.conf entry for
   host "127.0.0.1", user "luca", database "template1", SSL off
....

.Command
[source,bash]
....
  psql -h localhost -U luca template1
....

.Output
[source,output]
....
   psql: error: could not connect to server: FATAL: no pg_hba.conf entry for
   host "127.0.0.1", user "luca", database "template1", SSL off
....


Lý do là trong file `pg_hba.conf` không có rule nào cho phép user `luca` kết nối từ localhost. Vì vậy, chẳng hạn, thêm một dòng như sau vào file `pg_hba.conf` có thể khắc phục vấn đề:

[source,text]
....
   host all luca 127.0.0.1/32 trust
....

Bạn cần reload configuration để áp dụng thay đổi. Định dạng của từng dòng trong file `pg_hba.conf` sẽ được trình bày ở phần sau, nhưng hiện tại, hãy giả định rằng dòng trên yêu cầu cluster chấp nhận mọi connection từ localhost cho user `luca`.
