= Tìm hiểu CTE

Trong section này, chúng ta sẽ nói về CTE. Section này được chia thành ba phần. Thứ nhất, chúng ta sẽ nói về khái niệm CTE; thứ hai, chúng ta sẽ thảo luận cách CTE được implement bắt đầu từ PostgreSQL 12; và cuối cùng, chúng ta sẽ khám phá một số ví dụ về cách sử dụng CTE.

== Khái niệm CTE

CTE, hay common table expression, là một temporary result lấy từ một SQL statement. Statement này có thể chứa instruction `SELECT`, `INSERT`, `UPDATE` hoặc `DELETE`. Lifetime của CTE bằng với lifetime của query. Đây là một ví dụ về định nghĩa CTE:

[source,text]
....
WITH cte_name (column_list) AS (
  CTE_query_definition
)
statement;
....

Ví dụ, nếu muốn tạo một temporary dataset với tất cả post do author `enrico_pirozzi` viết, chúng ta phải viết như sau:

[source,text]
....
forumdb=> with posts_author_1 as
  (select p.* from posts p
  inner join users u on p.author=u.pk
  where username='enrico_pirozzi')
select pk,title from posts_author_1;
  pk |             title
 ----+------------------------------
   3 | A view of   Data types in C++
(1 row)
....

Chúng ta cũng có thể viết cùng điều này bằng cách sử dụng một inline view:

[source,text]
....
forumdb=> select pk,title from
(select p.* from posts p inner join users u on p.author=u.pk where
u.username='enrico_pirozzi') posts_author_1;
 pk |             title
----+------------------------------
  3 | A view of   Data types in C++
(1 row)
....

Như có thể thấy, result giống nhau. Điểm khác biệt là trong ví dụ đầu tiên, CTE tạo ra một temporary resultset, còn query thứ hai, inline view, thì không.
