= Yêu cầu kỹ thuật

Đến thời điểm này trong cuốn sách, chúng ta đã học cách cài đặt PostgreSQL và cấu hình user. Tuy nhiên, nếu chưa đọc các chương trước, bạn vẫn có thể dễ dàng làm theo các bước tiếp theo bằng Docker image được mô tả dưới đây.

== Sử dụng Docker image

Nếu muốn làm theo các bước tiếp theo mà không cài đặt và cấu hình PostgreSQL, bạn có thể dễ dàng thực hiện các bước đó bằng Docker image trong repository trên GitHub (chi tiết về cách thiết lập được trình bày trong chương 1, *Giới thiệu về PostgreSQL*). Vì vậy, hãy khởi động standalone container như mô tả trong chương 1, *Giới thiệu về PostgreSQL*, rồi thực thi lệnh sau:

[source,console,role="transcript"]
....
$ sudo docker exec -it standalone_learn_postgresql_1 /bin/bash
....

.Command
[source,bash]
....
sudo docker exec -it standalone_learn_postgresql_1 /bin/bash
....


Sau khi chạy lệnh này, chúng ta sẽ ở trong container `standalone_learn_postgresql_1` và có một root shell:

[source,text]
....
root@learn_postgresql:/#
....

== Kết nối đến database

Ngay cả khi dùng PostgreSQL được cài đặt trực tiếp thay vì Docker container như mô tả trong chương 1, *Giới thiệu về PostgreSQL*, chúng ta vẫn đạt được kết quả tương tự bằng cách thực thi cùng statement với tư cách user postgres:

[source,console,role="transcript"]
....
root@learn_postgresql:/# su - postgres
postgres@learn_postgresql:~$ psql
postgres=#
....

.Command
[source,bash]
....
root@learn_postgresql:/# su - postgres
psql
....


Bây giờ hãy bật expanded mode bằng lệnh `\x`:

[source,console,role="transcript"]
....
postgres=# \x
Expanded display is on.
....

.SQL
[source,sql]
....
\x
....

.Output
[source,output]
....
Expanded display is on.
....


Sau đó, hãy liệt kê tất cả database hiện có trong cluster:

[source,console,role="transcript"]
....
postgres=# \l
List of databases
-[ RECORD 1 ]-----+--------------
Name                 | forumdb
Owner                  | forum
Encoding               | UTF8
Collate                | en_US.utf8
Ctype                  | en_US.utf8
ICU Locale             |
Locale Provider        | libc
Access privileges |
....

.SQL
[source,sql]
....
\l
....

.Output
[source,output]
....
List of databases
-[ RECORD 1 ]-----+--------------
Name                 | forumdb
Owner                  | forum
Encoding               | UTF8
Collate                | en_US.utf8
Ctype                  | en_US.utf8
ICU Locale             |
Locale Provider        | libc
Access privileges |
....


Để tiết kiệm không gian, chúng ta chỉ hiển thị database `forumdb` được import từ Docker script; tuy nhiên, như đã thấy trong chương 2, *Làm quen với cluster của bạn*, còn có các database `template0`, `template1` và `postgres`. Cuối cùng, hãy kết nối đến database `forumdb`:

[source,console,role="transcript"]
....
postgres=# \c forumdb
You are now connected to database "forumdb" as user "postgres".
....

.SQL
[source,sql]
....
\c forumdb
....

.Output
[source,output]
....
You are now connected to database "forumdb" as user "postgres".
....


Bây giờ chúng ta đã hoàn tất việc thiết lập môi trường phát triển và có thể chuyển sang tạo database trong môi trường đó.
