= Kiểm tra kiến thức

* Hãy xem xét hai query sau:

.. `select category,count(*) from posts group by category order by category;`
.. `select category, count(*) over (partition by category) from posts order by category;`

  Query nào trong hai query có số record lớn hơn?

  Query thứ hai có số record lớn hơn.

  Xem section Using basic statement window functions để biết thêm chi tiết.

* Hãy xem xét hai query sau:

.. `select category,count(*) from posts group by category order by category;`
.. `select distinct category, count(*) over (partition by category) from posts order by category;`

  Query nào trong hai query có số record lớn hơn?

  Hai query có cùng số record.

  Xem section Using basic statement window functions để biết thêm chi tiết.

* Query nào trong hai query sau đúng về semantic?

.. `select category,row_number() over w,title from posts WINDOW w as (partition by category order by title) order by category;`
.. `select category,row_number() over w,title from posts WINDOW w as (partition by category) order by category;`

  Query thứ nhất đúng về semantic vì function `row_number()` phụ thuộc vào `order by`.

  Xem section The row number function để biết thêm chi tiết.

* Có thể lấy value đầu tiên trong một partition không?

  Có, chúng ta có thể làm vậy bằng function `first_value()`. Xem section `FIRST_VALUE` để biết thêm chi tiết.

* Có thể tính tổng tăng dần từng row trong một table không?

  Có, chúng ta có thể làm vậy bằng clause `BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW`.

  Xem section Using advanced statement window functions để biết thêm chi tiết.
