= Tạo và quản lý database

Trong phần này, trước hết chúng ta sẽ tạo database đầu tiên, sau đó học cách xóa database và cuối cùng là cách tạo database mới từ một database hiện có. Chúng ta cũng sẽ xem xét vấn đề dưới góc nhìn của DBA, tìm hiểu điều gì xảy ra phía sau khi tạo database mới và một số function cơ bản giúp DBA hình dung kích thước thực của database.

Trước hết, hãy xem cách tạo database từ đầu và điều gì xảy ra phía sau khi database được tạo.

== Tạo database

Để tạo database có tên `databasename` từ đầu, bạn chỉ cần thực thi statement đơn giản sau:

[source,sql]
....
CREATE DATABASE databasename;
....

[quote]
____
SQL không phân biệt chữ hoa chữ thường, vì vậy có thể viết các lệnh bằng chữ hoa hoặc chữ thường.

____
Bây giờ hãy xem điều gì xảy ra phía sau khi tạo database mới. PostgreSQL thực hiện các bước sau:

. Tạo một bản sao vật lý của template database `template1`
. Đặt tên cho database vừa được sao chép

Database `template1` được tạo bởi tiến trình `initdb` trong quá trình khởi tạo PostgreSQL cluster.

== Quản lý database

Chúng ta vừa xem cách tạo database. Trong phần này, chúng ta sẽ tìm hiểu cách quản lý database: liệt kê tất cả database hiện có trong một cluster, tạo database từ một database hiện có, xóa database và xem điều gì xảy ra bên trong khi tạo hoặc xóa database.

== Giới thiệu schema

Như đã nêu trong Chương 1, *Giới thiệu về PostgreSQL*: “một database có thể được tổ chức thành các namespace gọi là schema. Schema là một tên gợi nhớ mà user có thể dùng để tổ chức các database object, chẳng hạn như table, thành một tập hợp có cấu trúc hơn. Schema không thể lồng nhau, nên chúng tạo thành một namespace phẳng.”

Nhắc lại nội dung trong Chương 1, *Giới thiệu về PostgreSQL*, chúng ta đã học rằng có hai loại user: user thông thường và superuser:

* superuser có thể thực hiện mọi thao tác trên database và schema.
* user thông thường chỉ có thể thực hiện các thao tác tùy theo privilege được cấp.

== PostgreSQL và public schema

Từ PostgreSQL 15, PostgreSQL đã thay đổi cách quản lý public schema. Trong phần này, chúng ta sẽ xem cơ chế này hoạt động như thế nào. Trước PostgreSQL 15, bất kỳ user nào cũng có thể thực hiện mọi thao tác DDL trên public schema. PostgreSQL 15 giới thiệu cơ chế loại bỏ privilege toàn cục khỏi public schema.

Từ PostgreSQL 15:

* User thông thường sẽ không thể thực thi DDL trên public schema.
* User thông thường sẽ không thể thực thi DML trên public schema, trừ khi được superuser cấp privilege.

Hãy dùng một ví dụ để giải thích rõ hơn tính năng mới này. Chúng ta sẽ làm việc như thể đang sử dụng phiên bản PostgreSQL <=14.x.

Chúng ta sẽ thực hiện các bước sau (một số hướng dẫn sẽ được giải thích ở phần sau của sách):

. Chúng ta sẽ tạo một user thông thường có tên `myuser`.
. Chúng ta sẽ kết nối đến database bằng user `myuser`.
. Với tư cách `myuser`, chúng ta sẽ thử tạo table mới tên `mytable`.

Dưới đây là kết quả thực thi các bước trên:

[source,console,role="transcript"]
....
forumdb=# create user myuser with password 'SuperSecret' login;
CREATE ROLE
forumdb=# set role to myuser;
SET
forumdb=> create table mytable(id integer);
ERROR:     permission denied for schema public
LINE 1: create table mytable(id integer);
....

.SQL
[source,sql]
....
CREATE user myuser WITH password 'SuperSecret' login;
SET role to myuser;
CREATE TABLE mytable(id integer);
....

.Output
[source,output]
....
CREATE ROLE
SET
ERROR:     permission denied for schema public
LINE 1: create table mytable(id integer);
....


Như có thể thấy, user thông thường không thể tạo table (DDL) trên public schema.

== Biến search_path

PostgreSQL có nhiều biến hệ thống. Một trong số đó là `search_path`. Biến `search_path` chứa thứ tự các schema mà PostgreSQL dùng để tìm table; giá trị mặc định của `search_path` là `$user,public`. Điều này có nghĩa là trước tiên PostgreSQL sẽ tìm table trong schema có tên trùng với user hiện tại, sau đó tìm trong public schema.

Ví dụ, nếu có một user tên `forum` và muốn hiển thị tất cả row trong table `cities`, trước tiên PostgreSQL sẽ tìm table `cities` trong schema `forum`. Nếu không tìm thấy table `cities` trong schema `forum`, PostgreSQL sẽ tìm table `cities` trong public schema.

== Cách đúng để bắt đầu làm việc

Hãy bắt đầu lại từ đầu và thực hiện các bước sau:

. Với tư cách superuser, hãy tạo database mới tên `myforumdb` và kết nối đến đó.
. Với tư cách superuser, hãy tạo user mới có tên `myforum`.
. Với tư cách superuser, hãy tạo schema mới có tên `myforum` và gán quyền sở hữu cho user `myforum`.
. Hãy kết nối đến database bằng user `myforum`:

[source,console,role="transcript"]
....
postgres=# create database myforumdb;
CREATE DATABASE
postgres=# \c myforumdb
You are now connected to database "myforumdb" as user "postgres".
myforumdb=# create user myforum with password 'SuperSecret' login;
CREATE ROLE
myforumdb=# create schema myforum authorization myforum;
CREATE SCHEMA
....

.SQL
[source,sql]
....
CREATE DATABASE myforumdb;
\c myforumdb CREATE user myforum WITH password 'SuperSecret' login;
CREATE schema myforum authorization myforum;
....

.Output
[source,output]
....
CREATE DATABASE
You are now connected to database "myforumdb" as user "postgres".
CREATE ROLE
CREATE SCHEMA
....


Bây giờ hãy thử kết nối đến database `myforumdb` bằng user `myforum`:

[source,console,role="transcript"]
....
postgres@learn_postgresql:/$ psql -U myforum myforumdb
myforumdb=>
....

.Command
[source,bash]
....
psql -U myforum myforumdb
....


Hãy thử tạo table mới tên `mytable` như trước:

[source,console,role="transcript"]
....
myforumdb=> create table mytable(id integer);
CREATE TABLE
....

.SQL
[source,sql]
....
CREATE TABLE mytable(id integer);
....

.Output
[source,output]
....
CREATE TABLE
....


Lần này thao tác đã thành công vì table `mytable` được tạo bên trong schema `myforum`, như đã giải thích ở trên.

[quote]
____
Database `forumdb` đi kèm container đã được cấu hình sẵn để user `forum` sử dụng schema `forum`.

____
== Liệt kê tất cả table

Bây giờ hãy kết nối đến database `forumdb` bằng user `forum`:

[source,console,role="transcript"]
....
postgres@learn_postgresql:/$ psql -U forum forumdb
forumdb=>
....

.Command
[source,bash]
....
psql -U forum forumdb
....


Để liệt kê tất cả table trong database `forumdb`, chúng ta phải dùng meta-command của `psql`, cụ thể là `\dt`. Meta-command `\dt` liệt kê tất cả table hiện có trong database `forumdb`:

[source,console,role="transcript"]
....
forumdb=> \dt
              List of relations
 Schema |          Name      | Type   | Owner
--------+--------------+-------+-------
 forum    | categories       | table | forum
 forum    | j_posts_tags | table | forum
 forum    | posts            | table | forum
 forum    | tags             | table | forum
 forum    | users            | table | forum
(5 rows)
....

.SQL
[source,sql]
....
\dt
....

.Output
[source,output]
....
              List of relations
 Schema |          Name      | Type   | Owner
--------+--------------+-------+-------
 forum    | categories       | table | forum
 forum    | j_posts_tags | table | forum
 forum    | posts            | table | forum
 forum    | tags             | table | forum
 forum    | users            | table | forum
(5 rows)
....


== Tạo database mới từ template đã sửa đổi

Bây giờ đã biết cách liệt kê tất cả table trong một database, hãy bảo đảm rằng mọi thay đổi được thực hiện trên database `template1` sẽ xuất hiện trong mọi database được tạo sau đó. Chúng ta sẽ thực hiện các bước sau:

. Kết nối đến database `template1`.
. Tạo table tên `dummytable` trong database `template1`.
. Tạo database mới tên `dummydb`.

Hãy bắt đầu tạo database theo các bước sau:

. Kết nối đến database `template1`:

[source,console,role="transcript"]
....
   postgres@learn_postgresql:/$ psql template1
   template1=#
....

.Command
[source,bash]
....
psql template1
....


. Với tư cách *superuser*, tạo table tên `dummytable`. Hiện tại, chúng ta chưa cần quan tâm đến cú pháp chính xác để tạo table; nội dung này sẽ được giải thích chi tiết hơn ở phần sau:

[source,console,role="transcript"]
....
   template1=# create table dummytable (dummyfield integer not null
   primary key);
   CREATE TABLE
....

.SQL
[source,sql]
....
CREATE TABLE dummytable (dummyfield integer NOT NULL
   PRIMARY KEY);
....

.Output
[source,output]
....
   CREATE TABLE
....


. Dùng meta-command `\dt` để hiển thị danh sách các table hiện có trong database `template1`:

[source,console,role="transcript"]
....
   template1=# \dt
                List of relations
    Schema |        Name   | Type   |     Owner
   --------+------------+-------+----------
    public | dummytable | table | postgres
   (1 row)
....

.SQL
[source,sql]
....
\dt
....

.Output
[source,output]
....
                List of relations
    Schema |        Name   | Type   |     Owner
   --------+------------+-------+----------
    public | dummytable | table | postgres
   (1 row)
....


. Vì vậy, chúng ta đã thêm thành công table mới vào database `template1`. Bây giờ hãy thử tạo database mới có tên `dummydb` và liệt kê tất cả table trong database `dummydb`:

[source,console,role="transcript"]
....
template1=# create database dummydb;
CREATE DATABASE
template1=# \c dummydb
You are now connected to database "dummydb" as user "postgres".
....

.SQL
[source,sql]
....
CREATE DATABASE dummydb;
\c dummydb
....

.Output
[source,output]
....
CREATE DATABASE
You are now connected to database "dummydb" as user "postgres".
....


Database `dummydb` chứa các table sau:

[source,console,role="transcript"]
....
dummydb=# \dt
             List of relations
 Schema |       Name      | Type    |   Owner
--------+------------+-------+----------
 public | dummytable | table | postgres
(1 row)
....

.SQL
[source,sql]
....
\dt
....

.Output
[source,output]
....
             List of relations
 Schema |       Name      | Type    |   Owner
--------+------------+-------+----------
 public | dummytable | table | postgres
(1 row)
....


Đúng như dự kiến, database `dummydb` chứa table đã được tạo trước đó trong database `template1`.

[quote]
____
Điều quan trọng cần nhớ là mọi thay đổi được thực hiện trên database `template1` sẽ xuất hiện trong mọi database được tạo sau thay đổi đó.

____
Bây giờ chúng ta sẽ xóa database `dummydb` và table dummytable trong database `template1`.

== Xóa table và database
Trong phần tiếp theo, bạn sẽ học cách xóa table và database. Các lệnh chúng ta sẽ sử dụng là:

* `DROP TABLE`: Dùng để xóa table trong database.
* `DROP DATABASE`: Dùng để xóa database trong cluster.

== Xóa table
Trong PostgreSQL, lệnh dùng để xóa table đơn giản là `DROP TABLE tablename`. Để thực hiện việc này, chúng ta phải kết nối đến database chứa table đó, rồi chạy lệnh `DROP TABLE tablename`.

Ví dụ, nếu muốn xóa table `dummytable` khỏi database `template1`, chúng ta phải thực hiện các bước sau.

Chúng ta kết nối đến database `template1` bằng lệnh sau:

[source,console,role="transcript"]
....
dummydb=# \c template1
You are now connected to database "template1" as user "postgres".
....

.SQL
[source,sql]
....
\c template1
....

.Output
[source,output]
....
You are now connected to database "template1" as user "postgres".
....


Sau đó, chúng ta có thể xóa table bằng lệnh sau:

[source,console,role="transcript"]
....
template1=# drop table dummytable;
DROP TABLE
....

.SQL
[source,sql]
....
DROP TABLE dummytable;
....

.Output
[source,output]
....
DROP TABLE
....


== Xóa database
Trong PostgreSQL, lệnh dùng để xóa một table đơn giản là `DROP DATABASE databasename`; ví dụ, nếu muốn xóa database `dummydb`, chúng ta phải thực thi lệnh sau:

[source,console,role="transcript"]
....
template1=# drop database dummydb ;
DROP DATABASE
....

.SQL
[source,sql]
....
DROP DATABASE dummydb;
....

.Output
[source,output]
....
DROP DATABASE
....


Sau đó, mọi thứ trở về trạng thái ban đầu của chương.

== Tạo bản sao database
Các bước sau đây hướng dẫn cách tạo database mới từ một template database:

. Tạo bản sao của database `forumdb` trên cùng PostgreSQL cluster bằng lệnh sau:

[source,console,role="transcript"]
....
   template1=# create database forumdb2 template forumdb;
   CREATE DATABASE
....

.SQL
[source,sql]
....
CREATE DATABASE forumdb2 template forumdb;
....

.Output
[source,output]
....
   CREATE DATABASE
....


   Khi sử dụng lệnh này, bạn chỉ yêu cầu PostgreSQL tạo database mới có tên `forumdb2` và dùng database `forumdb` làm template.

[%start=2]
. Kết nối đến database `forumdb2` với tư cách user forum:

[source,console,role="transcript"]
....
   postgres@learn_postgresql:/$ psql -U forum forumdb2
   forumdb2=>
....

.Command
[source,bash]
....
psql -U forum forumdb2
....


. Liệt kê tất cả table trong database `forumdb2`:

[source,console,role="transcript"]
....
   forumdb2=> \dt
                List of relations
    Schema |       Name       | Type    | Owner
   --------+--------------+-------+-------
    forum    | categories     | table | forum
    forum    | j_posts_tags | table | forum
    forum    | posts          | table | forum
    forum    | tags           | table | forum
    forum    | users          | table | forum
   (5 rows)
....

.SQL
[source,sql]
....
\dt
....

.Output
[source,output]
....
                List of relations
    Schema |       Name       | Type    | Owner
   --------+--------------+-------+-------
    forum    | categories     | table | forum
    forum    | j_posts_tags | table | forum
    forum    | posts          | table | forum
    forum    | tags           | table | forum
    forum    | users          | table | forum
   (5 rows)
....


Bạn có thể thấy các table trong database `forumdb` hiện cũng có trong database này.

== Xác nhận kích thước database
Bây giờ chúng ta sẽ trả lời câu hỏi làm thế nào để xác định kích thước thực của database. Có hai phương thức bạn có thể sử dụng: `psql` và SQL. Hãy so sánh hai phương thức này trong các phần sau.

== Phương thức psql
Chúng ta có thể kiểm tra kích thước database bằng `psql` theo các bước sau:

. Đầu tiên, hãy kết nối đến `forumdb` và chuyển về expanded mode:

[source,console,role="transcript"]
....
   postgres@learn_postgresql:/$ psql -U forum forumdb
   forumdb=> \x
   Expanded display is on.
....

.Command
[source,bash]
....
psql -U forum forumdb
....

.SQL
[source,sql]
....
\x
....

.Output
[source,output]
....
   Expanded display is on.
....


. Sau đó, thực thi lệnh sau:

[source,console,role="transcript"]
....
   forumdb=# \l+ forumdb
   List of databases
   -[ RECORD 1 ]-----+-----------
   Name                 | forumdb
   Owner                | forum
   Encoding             | UTF8
   Collate              | en_US.utf8
   Ctype                | en_US.utf8
   ICU Locale           |
   Locale Provider      | libc
   Access privileges    |
   Size                 | 7685 kB
   Tablespace           | pg_default
   Description          |
....

.SQL
[source,sql]
....
\l+ forumdb
....

.Output
[source,output]
....
   List of databases
   -[ RECORD 1 ]-----+-----------
   Name                 | forumdb
   Owner                | forum
   Encoding             | UTF8
   Collate              | en_US.utf8
   Ctype                | en_US.utf8
   ICU Locale           |
   Locale Provider      | libc
   Access privileges    |
   Size                 | 7685 kB
   Tablespace           | pg_default
   Description          |
....


Trong trường `Size`, bạn có thể thấy kích thước thực của database tại thời điểm đó.

== Phương thức SQL
Khi sử dụng phương thức được mô tả ở trên, bạn có thể gặp trường hợp không thể kết nối đến database bằng lệnh `psql`. Điều này xảy ra khi chúng ta chỉ có quyền truy cập database qua web; ví dụ, khi chỉ có quyền truy cập vào bản cài đặt pgadmin4 ở phía server. Trong trường hợp đó, phương thức SQL là cách tiếp cận thay thế, cho phép tìm cùng thông tin. Để sử dụng phương thức này, hãy thực hiện các bước sau:

. Thực thi lệnh sau:

[source,console,role="transcript"]
....
   forumdb=> select pg_database_size('forumdb');
   -[ RECORD 1 ]----+--------
   pg_database_size | 7869231
....

.SQL
[source,sql]
....
SELECT pg_database_size('forumdb');
....

.Output
[source,output]
....
   -[ RECORD 1 ]----+--------
   pg_database_size | 7869231
....


   Function `pg_database_size(name)` trả về dung lượng đĩa mà database có tên `forumdb` sử dụng. Điều đó có nghĩa là kết quả là số byte mà database sử dụng.

[%start=2]
. Nếu muốn kết quả dễ đọc hơn, bạn có thể sử dụng function `pg_size_pretty` như sau:

[source,console,role="transcript"]
....
   forumdb=> select pg_size_pretty(pg_database_size('forumdb'));
   -[ RECORD 1 ]--+--------
   pg_size_pretty | 7685 kB
....

.SQL
[source,sql]
....
SELECT pg_size_pretty(pg_database_size('forumdb'));
....

.Output
[source,output]
....
   -[ RECORD 1 ]--+--------
   pg_size_pretty | 7685 kB
....


Như bạn có thể thấy, cả hai phương thức đều cho cùng một kết quả.

== Điều gì xảy ra phía sau khi tạo database
Chúng ta vừa học các lệnh dùng để tạo database mới, nhưng điều gì xảy ra phía sau khi database được tạo?

Trong phần này, chúng ta sẽ xem xét mối quan hệ giữa những gì chúng ta thực hiện ở cấp SQL và những gì xảy ra về mặt vật lý trong filesystem; lưu ý rằng các số OID dưới đây liên quan đến Docker image đã tạo. Các giá trị số trong Docker image của bạn có thể khác.

Để hiểu điều này, chúng ta cần giới thiệu system table `pg_database`:

. Quay lại expanded mode và thực thi như sau:

[source,console,role="transcript"]
....
   forumdb=> select * from pg_database where datname='forumdb';
   -[ RECORD 1 ]--+-----------
   oid               | 16386
   datname           | forumdb
   datdba            | 16385
   encoding          | 6
   datlocprovider | c
   datistemplate     | f
   datallowconn      | t
   datconnlimit      | -1
   datfrozenxid      | 717
   datminmxid        | 1
   dattablespace     | 1663
   datcollate        | en_US.utf8
   datctype          | en_US.utf8
   daticulocale      |
   datcollversion | 2.31
   datacl            |
....

.SQL
[source,sql]
....
SELECT *
FROM pg_database
WHERE datname = 'forumdb';
....

.Output
[source,output]
....
   -[ RECORD 1 ]--+-----------
   oid               | 16386
   datname           | forumdb
   datdba            | 16385
   encoding          | 6
   datlocprovider | c
   datistemplate     | f
   datallowconn      | t
   datconnlimit      | -1
   datfrozenxid      | 717
   datminmxid        | 1
   dattablespace     | 1663
   datcollate        | en_US.utf8
   datctype          | en_US.utf8
   daticulocale      |
   datcollversion | 2.31
   datacl            |
....


   Query này cung cấp mọi thông tin về database `forumdb`. Trường đầu tiên là Object Identifier (OID), một số nhận diện duy nhất của database có tên `forumdb`.

[%start=2]
. Thoát khỏi môi trường `psql` và đi đến thư mục `$PGDATA` (như đã trình bày trong các chương trước). Trong môi trường Linux Debian, chúng ta phải thực hiện:

[source,text]
....
   cd /var/lib/postgresql/16/main/
....

   Với Docker image, đường dẫn như sau:

[source,text]
....
   cd /postgres/16/data
....

Nếu không biết giá trị của `$PGDATA`, chúng ta có thể thực hiện lệnh sau với tư cách superuser:

[source,console,role="transcript"]
....
   forumdb=# show data_directory;
     data_directory
   -------------------
   /postgres/16/data
   (1 row)
....

.SQL
[source,sql]
....
show data_directory;
....

.Output
[source,output]
....
     data_directory
   -------------------
   /postgres/16/data
   (1 row)
....


[%start=3]
. Dùng lệnh `ls` để xem nội dung của thư mục `main` hoặc `data` (Docker image):

[source,console,role="transcript"]
....
   postgres@learn_postgresql:~/data$ ls -l
   total 128
   drwx------ 8 postgres postgres           4096 Jan   3 09:49 base
   drwx------ 2 postgres postgres           4096 Jan   3 09:49 global
   [...]
....

.Command
[source,bash]
....
ls -l
....

.Output
[source,output]
....
   total 128
   drwx------ 8 postgres postgres           4096 Jan   3 09:49 base
   drwx------ 2 postgres postgres           4096 Jan   3 09:49 global
   [...]
....


Như bạn có thể thấy, thư mục đầu tiên có tên `base`. Nó chứa tất cả database trong cluster.

[%start=4]
. Đi vào thư mục `base` để xem nội dung:

[source,console,role="transcript"]
....
   postgres@learn_postgresql:~/data$ cd base
   postgres@learn_postgresql:~/data/base$
....

.Command
[source,bash]
....
cd base
....


. Liệt kê tất cả file hiện có trong thư mục:

[source,console,role="transcript"]
....
   postgres@learn_postgresql:~/data/base$ ls -l
   total 40
   drwx------ 2 postgres postgres           4096 Jan   3 09:45 1
   drwx------ 2 postgres postgres 12288 Jan            3 09:14 16386
   [....]
....

.Command
[source,bash]
....
ls -l
....

.Output
[source,output]
....
   total 40
   drwx------ 2 postgres postgres           4096 Jan   3 09:45 1
   drwx------ 2 postgres postgres 12288 Jan            3 09:14 16386
   [....]
....


Như bạn có thể thấy, có một thư mục tên `16386`; tên của thư mục này chính là OID trong catalog `pg_database`.

[quote]
____
Khi PostgreSQL tạo database mới, nó sao chép thư mục tương ứng với database `template1`, sau đó đặt tên mới cho thư mục đó. Trong PostgreSQL, database được biểu diễn bằng các thư mục.

____
Trong phần này, chúng ta đã học cách quản lý database. Trong phần tiếp theo, chúng ta sẽ học cách quản lý table.
