= Sử dụng subquery

Trong section này, chúng ta sẽ nói về subquery. Subquery có thể được mô tả là query lồng nhau - chúng ta có thể lồng một query bên trong một query khác bằng cách sử dụng dấu ngoặc đơn. Subquery có thể trả về một giá trị đơn hoặc một record set, giống như các query thông thường. Chúng ta sẽ bắt đầu giới thiệu subquery bằng operator `IN`/`NOT IN`.

== Subquery và điều kiện `IN`/`NOT IN`

Hãy bắt đầu với operator `IN`; chúng ta có thể sử dụng operator `IN` bên trong clause `where` thay vì sử dụng nhiều điều kiện `OR`. Ví dụ, nếu muốn tìm kiếm tất cả category có giá trị `pk=1` hoặc giá trị `pk=2`, bạn phải thực hiện statement sau:

[source,text]
....
forumdb=> select * from categories where pk=1 or pk=2;
 pk |    title    |            description
 ----+----------+------------------------------
  1 | Database    | Database related discussions
  2 | Unix        | Unix and Linux discussions
(2 rows)
....

Một cách khác để đạt được cùng kết quả là:

[source,text]
....
forumdb=> select * from categories where pk in (1,2);
 pk |    title    |            description
 ----+----------+------------------------------
  1 | Database    | Database related discussions
  2 | Unix        | Unix and Linux discussions
(2 rows)
....

Một operator tương tự operator `IN` nhưng có chức năng ngược lại là operator `NOT IN`. Ví dụ, nếu muốn tìm kiếm tất cả category không có `pk=1` hoặc `pk=2`, chúng ta phải thực thi như sau:

[source,text]
....
forumdb=> select * from categories where pk not in (1,2);
 pk |            title             |             description
 ----+-----------------------+----------------------------
  3 | Programming Languages       | All about programming languages
  4 | New Category                | (NULL)
  5 | Database                    | PostgreSQL
(3 rows)
....

Bây giờ chúng ta có thể insert một ít dữ liệu vào table `users` và table `posts`:

[source,text]
....
forumdb=> insert into users (username,email) values ('luca_ferrari','luca@
pgtraining.com'),('enrico_pirozzi','enrico@pgtraining.com');
INSERT 0 2
....

Các statement sau đây insert dữ liệu vào table `posts`:

[source,text]
....
forumdb=> insert into posts (title,content,author,category) values
('Indexing PostgreSQL','Btree in PostgreSQL is....',1,1);
INSERT 0 1
forumdb=> insert into posts (title,content,author,category) values
('Indexing Mysql','Btree in Mysql is....',1,1);
INSERT 0 1
forumdb=> insert into posts (title,content,author,category) values ('Data
types in C++','Data type in C++ are ..' ,2,3);
INSERT 0 1
....

Các record hiện có trong table `posts` lúc này là như sau:

[source,text]
....
forumdb=> \x
Expanded display is on.
forumdb=> select pk,title,content,author,category from posts;
-[ RECORD 1 ]------------------------
pk        | 1
title     | Indexing PostgreSQL
content   | Btree in PostgreSQL is....
author    | 1
category  | 1
-[ RECORD 2 ]------------------------
pk        | 2
title     | Indexing Mysql
content   | Btree in Mysql is....
author    | 1
category  | 1
-[ RECORD 3 ]------------------------
pk        | 3
title     | Data types in C++
content   | Data type in C++ are ..
author    | 2
category  | 3
....

Giả sử bây giờ chúng ta muốn tìm kiếm tất cả post thuộc category `Database`. Có thể thực hiện việc này bằng một số phương pháp.

Phương pháp sau sử dụng subquery:

[source,text]
....
forumdb=> select pk,title,content,author,category from posts where
category in (select pk from categories where title ='Database');
-[ RECORD 1 ]------------------------
pk         | 1
title      | Indexing PostgreSQL
content    | Btree in PostgreSQL is....
author     | 1
category   | 1
-[ RECORD 2 ]------------------------
pk         | 2
title      | Indexing Mysql
content    | Btree in Mysql is....
author     | 1
category   | 1
....

Subquery được biểu diễn như sau:

[source,text]
....
forumdb=> \x
Expanded display is off.

forumdb=> select pk from categories where title ='Database';
 pk
----
  1
  5
(2 rows)
....

Statement này trích xuất các giá trị `pk=1` và `pk=5` từ category table, còn query bên ngoài tìm các record trong table `posts` có `pk=1` hoặc `pk=5`. Tương tự, nếu muốn tìm tất cả post không thuộc category `Database`, chúng ta phải thực hiện statement sau:

[source,text]
....
forumdb=> \x
Expanded display is on.

forumdb=> select pk,title,content,author,category from posts where
category not in (select pk from categories where title ='Database');
-[ RECORD 1 ]---------------------
pk       | 3
title    | Data types in C++
content  | Data type in C++ are ..
author   | 2
category | 3
....

== Subquery và điều kiện `EXISTS`/`NOT EXISTS`

Statement `EXISTS` được sử dụng khi muốn kiểm tra xem một subquery có trả về kết quả hay không (`TRUE`), còn statement `NOT EXISTS` được sử dụng khi muốn kiểm tra xem một subquery không trả về kết quả (`FALSE`). Ví dụ, nếu muốn viết các điều kiện giống như các điều kiện đã viết trước đó bằng điều kiện `EXISTS`/`NOT EXISTS`, chúng ta phải thực hiện như sau:

[source,text]
....
forumdb=> select pk,title,content,author,category from posts where exists
(select 1 from categories where title ='Database' and posts.category=pk);
-[ RECORD 1 ]------------------------
pk         | 1
title      | Indexing PostgreSQL
content    | Btree in PostgreSQL is....
author     | 1
category   | 1
-[ RECORD 2 ]------------------------
pk         | 2
title      | Indexing Mysql
content    | Btree in Mysql is....
author     | 1
category   | 1
....

Query trên trả về cùng kết quả với query được viết bằng điều kiện `IN`.

Tương tự, nếu muốn tìm tất cả post không thuộc category `Database` bằng điều kiện `NOT EXISTS`, chúng ta phải viết như sau:

[source,text]
....
forumdb=> select pk,title,content,author,category from posts where not
exists (select 1 from categories where title ='Database' and posts.
category=pk);
-[ RECORD 1 ]------------------
pk       | 3
title    | Data types in C++
content  | Data type in C++ are ..
author   | 2
category | 3
....

Cả hai query được viết bằng điều kiện `IN` và bằng điều kiện `EXISTS` đều được gọi là query semi-join, và chúng ta sẽ xem xét các join trong section tiếp theo.
