= Ví dụ về query tuning

Trong phần trước, bạn đã tìm hiểu cách `EXPLAIN` có thể hiển thị plan mà PostgreSQL sẽ dùng để truy cập data bên dưới; bây giờ là lúc dùng `EXPLAIN` để tune một số query chậm và cải thiện performance.

Phần này trình bày một số khái niệm cơ bản về cách sử dụng `EXPLAIN` hằng ngày như một công cụ mạnh để xác định nên instrument PostgreSQL ở đâu và bằng cách nào để truy cập data nhanh hơn. Dĩ nhiên, query tuning là một chủ đề rất phức tạp và thường đòi hỏi tối ưu hóa dựa trên việc thử nghiệm lặp đi lặp lại, vì vậy mục tiêu của phần này không phải là cung cấp cho bạn kiến thức chuyên sâu về query tuning mà là giúp bạn có hiểu biết cơ bản về cách cải thiện database và các query của mình.

Đôi khi, query tuning chỉ đơn giản là viết lại query theo cách PostgreSQL thấy dễ xử lý hơn hoặc, chính xác hơn, dễ hiểu hơn; nhưng thường thì query tuning có nghĩa là sử dụng một index phù hợp để tăng tốc việc truy cập data bên dưới.

Một điều quan trọng cần tính đến khi query tuning là cache effect: khi PostgreSQL truy cập một phần data, nó nạp data đó vào memory trong shared buffers. Vùng memory này hoạt động như một cache; vì vậy, nếu PostgreSQL lại cần cùng data đó, nó sẽ đọc data từ memory thay vì truy cập disk storage. Hệ quả là query có thể chậm ở lần đầu, nhưng nếu được thực thi lần thứ hai và, nói rộng hơn, lặp đi lặp lại, thời gian thực thi có thể ngắn hơn lần đầu. Vì vậy, khi kiểm tra một query chậm, hãy thử thực thi nó nhiều lần liên tiếp để xem cache effect có thể ảnh hưởng đến thời gian thực thi như thế nào.

Giả định database của chúng ta chứa một nghìn author, mỗi author đăng năm trăm post, tổng cộng nửa triệu post:

[source,console,role="transcript"]
....
forumdb=> SELECT reltuples, pg_size_pretty( pg_relation_size( oid ) ),
relname FROM pg_class
WHERE relname IN ( 'posts', 'users' ) AND relkind = 'r';
reltuples | pg_size_pretty | relname
-----------+----------------+---------
    500000 | 59 MB                 | posts
      1000 | 88 kB                 | users
....

.SQL
[source,sql]
....
SELECT
    reltuples,
    pg_size_pretty(pg_relation_size(oid)),
    relname
FROM pg_class
WHERE relname IN ('posts', 'users') AND relkind = 'r';
....

.Output
[source,output]
....
reltuples | pg_size_pretty | relname
-----------+----------------+---------
    500000 | 59 MB                 | posts
      1000 | 88 kB                 | users
....


[quote]
____
Docker image của chương này đã được nạp sẵn lượng data nói trên. Hãy cẩn thận, vì lượng data này cần khoảng 60 MB dung lượng disk trống.

____
Hãy bắt đầu với một ví dụ đơn giản: chúng ta muốn lấy tất cả post theo thứ tự ngày tạo, nên query là:

[source,sql]
....
SELECT *
FROM posts
ORDER BY created_on;
....

Chúng ta có thể truyền query này cho `EXPLAIN` để hình dung PostgreSQL sẽ thực thi nó như thế nào:

[source,console,role="transcript"]
....
forumdb=> EXPLAIN SELECT * FROM posts ORDER BY created_on;
                                         QUERY PLAN
---------------------------------------------------------------------
Sort       (cost=83838.92..85088.92 rows=500000 width=81)
   Sort Key: created_on
   ->      Seq Scan on posts     (cost=0.00..12584.00 rows=500000 width=81)
....

.SQL
[source,sql]
....
EXPLAIN SELECT *
FROM posts
ORDER BY created_on;
....

.Output
[source,output]
....
                                         QUERY PLAN
---------------------------------------------------------------------
Sort       (cost=83838.92..85088.92 rows=500000 width=81)
   Sort Key: created_on
   ->      Seq Scan on posts     (cost=0.00..12584.00 rows=500000 width=81)
....


Như bạn có thể thấy, node đầu tiên được thực thi là sequential scan (initial cost bằng 0); node này sẽ tạo ra 500.000 tuple làm output. Tại sao lại là sequential scan? Trước hết, không có filtering clause nào vì chúng ta muốn lấy toàn bộ data được lưu trong table; thứ hai, table không có access method nào (không có index).

Vì chúng ta yêu cầu sort output, node tiếp theo được thực thi là Sort node; node này tạo ra đúng số lượng tuple như result.

Query trước đó mất bao lâu để hoàn tất? `EXPLAIN ANALYZE` có thể giúp chúng ta trả lời câu hỏi đó:

[source,console,role="transcript"]
....
forumdb=> EXPLAIN ANALYZE SELECT * FROM posts ORDER BY created_on;
                                                           ------------------
--------------------------------------------------------------------------
-------------------------
Sort (cost=83838.92..85088.92 rows=500000 width=81) (actual
time=304.283..393.395 rows=500000 loops=1)
   Sort Key: created_on
   Sort Method: external merge       Disk: 51192kB
     -> Seq Scan on posts (cost=0.00..12584.00 rows=500000 width=81)
(actual time=0.045..63.449 rows=500000 loops=1)
Planning Time: 0.059 ms
Execution Time: 429.838 ms
....

.SQL
[source,sql]
....
EXPLAIN ANALYZE SELECT * FROM posts ORDER BY created_on;
....

.Output
[source,output]
....
                                                           ------------------
--------------------------------------------------------------------------
-------------------------
Sort (cost=83838.92..85088.92 rows=500000 width=81) (actual
time=304.283..393.395 rows=500000 loops=1)
   Sort Key: created_on
   Sort Method: external merge       Disk: 51192kB
     -> Seq Scan on posts (cost=0.00..12584.00 rows=500000 width=81)
(actual time=0.045..63.449 rows=500000 loops=1)
Planning Time: 0.059 ms
Execution Time: 429.838 ms
....


Thời gian thực thi thuần túy gần nửa giây. Liệu có thể giảm tổng thời gian bằng cách tạo một index riêng trên column `created_on` hay không:

[source,console,role="transcript"]
....
forumdb=> CREATE INDEX idx_posts_date ON posts( created_on );
CREATE INDEX
forumdb=> EXPLAIN ANALYZE SELECT * FROM posts ORDER BY created_on;


QUERY PLAN
--------------------------------------------------------------------------
-------------------------------------------------------------
Index Scan using idx_posts_date on posts (cost=0.42..16887.80 rows=500000
width=81) (actual time=0.079..133.305 rows=500000 loops=1)
Planning Time: 0.203 ms
Execution Time: 162.143 ms
(3 rows)
....

.SQL
[source,sql]
....
CREATE INDEX idx_posts_date ON posts(created_on);
EXPLAIN ANALYZE SELECT * FROM posts ORDER BY created_on;
....

.Output
[source,output]
....
CREATE INDEX


QUERY PLAN
--------------------------------------------------------------------------
-------------------------------------------------------------
Index Scan using idx_posts_date on posts (cost=0.42..16887.80 rows=500000
width=81) (actual time=0.079..133.305 rows=500000 loops=1)
Planning Time: 0.203 ms
Execution Time: 162.143 ms
(3 rows)
....


Query hiện chạy trong gần một phần ba thời gian so với khi không có index; trên thực tế, query plan đã thay đổi từ sequential scan thành index scan nhờ index mới tạo.

Dĩ nhiên, index mới tạo sẽ chiếm thêm dung lượng lưu trữ; như bạn có thể hình dung, tốc độ tăng lên đi kèm với chi phí về dung lượng, có thể kiểm tra như sau:

[source,console,role="transcript"]
....
forumdb=> SELECT pg_size_pretty( pg_relation_size( 'posts' ) ) AS table_
size,
    pg_size_pretty( pg_relation_size( 'idx_posts_date' ) ) AS index_size;
   table_size | index_size
-------------+------------
59 MB         | 3600 kB
(1 row)
....

.SQL
[source,sql]
....
SELECT pg_size_pretty(pg_relation_size('posts')) AS table_ size, pg_size_pretty(pg_relation_size('idx_posts_date')) AS index_size;
....

.Output
[source,output]
....
   table_size | index_size
-------------+------------
59 MB         | 3600 kB
(1 row)
....


Dung lượng disk bổ sung này có quá lớn hay không phụ thuộc vào tài nguyên và mục tiêu cuối cùng của bạn; trong trường hợp trên, với giả định bạn thực thi query khá thường xuyên, mức tăng tốc độ xứng đáng với phần dung lượng bổ sung.

Bây giờ hãy tập trung vào một query điển hình hơn: tìm tất cả post của một user cụ thể trong một khoảng thời gian cụ thể. Query tương ứng sẽ có dạng như sau, với giả định khoảng thời gian là 2 ngày:

[source,sql]
....
SELECT
    p.title,
    u.username
FROM posts p JOIN users u ON u.pk = p.author
WHERE u.username = 'fluca1978' AND daterange(CURRENT_DATE - 20, CURRENT_DATE) @> p.created_on::date
....

PostgreSQL thực thi query trước đó như thế nào? Một lần nữa, `EXPLAIN` có thể giúp chúng ta hiểu database cho rằng đâu là query plan tốt nhất:

[source,console,role="transcript"]
....
forumdb=> EXPLAIN
      SELECT p.title, u.username
      FROM posts p
      JOIN users u ON u.pk = p.author
      WHERE u.username = 'fluca1978'
    AND   daterange( CURRENT_DATE - 20, CURRENT_DATE ) @> p.created_
on::date;


                                              QUERY PLAN
--------------------------------------------------------------------------
---------------------------
Gather      (cost=1008.30..13803.58 rows=2 width=26)
   Workers Planned: 2
   ->     Hash Join     (cost=8.30..12803.38 rows=1 width=26)
            Hash Cond: (p.author = u.pk)
        ->       Parallel Seq Scan on posts p     (cost=0.00..12792.33 rows=1042
width=15)
              Filter: (daterange((CURRENT_DATE - 2), CURRENT_DATE) @>
(created_on)::date)
            ->   Hash    (cost=8.29..8.29 rows=1 width=19)
              -> Index Scan using users_username_key on users u
(cost=0.28..8.29 rows=1 width=19)
                         Index Cond: (username = 'fluca1978'::text)
....

.SQL
[source,sql]
....
EXPLAIN SELECT
    p.title,
    u.username
FROM posts p JOIN users u ON u.pk = p.author
WHERE u.username = 'fluca1978' AND daterange(CURRENT_DATE - 20, CURRENT_DATE) @> p.created_ ON::date;
....

.Output
[source,output]
....
                                              QUERY PLAN
--------------------------------------------------------------------------
---------------------------
Gather      (cost=1008.30..13803.58 rows=2 width=26)
   Workers Planned: 2
   ->     Hash Join     (cost=8.30..12803.38 rows=1 width=26)
            Hash Cond: (p.author = u.pk)
        ->       Parallel Seq Scan on posts p     (cost=0.00..12792.33 rows=1042
width=15)
              Filter: (daterange((CURRENT_DATE - 2), CURRENT_DATE) @>
(created_on)::date)
            ->   Hash    (cost=8.29..8.29 rows=1 width=19)
              -> Index Scan using users_username_key on users u
(cost=0.28..8.29 rows=1 width=19)
                         Index Cond: (username = 'fluca1978'::text)
....


Planner đã chọn khởi chạy parallel query execution: node trên cùng là một Gather node, nên nó hoạt động như một synchronization point cho các parallel worker. Cụ thể, planner quyết định sử dụng hai parallel process để hoàn tất query. Node ngoài cùng bên phải, và do đó là node đầu tiên được thực thi, là một Index Scan node trên table users. Kết quả được đưa vào hash, đồng thời một Parallel Seq Scan được khởi chạy để lấy data từ table posts. Các result được join, rồi Gather thu thập final result set. Tổng execution time của query này có thể dễ dàng lấy được bằng `EXPLAIN ANALYZE`; kết quả cho thấy query mất khoảng 140 millisecond để hoàn tất:

[source,console,role="transcript"]
....
forumdb=> EXPLAIN ANALYZE
     SELECT p.title, u.username
     FROM posts p
     JOIN users u ON u.pk = p.author
     WHERE u.username = 'fluca1978'
    AND   daterange( CURRENT_DATE - 20, CURRENT_DATE ) @> p.created_
on::date;




   QUERY PLAN
--------------------------------------------------------------------------
---------------------------------------------------------------------
Gather (cost=1008.30..13803.58 rows=2 width=26) (actual
time=0.856..141.434 rows=20 loops=1)
   Workers Planned: 2
   Workers Launched: 2
  -> Hash Join (cost=8.30..12803.38 rows=1 width=26) (actual
time=0.968..135.209 rows=7 loops=3)
          Hash Cond: (p.author = u.pk)
        -> Parallel Seq Scan on posts p (cost=0.00..12792.33 rows=1042
width=15) (actual time=0.076..133.975 rows=6667 loops=3)
              Filter: (daterange((CURRENT_DATE - 20), CURRENT_DATE) @>
(created_on)::date)
                 Rows Removed by Filter: 160000
        -> Hash (cost=8.29..8.29 rows=1 width=19) (actual
time=0.053..0.054 rows=1 loops=3)
                 Buckets: 1024      Batches: 1     Memory Usage: 9kB
             -> Index Scan using users_username_key on users u
(cost=0.28..8.29 rows=1 width=19) (actual time=0.047..0.048 rows=1
loops=3)
                      Index Cond: (username = 'fluca1978'::text)
Planning Time: 0.188 ms
Execution Time: 141.471 ms
....

.SQL
[source,sql]
....
EXPLAIN ANALYZE
     SELECT p.title, u.username
     FROM posts p
     JOIN users u ON u.pk = p.author
     WHERE u.username = 'fluca1978'
    AND daterange(CURRENT_DATE - 20, CURRENT_DATE) @> p.created_
ON::date;
....

.Output
[source,output]
....
   QUERY PLAN
--------------------------------------------------------------------------
---------------------------------------------------------------------
Gather (cost=1008.30..13803.58 rows=2 width=26) (actual
time=0.856..141.434 rows=20 loops=1)
   Workers Planned: 2
   Workers Launched: 2
  -> Hash Join (cost=8.30..12803.38 rows=1 width=26) (actual
time=0.968..135.209 rows=7 loops=3)
          Hash Cond: (p.author = u.pk)
        -> Parallel Seq Scan on posts p (cost=0.00..12792.33 rows=1042
width=15) (actual time=0.076..133.975 rows=6667 loops=3)
              Filter: (daterange((CURRENT_DATE - 20), CURRENT_DATE) @>
(created_on)::date)
                 Rows Removed by Filter: 160000
        -> Hash (cost=8.29..8.29 rows=1 width=19) (actual
time=0.053..0.054 rows=1 loops=3)
                 Buckets: 1024      Batches: 1     Memory Usage: 9kB
             -> Index Scan using users_username_key on users u
(cost=0.28..8.29 rows=1 width=19) (actual time=0.047..0.048 rows=1
loops=3)
                      Index Cond: (username = 'fluca1978'::text)
Planning Time: 0.188 ms
Execution Time: 141.471 ms
....


Điều gì xảy ra nếu chúng ta thêm một index cho column `author` của table posts?

[source,console,role="transcript"]
....
forumdb=> CREATE INDEX idx_posts_author ON posts( author );
CREATE INDEX
forumdb=> EXPLAIN ANALYZE
     SELECT p.title, u.username
     FROM posts p
     JOIN users u ON u.pk = p.author
     WHERE u.username = 'fluca1978'
    AND   daterange( CURRENT_DATE - 20, CURRENT_DATE ) @> p.created_
on::date;



   QUERY PLAN
--------------------------------------------------------------------------
---------------------------------------------------------
Nested Loop (cost=8.45..1602.29 rows=2 width=26) (actual
time=0.145..0.926 rows=20 loops=1)
  -> Index Scan using users_username_key on users u (cost=0.28..8.29
rows=1 width=19) (actual time=0.011..0.012 rows=1 loops=1)
            Index Cond: (username = 'fluca1978'::text)
  -> Bitmap Heap Scan on posts p (cost=8.17..1593.98 rows=2 width=15)
(actual time=0.129..0.904 rows=20 loops=1)
            Recheck Cond: (author = u.pk)
            Filter: (daterange((CURRENT_DATE - 20), CURRENT_DATE) @> (created_
on)::date)
            Rows Removed by Filter: 480
            Heap Blocks: exact=500
         -> Bitmap Index Scan on idx_posts_author (cost=0.00..8.17
rows=500 width=0) (actual time=0.059..0.059 rows=500 loops=1)
                   Index Cond: (author = u.pk)
Planning Time: 0.401 ms
Execution Time: 0.954 ms
(12 rows)
....

.SQL
[source,sql]
....
CREATE INDEX idx_posts_author ON posts(author);
EXPLAIN ANALYZE
     SELECT p.title, u.username
     FROM posts p
     JOIN users u ON u.pk = p.author
     WHERE u.username = 'fluca1978'
    AND daterange(CURRENT_DATE - 20, CURRENT_DATE) @> p.created_
ON::date;
....

.Output
[source,output]
....
CREATE INDEX



   QUERY PLAN
--------------------------------------------------------------------------
---------------------------------------------------------
Nested Loop (cost=8.45..1602.29 rows=2 width=26) (actual
time=0.145..0.926 rows=20 loops=1)
  -> Index Scan using users_username_key on users u (cost=0.28..8.29
rows=1 width=19) (actual time=0.011..0.012 rows=1 loops=1)
            Index Cond: (username = 'fluca1978'::text)
  -> Bitmap Heap Scan on posts p (cost=8.17..1593.98 rows=2 width=15)
(actual time=0.129..0.904 rows=20 loops=1)
            Recheck Cond: (author = u.pk)
            Filter: (daterange((CURRENT_DATE - 20), CURRENT_DATE) @> (created_
on)::date)
            Rows Removed by Filter: 480
            Heap Blocks: exact=500
         -> Bitmap Index Scan on idx_posts_author (cost=0.00..8.17
rows=500 width=0) (actual time=0.059..0.059 rows=500 loops=1)
                   Index Cond: (author = u.pk)
Planning Time: 0.401 ms
Execution Time: 0.954 ms
(12 rows)
....


Trước hết, query hiện chạy tuần tự vì không có Gather node nào; điều này có nghĩa là PostgreSQL giờ có thể thu hẹp result set cần kiểm tra ngay từ đầu. Ngoài ra, execution time hiện đã nhỏ hơn một millisecond.

Như bạn có thể thấy, khác với parallel plan trước đó, node đầu tiên được thực thi hiện là một Index Scan node trên table posts; sau đó, result set sau khi thu hẹp được join với table authors bằng Nested Loop. Việc sử dụng Nested Loop xác nhận rằng PostgreSQL đã có thể thu hẹp result set, chỉ lấy trước những tuple cần thiết từ table posts.

Cũng cần lưu ý rằng không còn lý do để giữ index trên column `created_on`, vì query plan vừa nêu không còn sử dụng index này.

Bây giờ các index cần bao nhiêu dung lượng? Một lần nữa, việc kiểm tra khá đơn giản:

[source,console,role="transcript"]
....
forumdb=> SELECT pg_size_pretty( pg_relation_size( 'posts') ) AS table_
size,
         pg_size_pretty( pg_relation_size( 'idx_posts_date' ) ) AS idx_date_
size,
        pg_size_pretty( pg_relation_size( 'idx_posts_author' ) ) AS idx_
author_size;


      table_size | idx_date_size | idx_author_size
   ------------+---------------+-----------------
   59 MB         | 3600 kB            | 3600 kB


   (1 row)
....

.SQL
[source,sql]
....
SELECT pg_size_pretty(pg_relation_size('posts')) AS table_ size, pg_size_pretty(pg_relation_size('idx_posts_date')) AS idx_date_ size, pg_size_pretty(pg_relation_size('idx_posts_author')) AS idx_ author_size;
....

.Output
[source,output]
....
      table_size | idx_date_size | idx_author_size
   ------------+---------------+-----------------
   59 MB         | 3600 kB            | 3600 kB


   (1 row)
....


Cả hai index đều chiếm cùng một lượng dung lượng, nhưng như đã nói, chúng ta có thể drop date-based index vì nó không còn cần thiết. Thực tế, ngay cả với một date clause cụ thể, index này cũng không còn được sử dụng:

[source,console,role="transcript"]
....
forumdb=> EXPLAIN ANALYZE
      SELECT p.title, u.username
      FROM posts p
      JOIN users u ON u.pk = p.author
      WHERE u.username = 'fluca1978'
        AND     p.created_on::date = CURRENT_DATE -2;


                                                                            QUERY PLAN
--------------------------------------------------------------------------
---------------------------------------------------------
Nested Loop (cost=8.45..1599.79 rows=2 width=26) (actual
time=0.132..0.737 rows=1 loops=1)
  -> Index Scan using users_username_key on users u (cost=0.28..8.29
rows=1 width=19) (actual time=0.009..0.010 rows=1 loops=1)
           Index Cond: (username = 'fluca1978'::text)
  -> Bitmap Heap Scan on posts p (cost=8.17..1591.48 rows=2 width=15)
(actual time=0.119..0.723 rows=1 loops=1)
           Recheck Cond: (author = u.pk)
           Filter: ((created_on)::date = (CURRENT_DATE - 2))
           Rows Removed by Filter: 499
           Heap Blocks: exact=500
        -> Bitmap Index Scan on idx_posts_author (cost=0.00..8.17
rows=500 width=0) (actual time=0.053..0.053 rows=500 loops=1)
                  Index Cond: (author = u.pk)
Planning Time: 0.237 ms
Execution Time: 0.763 ms
....

.SQL
[source,sql]
....
EXPLAIN ANALYZE
    SELECT p.title, u.username
    FROM posts p
    JOIN users u ON u.pk = p.author
    WHERE u.username = 'fluca1978'
      AND p.created_on::date = CURRENT_DATE -2;
....

.Output
[source,output]
....
                                                                            QUERY PLAN
--------------------------------------------------------------------------
---------------------------------------------------------
Nested Loop (cost=8.45..1599.79 rows=2 width=26) (actual
time=0.132..0.737 rows=1 loops=1)
  -> Index Scan using users_username_key on users u (cost=0.28..8.29
rows=1 width=19) (actual time=0.009..0.010 rows=1 loops=1)
           Index Cond: (username = 'fluca1978'::text)
  -> Bitmap Heap Scan on posts p (cost=8.17..1591.48 rows=2 width=15)
(actual time=0.119..0.723 rows=1 loops=1)
           Recheck Cond: (author = u.pk)
           Filter: ((created_on)::date = (CURRENT_DATE - 2))
           Rows Removed by Filter: 499
           Heap Blocks: exact=500
        -> Bitmap Index Scan on idx_posts_author (cost=0.00..8.17
rows=500 width=0) (actual time=0.053..0.053 rows=500 loops=1)
                  Index Cond: (author = u.pk)
Planning Time: 0.237 ms
Execution Time: 0.763 ms
....


Việc xác định các index không được sử dụng rất quan trọng vì cho phép chúng ta thu hồi dung lượng trên disk, đồng thời đơn giản hóa việc quản lý và chèn data. Hãy nhớ rằng mỗi khi table thay đổi, index phải được update; việc này cũng đòi hỏi thêm tài nguyên như thời gian và dung lượng trên disk.

Vì vậy, như bạn có thể thấy, việc phân tích những query mà application của bạn thực thi thường xuyên nhất và xác định liệu một index có thể cải thiện tốc độ thực thi hay không là thực sự quan trọng. Tuy nhiên, hãy nhớ rằng index kéo theo cost bổ sung cả về dung lượng lẫn maintenance, vì vậy đừng lạm dụng index.

Nhưng làm thế nào bạn có thể xác định các index không được sử dụng mà không cần biết các query đang chạy?

May mắn là PostgreSQL cung cấp thông tin chi tiết về việc sử dụng mọi index: view đặc biệt `pg_stat_user_indexes` cho biết một index đã được sử dụng bao nhiêu lần và được sử dụng như thế nào. Ví dụ, để lấy thông tin về các index trên table posts, bạn có thể thực thi query sau:

[source,console,role="transcript"]
....
forumdb=> SELECT indexrelname, idx_scan, idx_tup_read, idx_tup_fetch FROM
pg_stat_user_indexes WHERE relname = 'posts';
....

.SQL
[source,sql]
....
SELECT
    indexrelname,
    idx_scan,
    idx_tup_read,
    idx_tup_fetch
FROM pg_stat_user_indexes
WHERE relname = 'posts';
....


[source,output]
....
   indexrelname      | idx_scan | idx_tup_read | idx_tup_fetch
------------------+----------+--------------+---------------
posts_pkey           |          5 |                5 |                 5
idx_posts_date       |          1 |          500000 |            500000
idx_posts_author |             51 |            8534 |                  0
....

Điều này cho biết `idx_posts_date` đã được sử dụng 1 lần và cung cấp 500000 tuple, trong khi `idx_posts_author` đã được sử dụng 51 lần nhưng chỉ cung cấp 8534 tuple, ít hơn rất nhiều; điều đó cho thấy index này rất hiệu quả.

Sau khi theo dõi xu hướng này trong một khoảng thời gian, bạn có thể an toàn drop `idx_posts_date` nếu index này hiếm khi được sử dụng.

Cuối cùng, hãy xem xét một query được viết kém và vấn đề đi kèm: giả sử chúng ta muốn lấy tất cả author đã tạo post vào một ngày nhất định và trong chính ngày đó nhận được một số lượng like cụ thể. Một query tệ có thể là query sau:

[source,sql]
....
SELECT u.username
FROM users u JOIN posts p ON p.author = u.pk
WHERE p.created_on = CURRENT_ DATE - 5 AND u.pk IN (SELECT pp.author FROM posts pp WHERE likes = 5 AND p.created_on = created_on);
....

Rõ ràng không cần subquery trên table `posts`, nhưng đây là ví dụ cụ thể cho thấy tại sao cần hiểu cách viết query tốt.

Thoạt nhìn, query trước đó chạy đủ nhanh: nó mất 190 millisecond để thực thi, như `EXPLAIN ANALYZE` cho thấy:

[source,console,role="transcript"]
....
   forumdb=> EXPLAIN ANALYZE SELECT u.username
   FROM users u JOIN posts p ON p.author = u.pk WHERE p.created_on = CURRENT_
   DATE - 5
   AND u.pk IN ( SELECT pp.author FROM posts pp WHERE likes = 5 and
   p.created_on = created_on );
                                                                               QUERY PLAN
   --------------------------------------------------------------------------
   -------------------------------------------------------------
   Hash Join (cost=33.93..92.04 rows=498 width=15) (actual
   time=1.351..189.308 rows=100 loops=1)
   Hash Cond: (p.author = u.pk)
      Join Filter: (SubPlan 1)
      Rows Removed by Join Filter: 900
     -> Index Scan using idx_posts_date on posts p (cost=0.43..55.92
   rows=996 width=12) (actual time=0.029..0.254 rows=1000 loops=1)
              Index Cond: (created_on = (CURRENT_DATE - 5))
     -> Hash (cost=21.00..21.00 rows=1000 width=19) (actual
   time=0.345..0.345 rows=1000 loops=1)
              Buckets: 1024    Batches: 1    Memory Usage: 59kB
           -> Seq Scan on users u (cost=0.00..21.00 rows=1000 width=19)
   (actual time=0.006..0.151 rows=1000 loops=1)
      SubPlan 1
       -> Index Scan using idx_posts_date on posts pp (cost=0.42..58.49
   rows=99 width=4) (actual time=0.005..0.176 rows=95 loops=1000)
                Index Cond: (created_on = p.created_on)
                Filter: (likes = 5)
                Rows Removed by Filter: 855
   Planning Time: 0.393 ms
   Execution Time: 189.439 ms
....

.SQL
[source,sql]
....
EXPLAIN ANALYZE SELECT u.username
   FROM users u JOIN posts p ON p.author = u.pk WHERE p.created_on = CURRENT_
   DATE - 5
   AND u.pk IN (SELECT pp.author FROM posts pp WHERE likes = 5 AND
   p.created_on = created_on);
....

.Output
[source,output]
....
                                                                               QUERY PLAN
   --------------------------------------------------------------------------
   -------------------------------------------------------------
   Hash Join (cost=33.93..92.04 rows=498 width=15) (actual
   time=1.351..189.308 rows=100 loops=1)
   Hash Cond: (p.author = u.pk)
      Join Filter: (SubPlan 1)
      Rows Removed by Join Filter: 900
     -> Index Scan using idx_posts_date on posts p (cost=0.43..55.92
   rows=996 width=12) (actual time=0.029..0.254 rows=1000 loops=1)
              Index Cond: (created_on = (CURRENT_DATE - 5))
     -> Hash (cost=21.00..21.00 rows=1000 width=19) (actual
   time=0.345..0.345 rows=1000 loops=1)
              Buckets: 1024    Batches: 1    Memory Usage: 59kB
           -> Seq Scan on users u (cost=0.00..21.00 rows=1000 width=19)
   (actual time=0.006..0.151 rows=1000 loops=1)
      SubPlan 1
       -> Index Scan using idx_posts_date on posts pp (cost=0.42..58.49
   rows=99 width=4) (actual time=0.005..0.176 rows=95 loops=1000)
                Index Cond: (created_on = p.created_on)
                Filter: (likes = 5)
                Rows Removed by Filter: 855
   Planning Time: 0.393 ms
   Execution Time: 189.439 ms
....


Tuy nhiên, khi xem output, bạn có thể thấy node *Index Scan* sử dụng `idx_posts_date` trên `pp posts` có bộ đếm `loops` bằng 1000: điều này nghĩa là node này được thực thi 1.000 lần trong query. Node này chính là subquery, và đó là cách SQL đạt được kết quả: mỗi khi tìm thấy một tuple từ outer query, inner query phải chạy và các result phải được join. Một lựa chọn có thể là rewrite query để PostgreSQL không phải loop, chẳng hạn bằng cách dùng subquery với expression `GROUP BY`:

[source,console,role="transcript"]
....
   forumdb=> EXPLAIN ANALYZE
   WITH likes AS (
             SELECT pp.author, pp.created_on FROM posts pp
             WHERE likes = 5
             GROUP BY pp.author, pp.created_on
                  )
   SELECT u.username
   FROM users u JOIN posts p ON p.author = u.pk
   JOIN likes l ON l.created_on = p.created_on AND l.author = u.pk
   WHERE p.created_on = CURRENT_DATE - 5;
....

.SQL
[source,sql]
....
EXPLAIN ANALYZE
   WITH likes AS (
             SELECT pp.author, pp.created_on FROM posts pp
             WHERE likes = 5
             GROUP BY pp.author, pp.created_on
                  )
   SELECT u.username
   FROM users u JOIN posts p ON p.author = u.pk
   JOIN likes l ON l.created_on = p.created_on AND l.author = u.pk
   WHERE p.created_on = CURRENT_DATE - 5;
....


[source,output]
....
  --------------------------------------------------------------------------
  -------------------------------------------------------------------------
  ---------------
  Hash Join (cost=89.47..149.68 rows=98 width=15) (actual time=0.581..0.896
  rows=100 loops=1)
      Hash Cond: (p.author = u.pk)
    -> Index Scan using idx_posts_date on posts p (cost=0.43..55.92
  rows=996 width=12) (actual time=0.012..0.167 rows=1000 loops=1)
            Index Cond: (created_on = (CURRENT_DATE - 5))
    -> Hash (cost=87.82..87.82 rows=98 width=31) (actual time=0.561..0.562
  rows=100 loops=1)
            Buckets: 1024   Batches: 1   Memory Usage: 15kB
          -> Hash Join (cost=62.09..87.82 rows=98 width=31) (actual
  time=0.305..0.540 rows=100 loops=1)
                  Hash Cond: (u.pk = l.author)
                -> Seq Scan on users u (cost=0.00..21.00 rows=1000
  width=19) (actual time=0.005..0.094 rows=1000 loops=1)
                -> Hash (cost=60.86..60.86 rows=98 width=12) (actual
  time=0.294..0.294 rows=100 loops=1)
                        Buckets: 1024   Batches: 1   Memory Usage: 13kB
                      -> Subquery Scan on l (cost=58.90..60.86 rows=98
  width=12) (actual time=0.243..0.276 rows=100 loops=1)
                            -> HashAggregate (cost=58.90..59.88 rows=98
  width=12) (actual time=0.242..0.260 rows=100 loops=1)
                                     Group Key: pp.author, pp.created_on
                                     Batches: 1   Memory Usage: 24kB
                                    -> Index Scan using idx_posts_date on
  posts pp    (cost=0.43..58.41 rows=98 width=12) (actual time=0.009..0.208
  rows=100 loops=1)
                                            Index Cond: (created_on = (CURRENT_
  DATE - 5))
                                            Filter: (likes = 5)
                                            Rows Removed by Filter: 900
  Planning Time: 0.455 ms
  Execution Time: 0.954 ms
....

Output này cho thấy thời gian thực thi chưa đến một millisecond; đáng chú ý nhất là PostgreSQL không phải loop qua cùng một subquery nhiều lần.

Rõ ràng, viết query mà hoàn toàn không dùng subquery là cách hiệu quả nhất để PostgreSQL hiểu cần phải làm gì:

[source,console,role="transcript"]
....
   forumdb=> EXPLAIN ANALYZE
   SELECT u.username
   FROM users u JOIN posts p ON p.author = u.pk
   WHERE p.created_on = CURRENT_DATE - 5
   AND p.likes = 5;
                                                                           QUERY PLAN
   --------------------------------------------------------------------------
   --------------------------------------------------------
   Hash Join (cost=33.93..92.17 rows=98 width=15) (actual time=0.413..0.638
   rows=100 loops=1)
      Hash Cond: (p.author = u.pk)
     -> Index Scan using idx_posts_date on posts p (cost=0.43..58.41
   rows=98 width=4) (actual time=0.015..0.212 rows=100 loops=1)
             Index Cond: (created_on = (CURRENT_DATE - 5))
             Filter: (likes = 5)
             Rows Removed by Filter: 900
     -> Hash (cost=21.00..21.00 rows=1000 width=19) (actual
   time=0.393..0.394 rows=1000 loops=1)
           Buckets: 1024     Batches: 1     Memory Usage: 59kB
         -> Seq Scan on users u (cost=0.00..21.00 rows=1000 width=19)
   (actual time=0.007..0.173 rows=1000 loops=1)
   Planning Time: 0.263 ms
   Execution Time: 0.666 ms
....

.SQL
[source,sql]
....
EXPLAIN ANALYZE
   SELECT u.username
   FROM users u JOIN posts p ON p.author = u.pk
   WHERE p.created_on = CURRENT_DATE - 5
   AND p.likes = 5;
....

.Output
[source,output]
....
                                                                           QUERY PLAN
   --------------------------------------------------------------------------
   --------------------------------------------------------
   Hash Join (cost=33.93..92.17 rows=98 width=15) (actual time=0.413..0.638
   rows=100 loops=1)
      Hash Cond: (p.author = u.pk)
     -> Index Scan using idx_posts_date on posts p (cost=0.43..58.41
   rows=98 width=4) (actual time=0.015..0.212 rows=100 loops=1)
             Index Cond: (created_on = (CURRENT_DATE - 5))
             Filter: (likes = 5)
             Rows Removed by Filter: 900
     -> Hash (cost=21.00..21.00 rows=1000 width=19) (actual
   time=0.393..0.394 rows=1000 loops=1)
           Buckets: 1024     Batches: 1     Memory Usage: 59kB
         -> Seq Scan on users u (cost=0.00..21.00 rows=1000 width=19)
   (actual time=0.007..0.173 rows=1000 loops=1)
   Planning Time: 0.263 ms
   Execution Time: 0.666 ms
....


Ví dụ đơn giản trên cho thấy vì sao việc hiểu output của `EXPLAIN` và `EXPLAIN ANALYZE` lại quan trọng: nhờ đó, bạn có thể xác định rõ hơn query có đang thiếu index hay cần được rewrite để PostgreSQL thực hiện công việc tốt nhất hay không.
