= Kết nối SSL

Secure Sockets Layer (SSL) cho phép PostgreSQL chấp nhận các network connection được mã hóa. Nghĩa là mọi phần dữ liệu trong mỗi packet đều được mã hóa và nhờ đó được bảo vệ khỏi network spoofing, miễn là key và certificate được xử lý đúng cách.

Để bật SSL, trước tiên bạn cần cấu hình server, sau đó cho phép các SSL connection đến, và cuối cùng cấu hình client để kết nối ở SSL mode.

== Cấu hình database cluster cho SSL

Để SSL mã hóa dữ liệu, server phải có private certificate và public certificate. Việc tạo và quản lý certificate nằm ngoài phạm vi cuốn sách này và là một chủ đề phức tạp; bạn có thể tham khảo tài liệu chính thức của PostgreSQL để biết các bước cần thiết nhằm tự tạo certificate. Khi bạn hoặc tổ chức của bạn đã có certificate, việc duy nhất cần làm là đặt certificate và key file vào PostgreSQL server.

Giả sử certificate và key file của bạn lần lượt có tên `server.crt` và `server.key`, bạn phải cấu hình các parameter sau trong configuration file `postgresql.conf`:

[source,text]
....
   ssl = on
   ssl_key_file = '/postgres/16/data/ssl/server.key'
   ssl_cert_file = '/postgres/16/data/ssl/server.crt'
....

Tất nhiên, bạn cần dùng absolute path tới các file của mình. Dòng đầu tiên yêu cầu PostgreSQL bật SSL, còn hai dòng kia cho server biết nơi tìm các file cần thiết để thiết lập connection được mã hóa. User chạy PostgreSQL database cluster phải đọc được các file đó (thường là operating-system user `postgres`).

Sau khi bật SSL, bạn cần điều chỉnh file `pg_hba.conf` để host-based access control xử lý các connection qua SSL. Cụ thể, nếu không muốn chấp nhận connection không mã hóa, bạn cần thay mọi dòng `host` bằng `hostssl`, ví dụ:

[source,text]
....
   hostssl       all   luca         venkman             scram-sha-256
   hostssl       all   forum     192.168.222.1/32 scram-sha-256
....

Nếu muốn chấp nhận cả connection không mã hóa lẫn connection được mã hóa, bạn có thể giữ `host` làm connection method.

== Kết nối tới database cluster qua SSL

Khi kết nối tới PostgreSQL, client sẽ tự động dùng SSL connection nếu host-based access control có dòng `hostssl`; nếu không, client sẽ mặc định dùng connection tiêu chuẩn không mã hóa.

Nếu `pg_hba.conf` có dòng `host`, điều đó có nghĩa là file này có thể chấp nhận cả SSL connection lẫn connection không mã hóa. Vì vậy, bạn cần buộc connection sử dụng SSL khi khởi tạo connection. Trong `psql`, điều này chỉ có thể thực hiện bằng cách dùng connection string và chỉ định parameter `sslmode=require` để bật SSL. Nếu server chấp nhận connection, bạn sẽ thấy protocol SSL đang được sử dụng:

[source,console,role="transcript"]
....
   $ psql "postgresql://forum@localhost:5432/forumdb?sslmode=require"
   psql (16.0)
   SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits:
   256, compression: off)
   Type "help" for help.


   forumdb=>
....

.Command
[source,bash]
....
psql "postgresql://forum@localhost:5432/forumdb?sslmode=require"
....

.Output
[source,output]
....
   psql (16.0)
   SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits:
   256, compression: off)
   Type "help" for help.
....


Nếu bỏ parameter `sslmode` hoặc dùng các parameter connection tiêu chuẩn của `psql`, connection sẽ dùng SSL nếu file `pg_hba.conf` có một dòng `hostssl` khớp. Ví dụ, ba connection sau cho cùng một kết quả (một connection được mã hóa):

[source,console,role="transcript"]
....
   $ psql -h localhost -U forum forumdb
   psql (16.0)
   SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits:
   256, compression: off)
   Type "help" for help.


   forumdb=> \q


   $ psql "postgresql://forum@localhost:5432/forumdb"
   psql (16.0)
   SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits:
   256, compression: off)
   Type "help" for help.


   forumdb=> \q


   $ psql "postgresql://forum@localhost:5432/forumdb?sslmode=require"
   psql (16.0)
   SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits:
   256, compression: off)
   Type "help" for help.


   forumdb=>
....

.Command
[source,bash]
....
psql -h localhost -U forum forumdb
psql "postgresql://forum@localhost:5432/forumdb"
psql "postgresql://forum@localhost:5432/forumdb?sslmode=require"
....

.SQL
[source,sql]
....
\q \q
....

.Output
[source,output]
....
   psql (16.0)
   SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits:
   256, compression: off)
   Type "help" for help.




   psql (16.0)
   SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits:
   256, compression: off)
   Type "help" for help.




   psql (16.0)
   SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits:
   256, compression: off)
   Type "help" for help.
....


Tương tự, bạn có thể chỉ định rằng hoàn toàn không muốn dùng SSL connection bằng cách đặt `sslmode=disable`. Lần này, nếu `pg_hba.conf` có method `hostssl`, connection sẽ bị từ chối, còn nếu file `pg_hba.conf` có dòng `host` thì connection sẽ được thiết lập dưới dạng không mã hóa:

[source,console,role="transcript"]
....
   $ psql "postgresql://forum@localhost:5432/forumdb?sslmode=require"
   psql: error: could not connect to server: FATAL:  no pg_hba.conf entry for
   host "127.0.0.1", user "forum", database "forumdb", SSL off
....

.Command
[source,bash]
....
psql "postgresql://forum@localhost:5432/forumdb?sslmode=require"
....

.Output
[source,output]
....
   psql: error: could not connect to server: FATAL:  no pg_hba.conf entry for
   host "127.0.0.1", user "forum", database "forumdb", SSL off
....


Từ lỗi này, bạn có thể thấy rõ rằng file `pg_hba.conf` không có dòng nào chấp nhận connection không mã hóa (mode `host`); nói cách khác, file chỉ có các dòng `hostssl`.

Cuối cùng, nếu yêu cầu connection sử dụng SSL nhưng PostgreSQL server chưa được cấu hình để dùng SSL, một thông báo lỗi về sự không khớp sẽ được hiển thị:

[source,console,role="transcript"]
....
   $ psql "postgresql://forum@localhost:5432/forumdb?sslmode=disable"
   psql: error: could not connect to server: server does not support SSL, but
   SSL was required
....

.Command
[source,bash]
....
psql "postgresql://forum@localhost:5432/forumdb?sslmode=disable"
....

.Output
[source,output]
....
   psql: error: could not connect to server: server does not support SSL, but
   SSL was required
....
