= Di chuyển từ MySQL/MariaDB sang PostgreSQL bằng pgloader

Trong phần này, chúng ta sẽ xem cách di chuyển một database từ MySQL/MariaDB sang PostgreSQL theo cách rất đơn giản. Công cụ chúng ta sử dụng có tên là pgloader. Tài liệu tham khảo thêm về phần này có tại https://pgloader.io.

Phần này sử dụng hai Docker container: một container chạy MariaDB server và một container chạy PostgreSQL server. MariaDB server có tên mariadb-source chứa bản sao của database forumdb được sử dụng trong Chapter 4; PostgreSQL server có tên pg-destination chứa một database forumdb rỗng. Mục tiêu là di chuyển toàn bộ nội dung của database forumdb từ mariadb-source server sang postgresql-destination server bằng pgloader.

Mở hai Bash terminal, rồi thực thi lệnh sau trong terminal thứ nhất:

[source,text]
....
chapter19$ bash run-pg-docker-mariadb.sh
....

Sau khi container khởi động, hãy thực thi statement dưới đây và dùng LearnPostgreSQL làm password:

[source,text]
....
root@mariadb-source:~# mysql -D forumdb -p
[...]
Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.


Type 'help;' or '\h' for help. Type '\c' to clear the current input
statement.


MariaDB [forumdb]>
....

Hiện chúng ta đang ở trong database forumdb và có thể chạy query trên database này:

[source,output]
....
MariaDB [forumdb]> show tables;
+-------------------+
| Tables_in_forumdb |
+-------------------+
| categories             |
| j_posts_tags           |
| posts                  |
| tags                   |
| users                  |
+-------------------+
5 rows in set (0.000 sec)
....

[source,output]
....
MariaDB [forumdb]> select * from categories;
+----+-----------------------+---------------------------------+
| pk | title                        | description                            |
+----+-----------------------+---------------------------------+
|   1 | Database                    | Database related discussions           |
|   2 | Unix                        | Unix and Linux discussions             |
|   3 | Programming Languages | All about programming languages |
+----+-----------------------+---------------------------------+
3 rows in set (0.002 sec)
....

[source,output]
....
MariaDB [forumdb]> select * from users;
+----+-----------+----------------+---------------------+
| pk | username      | gecos             | email                    |
+----+-----------+----------------+---------------------+
|   1 | fluca1978 | Luca Ferrari         | fluca1978@gmail.com |
|   2 | sscotty71 | Enrico Pirozzi | sscptty71@gmail.com |
+----+-----------+----------------+---------------------+
2 rows in set (0.001 sec)
....

Như có thể thấy, đây là database chúng ta đã sử dụng trong Chapter 4, Basic Statements.

Bây giờ, chuyển sang Bash terminal thứ hai và thực thi:

[source,text]
....
chapter19$ bash run-pg-docker-postgresql.sh
....

Sau khi container khởi động, thực thi:

[source,console,role="transcript"]
....
postgres@pg-destination:~$ psql forumdb
....

.Command
[source,bash]
....
psql forumdb
....


Như kết quả dưới đây cho thấy, PostgreSQL database đang trống:

[source,console,role="transcript"]
....
postgres@pg-destination:~$ psql forumdb
forumdb=# \d
Did not find any relations.
....

.Command
[source,bash]
....
psql forumdb
....

.SQL
[source,sql]
....
\d
....

.Output
[source,output]
....
Did not find any relations.
....


Bây giờ, thoát khỏi psql client và chạy command pgloader:

[source,console,role="transcript"]
....
forumdb=# \q
ppostgres@pg-destination:~$ pgloader mysql://root:LearnPostgreSQL@mariadb-
source/forumdb pgsql://postgres@127.0.0.1/forumdb


              table name       errors         rows        bytes        total time
-----------------------      ---------    ---------    ---------    --------------
          fetch meta data             0           22                          0.104s
           Create Schemas             0            0                          0.000s
         Create SQL Types             0            0                          0.004s
            Create tables             0           10                          0.056s
           Set Table OIDs             0            5                          0.020s
-----------------------      ---------    ---------    ---------    --------------
       forumdb.categories             0            3      0.1 kB              0.020s
            forumdb.users             0            2      0.1 kB              0.016s
     forumdb.j_posts_tags             0            0                          0.012s
             forumdb.tags             0            0                          0.016s
            forumdb.posts             0            0                          0.012s
-----------------------      ---------    ---------    ---------    --------------
COPY Threads Completion               0            4                          0.024s
   Index Build Completion             0           11                          0.048s
           Create Indexes             0           11                          0.092s
          Reset Sequences             0            4                          0.012s
             Primary Keys             0            4                          0.004s
      Create Foreign Keys             0            6                          0.004s
          Create Triggers             0            0                          0.000s
          Set Search Path             0            1                          0.000s
         Install Comments             0            0                          0.000s
-----------------------      ---------    ---------    ---------    --------------
        Total import time             ✓            5      0.2 kB              0.184s
....

.Command
[source,bash]
....
pgloader mysql://root:LearnPostgreSQL@mariadb-
....

.SQL
[source,sql]
....
\q
....

.Output
[source,output]
....
source/forumdb pgsql://postgres@127.0.0.1/forumdb


              table name       errors         rows        bytes        total time
-----------------------      ---------    ---------    ---------    --------------
          fetch meta data             0           22                          0.104s
           Create Schemas             0            0                          0.000s
         Create SQL Types             0            0                          0.004s
            Create tables             0           10                          0.056s
           Set Table OIDs             0            5                          0.020s
-----------------------      ---------    ---------    ---------    --------------
       forumdb.categories             0            3      0.1 kB              0.020s
            forumdb.users             0            2      0.1 kB              0.016s
     forumdb.j_posts_tags             0            0                          0.012s
             forumdb.tags             0            0                          0.016s
            forumdb.posts             0            0                          0.012s
-----------------------      ---------    ---------    ---------    --------------
COPY Threads Completion               0            4                          0.024s
   Index Build Completion             0           11                          0.048s
           Create Indexes             0           11                          0.092s
          Reset Sequences             0            4                          0.012s
             Primary Keys             0            4                          0.004s
      Create Foreign Keys             0            6                          0.004s
          Create Triggers             0            0                          0.000s
          Set Search Path             0            1                          0.000s
         Install Comments             0            0                          0.000s
-----------------------      ---------    ---------    ---------    --------------
        Total import time             ✓            5      0.2 kB              0.184s
....


Với command đơn giản này, chúng ta đã di chuyển MariaDB database forumdb sang PostgreSQL database forumdb. Bây giờ hãy kiểm tra xem mọi thứ đã được di chuyển hay chưa bằng cách kết nối lại với forumdb trên PostgreSQL server:

[source,console,role="transcript"]
....
postgres@pg-destination:~$ psql forumdb
....

.Command
[source,bash]
....
psql forumdb
....


[source,console,role="transcript"]
....
forumdb=# \dn
          List of schemas
   Name     |       Owner
---------+-------------------
 forumdb | postgres
 public     | pg_database_owner
(2 rows)


forumdb=# \dt forumdb.*
                    List of relations
     Schema     |     Name       | Type    |   Owner
    ---------+--------------+-------+----------
     forumdb | categories        | table | postgres
     forumdb | j_posts_tags | table | postgres
     forumdb | posts             | table | postgres
     forumdb | tags              | table | postgres
     forumdb | users             | table | postgres
(5 rows)
....

.SQL
[source,sql]
....
\dn \dt forumdb.*
....

.Output
[source,output]
....
          List of schemas
   Name     |       Owner
---------+-------------------
 forumdb | postgres
 public     | pg_database_owner
(2 rows)


                    List of relations
     Schema     |     Name       | Type    |   Owner
    ---------+--------------+-------+----------
     forumdb | categories        | table | postgres
     forumdb | j_posts_tags | table | postgres
     forumdb | posts             | table | postgres
     forumdb | tags              | table | postgres
     forumdb | users             | table | postgres
(5 rows)
....


Như có thể thấy ở trên, MariaDB database forumdb đã được di chuyển sang PostgreSQL database forumdb. pgloader tự động tạo một schema forumdb, nơi chứa toàn bộ table và dữ liệu từ database forumdb ban đầu của MariaDB; việc duy nhất còn lại là tạo user forumdb với đủ permission để sử dụng toàn bộ dữ liệu vừa import:

[source,console,role="transcript"]
....
forumdb=# create role forumdb with password 'LearnPostgreSQL' login;
CREATE ROLE


forumdb=# grant usage on schema forumdb to forumdb ;
GRANT
forumdb=# grant all on all tables in schema forumdb to forumdb ;
GRANT


forumdb=# \q
....

.SQL
[source,sql]
....
CREATE role forumdb WITH password 'LearnPostgreSQL' login;
GRANT usage ON schema forumdb to forumdb;
GRANT ALL ON ALL tables IN schema forumdb to forumdb;
\q
....

.Output
[source,output]
....
CREATE ROLE


GRANT
GRANT
....


Giờ đây, chúng ta có thể dùng user `forumdb` để truy cập database `forumdb` trên PostgreSQL:

[source,console,role="transcript"]
....
postgres@pg-destination:~$ psql -U forumdb forumdb

forumdb=> select * from categories;
    pk |          title             |             description
----+-----------------------+---------------------------------
     1 | Database                   | Database related discussions
     2 | Unix                       | Unix and Linux discussions
     3 | Programming Languages | All about programming languages
(3 rows)

forumdb=> select * from users;
    pk | username    |      gecos         |          email
----+-----------+----------------+---------------------
     1 | fluca1978 | Luca Ferrari         | fluca1978@gmail.com
     2 | sscotty71 | Enrico Pirozzi | sscptty71@gmail.com
(2 rows)
....

.Command
[source,bash]
....
psql -U forumdb forumdb
....

.SQL
[source,sql]
....
SELECT *
FROM categories;
SELECT *
FROM users;
....

.Output
[source,output]
....
    pk |          title             |             description
----+-----------------------+---------------------------------
     1 | Database                   | Database related discussions
     2 | Unix                       | Unix and Linux discussions
     3 | Programming Languages | All about programming languages
(3 rows)

    pk | username    |      gecos         |          email
----+-----------+----------------+---------------------
     1 | fluca1978 | Luca Ferrari         | fluca1978@gmail.com
     2 | sscotty71 | Enrico Pirozzi | sscptty71@gmail.com
(2 rows)
....
