= Kiểm tra kiến thức

* Nếu `myfield` là một field kiểu `varchar(200)` trong table `mytable`, statement `create index on mytable(myfield)` có giúp cải thiện query có điều kiện `where` dạng `like foo%` không?

  Không, statement trên sẽ không giúp cải thiện query có điều kiện `where` dạng `like ‘foo%'`; để làm được điều đó, chúng ta phải dùng `create index on mytable using btree(my field varchar_pattern_ops);`. Xem mục *Khám phá extension pg_trgm* để biết thêm chi tiết.

* Có thể dùng index cho mọi loại query `like` và `ilike` không?

  Có, có thể sử dụng `pg_trgm`. Xem mục *Khám phá extension pg_trgm* để biết thêm chi tiết.

* Point-in-time recovery (PITR) là gì?

  Trong phạm vi retention, point-in-time recovery là khả năng khôi phục về bất kỳ thời điểm nào trong quá khứ. Xem mục *Disaster recovery với pgbackrest* để biết thêm chi tiết.

* PostgreSQL có công cụ nào giúp quản lý continuous backup và point-in-time recovery không?

  Có, PostgreSQL có một số công cụ giúp quản lý continuous backup và PITR; pgbackrest là một trong số đó. Xem mục *Disaster recovery với pgbackrest* để biết thêm chi tiết.

* Có thể kết nối trực tiếp tới một PostgreSQL server khác không?

  Có, bằng extension foreign data wrapper của PostgreSQL. Xem mục *Sử dụng foreign data wrappers và extension postgres_fdw* để biết thêm chi tiết.
