= Default partition

Trong phần này, chúng ta sẽ xem điều gì xảy ra khi insert dữ liệu vào partitioned table trong lúc child partition chưa tồn tại, đồng thời tìm cách khắc phục vấn đề này. Để mô phỏng, giả sử chúng ta muốn insert một giá trị date là `2023-05-01` vào table có tên `part_tags`. Kết quả nhận được như sau:

[source,console,role="transcript"]
....
   forumdb=> insert into part_tags (tag,ins_date,level) values ('Ubuntu
   Linux','2023-05-01',2);
   ERROR:    no partition of relation "part_tags" found for row
   DETAIL:    Partition key of the failing row contains (ins_date) = (2023-05-
   01).
....

.SQL
[source,sql]
....
INSERT INTO part_tags (tag, ins_date, level)
VALUES ('Ubuntu Linux', '2023-05-01', 2);
....

.Output
[source,output]
....
   ERROR:    no partition of relation "part_tags" found for row
   DETAIL:    Partition key of the failing row contains (ins_date) = (2023-05-
   01).
....


Nguyên nhân là PostgreSQL không tìm thấy giá trị date `2023-05-01` trong mapping của các child table.

Để khắc phục nhược điểm này, cần sử dụng một default partition; mọi giá trị không được ánh xạ tới child table sẽ được insert vào đó.

Để thực hiện việc này, hãy thực thi statement sau:

[source,console,role="transcript"]
....
   forumdb=> CREATE TABLE part_tags_default PARTITION OF part_tags default;
   CREATE TABLE
....

.SQL
[source,sql]
....
CREATE TABLE part_tags_default PARTITION OF part_tags DEFAULT;
....

.Output
[source,output]
....
   CREATE TABLE
....


Bây giờ hãy thử thực hiện lại thao tác trước đó:

[source,console,role="transcript"]
....
   forumdb=> insert into part_tags (tag,ins_date,level) values ('Ubuntu
   Linux','2023-05-01',2);
   INSERT 0 1
....

.SQL
[source,sql]
....
INSERT INTO part_tags (tag, ins_date, level)
VALUES ('Ubuntu Linux', '2023-05-01', 2);
....

.Output
[source,output]
....
   INSERT 0 1
....


Lúc này, dữ liệu đã được insert vào default partition và có thể xem được qua parent table `part_tags`, như minh họa dưới đây:

[source,console,role="transcript"]
....
   forumdb=> select * from part_tags;
      pk |   ins_date   |       tag           | level
   ----+------------+--------------------+-------
       1 | 2023-01-01 | Operating Systems     |     0
       2 | 2023-02-01 | Linux                 |     1
       3 | 2023-03-01 | BSD Unix              |     1
       4 | 2023-04-01 | Rocky Linux Distro |        2
       6 | 2023-05-01 | Ubuntu Linux          |     2
   (5 rows)


   forumdb=> select * from part_tags_default ;
      pk |   ins_date   |    tag       | level


   ----+------------+--------------+-------
       6 | 2023-05-01 | Ubuntu Linux |        2
   (1 row)
....

.SQL
[source,sql]
....
SELECT *
FROM part_tags;
SELECT *
FROM part_tags_default;
....

.Output
[source,output]
....
      pk |   ins_date   |       tag           | level
   ----+------------+--------------------+-------
       1 | 2023-01-01 | Operating Systems     |     0
       2 | 2023-02-01 | Linux                 |     1
       3 | 2023-03-01 | BSD Unix              |     1
       4 | 2023-04-01 | Rocky Linux Distro |        2
       6 | 2023-05-01 | Ubuntu Linux          |     2
   (5 rows)


      pk |   ins_date   |    tag       | level


   ----+------------+--------------+-------
       6 | 2023-05-01 | Ubuntu Linux |        2
   (1 row)
....
