= Một case study đơn giản

Trong phần cuối này, chúng ta sẽ không sử dụng database `forumdb`. Thay vào đó, database dùng trong phần này có tên `world_temperatures`; database này chứa dữ liệu công khai được import từ tệp CSV công khai tại https://www.meteoblue.com/it/tempo/archive/export.

Có thể tìm thấy bản backup của database `db-world-temperatures` trên GitHub của Packtpub, trong thư mục `chapter 9`, với tên tệp `backup-db-world-temperatures.sql.gz`. Nếu sử dụng Docker image, bạn đã có mọi thứ cần thiết; nếu không, để import database, hãy chạy PostgreSQL trên server của bạn:

[source,console,role="transcript"]
....
   $ gunzip < backup-db-world-temperatures.sql.gz | psql
....

.Command
[source,bash]
....
gunzip < backup-db-world-temperatures.sql.gz | psql
....


Nếu sử dụng Docker image, chỉ cần chạy lệnh sau:

[source,console,role="transcript"]
....
   postgres@learn_postgresql:~$ psql -U postgres world_temperatures
....

.Command
[source,bash]
....
psql -U postgres world_temperatures
....


Sau đó, database `db-world-temperatures` đã sẵn sàng để sử dụng. Trong database này, bạn sẽ tìm thấy một table chưa được partition có tên `basilea` và một partitioned table có tên `basilea_partitioned`; cả hai table đều chứa dữ liệu nhiệt độ của thành phố Basel từ năm 1950 đến năm 2022, được lấy mẫu đều đặn mỗi giờ. Bây giờ, hãy xem việc truy vấn một partitioned table khác với việc truy vấn một table chưa được partition như thế nào. Trước khi tiếp tục bài tập, nếu chưa quen với cách hoạt động của statement `EXPLAIN`, hãy xem Chương 13, Câu lệnh EXPLAIN.

Trước hết, hãy sử dụng table chưa được partition và viết một query trả về nhiệt độ trung bình của 5 năm lạnh nhất trong giai đoạn bắt đầu từ năm 1950:

[source,console,role="transcript"]
....
   world_temperatures=# select extract (year from insert_time) as year,
   avg(temperature) avg_temp from basilea group by 1 order by 2 limit 5;
      year |       avg_temp


   ------+--------------------
      1956 | 8.8073832344034608
      1963 | 8.9077977708904110
      1980 | 9.3459840948315118
      1969 | 9.3705488990867580
      1972 | 9.3749401615437158
   (5 rows)
....

.SQL
[source,sql]
....
SELECT
    extract (year FROM insert_time) AS year,
    avg(temperature) avg_temp
FROM basilea
GROUP BY 1
ORDER BY 2
LIMIT 5;
....

.Output
[source,output]
....
      year |       avg_temp


   ------+--------------------
      1956 | 8.8073832344034608
      1963 | 8.9077977708904110
      1980 | 9.3459840948315118
      1969 | 9.3705488990867580
      1972 | 9.3749401615437158
   (5 rows)
....


Tương tự, hãy lấy ra 5 năm nóng nhất:

[source,console,role="transcript"]
....
   world_temperatures=# select extract (year from insert_time) as year,
   avg(temperature) avg_temp from basilea group by 1 order by 2 desc limit
   5;
      year |       avg_temp


   ------+---------------------
      2022 | 12.7320820592465753
      2018 | 12.5638742964611872
      2020 | 12.3662106902322404
      2014 | 12.0601722329908676
      2015 | 11.9246379973744292
   (5 rows)
....

.SQL
[source,sql]
....
SELECT
    extract (year FROM insert_time) AS year,
    avg(temperature) avg_temp
FROM basilea
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;
....

.Output
[source,output]
....
      year |       avg_temp


   ------+---------------------
      2022 | 12.7320820592465753
      2018 | 12.5638742964611872
      2020 | 12.3662106902322404
      2014 | 12.0601722329908676
      2015 | 11.9246379973744292
   (5 rows)
....


Hãy lấy kết quả cuối cùng làm ví dụ để xem query này được thực thi nội bộ như thế nào:

[source,console,role="transcript"]
....
   world_temperatures=# explain analyze select extract (year from insert_
   time) as year, avg(temperature) avg_temp from basilea group by 1 order by
   2 desc limit 5;
                                                                            QUERY PLAN


   --------------------------------------------------------------------------
   ----------------------------------------------------------
    Limit (cost=98293.21..98293.23 rows=5 width=64) (actual
   time=380.284..380.286 rows=5 loops=1)
      -> Sort (cost=98293.21..99892.99 rows=639912 width=64) (actual
   time=380.282..380.283 rows=5 loops=1)
              Sort Key: (avg(temperature)) DESC
              Sort Method: top-N heapsort        Memory: 25kB
            -> HashAggregate (cost=68067.20..87664.51 rows=639912 width=64)
   (actual time=380.121..380.253 rows=73 loops=1)
                       Group Key: EXTRACT(year FROM insert_time)
                       Planned Partitions: 32     Batches: 1     Memory Usage: 817kB
                  -> Seq Scan on basilea (cost=0.00..12074.90 rows=639912
   width=40) (actual time=0.030..189.680 rows=639912 loops=1)
    Planning Time: 0.170 ms
    Execution Time: 380.480 ms
   (10 rows)
....

.SQL
[source,sql]
....
EXPLAIN analyze SELECT extract (year FROM insert_
   time) AS year, avg(temperature) avg_temp FROM basilea GROUP BY 1 ORDER BY
   2 DESC LIMIT 5;
....

.Output
[source,output]
....
                                                                            QUERY PLAN


   --------------------------------------------------------------------------
   ----------------------------------------------------------
    Limit (cost=98293.21..98293.23 rows=5 width=64) (actual
   time=380.284..380.286 rows=5 loops=1)
      -> Sort (cost=98293.21..99892.99 rows=639912 width=64) (actual
   time=380.282..380.283 rows=5 loops=1)
              Sort Key: (avg(temperature)) DESC
              Sort Method: top-N heapsort        Memory: 25kB
            -> HashAggregate (cost=68067.20..87664.51 rows=639912 width=64)
   (actual time=380.121..380.253 rows=73 loops=1)
                       Group Key: EXTRACT(year FROM insert_time)
                       Planned Partitions: 32     Batches: 1     Memory Usage: 817kB
                  -> Seq Scan on basilea (cost=0.00..12074.90 rows=639912
   width=40) (actual time=0.030..189.680 rows=639912 loops=1)
    Planning Time: 0.170 ms
    Execution Time: 380.480 ms
   (10 rows)
....


Như có thể thấy, PostgreSQL thực hiện sequential scan trên toàn bộ table. Bây giờ, hãy xem xét partitioned table `basilea_partitioned`:

[source,console,role="transcript"]
....
   world_temperatures=# \d+ basilea_partitioned
                                                                          Partitioned
   table "public.basilea_partitioned"
       Column      |             Type               | [...]


   -------------+--------------------------+
    id             | integer                        | [...]


    insert_time | timestamp with time zone | [...]
....

.SQL
[source,sql]
....
\d+ basilea_partitioned
....

.Output
[source,output]
....
                                                                          Partitioned
   table "public.basilea_partitioned"
       Column      |             Type               | [...]


   -------------+--------------------------+
    id             | integer                        | [...]


    insert_time | timestamp with time zone | [...]
....


[source,text]
....
      temperature | numeric(8,6)                    | [...]


   Partition key: RANGE (insert_time)
   Indexes:
         "basilea_partitioned_pkey" PRIMARY KEY, btree (id, insert_time)
   Partitions: basilea_partitioned_1950 FOR VALUES FROM ('1949-12-31
   23:00:00+00') TO ('1950-12-31 23:00:00+00'),
            basilea_partitioned_1951 FOR VALUES FROM ('1950-12-31
   23:00:00+00') TO ('1951-12-31 23:00:00+00'),
   [....]
               basilea_partitioned_2023 FOR VALUES FROM ('2022-12-31
   23:00:00+00') TO ('2023-12-31 23:00:00+00'),
                  basilea_partitioned_default DEFAULT
....

Table được partition theo từng năm từ 1950 đến 2022, đồng thời có thêm một default partition (như đã giải thích trong phần Default partition).

Dữ liệu được phân bổ đều cho tất cả các child table. Nếu thực thi cùng query, chúng ta sẽ nhận được kết quả sau:

[source,console,role="transcript"]
....
   world_temperatures=# explain analyze select extract (year from insert_time) as
   year, avg(temperature) avg_temp from basilea_partitioned group by 1 order by
   2 desc limit 5;



   QUERY PLAN


   ------------------------------------------------------------------------------
   ------------------------------------------------------------------------------
   -----------------------------------------
    Limit (cost=13183.59..13183.61 rows=5 width=64) (actual
   time=169.996..174.092 rows=5 loops=1)
      -> Sort (cost=13183.59..13184.09 rows=200 width=64) (actual
   time=169.995..174.090 rows=5 loops=1)
              Sort Key: (avg(basilea_partitioned.temperature)) DESC
              Sort Method: top-N heapsort       Memory: 25kB
            -> Finalize GroupAggregate (cost=13127.60..13180.27 rows=200
   width=64) (actual time=169.812..174.060 rows=73 loops=1)
                     Group Key: (EXTRACT(year FROM basilea_partitioned.insert_time))
                  -> Gather Merge (cost=13127.60..13174.27 rows=400
   width=64) (actual time=169.802..173.941 rows=132 loops=1)
                        Workers Planned: 2
                        Workers Launched: 2
                        -> Sort (cost=12127.58..12128.08 rows=200 width=64)
   (actual time=140.386..140.401 rows=44 loops=3)
                               Sort Key: (EXTRACT(year FROM basilea_
   partitioned.insert_time))
                               Sort Method: quicksort    Memory: 30kB
                               Worker 0:   Sort Method: quicksort    Memory: 29kB
                               Worker 1:   Sort Method: quicksort    Memory: 29kB
                              -> Partial HashAggregate
   (cost=12116.93..12119.93 rows=200 width=64) (actual time=140.330..140.363
   rows=44 loops=3)
                                     Group Key: (EXTRACT(year FROM basilea_
   partitioned.insert_time))
                                     Batches: 1    Memory Usage: 64kB
                                     Worker 0:    Batches: 1   Memory Usage: 48kB
                                     Worker 1:    Batches: 1   Memory Usage: 64kB
                                    -> Parallel Append (cost=0.00..10780.64
   rows=267259 width=40) (actual time=0.010..79.251 rows=213304 loops=3)
                                          -> Parallel Seq Scan on basilea_
   partitioned_1952 basilea_partitioned_3 (cost=0.00..129.59 rows=5167
   width=40) (actual time=0.010..3.176 rows=8784 loops=1)
   [....]
                                            ->Parallel Seq Scan on basilea_
   partitioned_2018 basilea_partitioned_69 (cost=0.00..128.41 rows=5153
   width=40) (actual time=0.004..2.671 rows=8760 loops=1)
                                            -> Parallel Seq Scan on basilea_
   partitioned_2021 basilea_partitioned_72 (cost=0.00..128.41 rows=5153
   width=40) (actual time=0.003..2.651 rows=8760 loops=1)
                                          -> Parallel Seq Scan on basilea_
   partitioned_default basilea_partitioned_75 (cost=0.00..21.10 rows=888
   width=40) (actual time=0.000..0.000 rows=0 loops=1)
                                          -> Parallel Seq Scan on basilea_
   partitioned_2023 basilea_partitioned_74 (cost=0.00..1.01 rows=1 width=40)
   (actual time=0.008..0.009 rows=1 loops=1)
    Planning Time: 0.698 ms

   Execution Time: 174.250 ms
   (97 rows)
....

.SQL
[source,sql]
....
EXPLAIN analyze SELECT extract (year FROM insert_time) AS
   year, avg(temperature) avg_temp FROM basilea_partitioned GROUP BY 1 ORDER BY
   2 DESC LIMIT 5;
....

.Output
[source,output]
....
   QUERY PLAN


   ------------------------------------------------------------------------------
   ------------------------------------------------------------------------------
   -----------------------------------------
    Limit (cost=13183.59..13183.61 rows=5 width=64) (actual
   time=169.996..174.092 rows=5 loops=1)
      -> Sort (cost=13183.59..13184.09 rows=200 width=64) (actual
   time=169.995..174.090 rows=5 loops=1)
              Sort Key: (avg(basilea_partitioned.temperature)) DESC
              Sort Method: top-N heapsort       Memory: 25kB
            -> Finalize GroupAggregate (cost=13127.60..13180.27 rows=200
   width=64) (actual time=169.812..174.060 rows=73 loops=1)
                     Group Key: (EXTRACT(year FROM basilea_partitioned.insert_time))
                  -> Gather Merge (cost=13127.60..13174.27 rows=400
   width=64) (actual time=169.802..173.941 rows=132 loops=1)
                        Workers Planned: 2
                        Workers Launched: 2
                        -> Sort (cost=12127.58..12128.08 rows=200 width=64)
   (actual time=140.386..140.401 rows=44 loops=3)
                               Sort Key: (EXTRACT(year FROM basilea_
   partitioned.insert_time))
                               Sort Method: quicksort    Memory: 30kB
                               Worker 0:   Sort Method: quicksort    Memory: 29kB
                               Worker 1:   Sort Method: quicksort    Memory: 29kB
                              -> Partial HashAggregate
   (cost=12116.93..12119.93 rows=200 width=64) (actual time=140.330..140.363
   rows=44 loops=3)
                                     Group Key: (EXTRACT(year FROM basilea_
   partitioned.insert_time))
                                     Batches: 1    Memory Usage: 64kB
                                     Worker 0:    Batches: 1   Memory Usage: 48kB
                                     Worker 1:    Batches: 1   Memory Usage: 64kB
                                    -> Parallel Append (cost=0.00..10780.64
   rows=267259 width=40) (actual time=0.010..79.251 rows=213304 loops=3)
                                          -> Parallel Seq Scan on basilea_
   partitioned_1952 basilea_partitioned_3 (cost=0.00..129.59 rows=5167
   width=40) (actual time=0.010..3.176 rows=8784 loops=1)
   [....]
                                            ->Parallel Seq Scan on basilea_
   partitioned_2018 basilea_partitioned_69 (cost=0.00..128.41 rows=5153
   width=40) (actual time=0.004..2.671 rows=8760 loops=1)
                                            -> Parallel Seq Scan on basilea_
   partitioned_2021 basilea_partitioned_72 (cost=0.00..128.41 rows=5153
   width=40) (actual time=0.003..2.651 rows=8760 loops=1)
                                          -> Parallel Seq Scan on basilea_
   partitioned_default basilea_partitioned_75 (cost=0.00..21.10 rows=888
   width=40) (actual time=0.000..0.000 rows=0 loops=1)
                                          -> Parallel Seq Scan on basilea_
   partitioned_2023 basilea_partitioned_74 (cost=0.00..1.01 rows=1 width=40)
   (actual time=0.008..0.009 rows=1 loops=1)
    Planning Time: 0.698 ms

   Execution Time: 174.250 ms
   (97 rows)
....


Như có thể thấy, trước tiên PostgreSQL thực hiện một parallel sequential scan, sau đó thực hiện một parallel append để gộp toàn bộ dữ liệu lấy được từ các child table.

Bây giờ hãy thử thực hiện cùng thao tác nhưng chỉ lọc các năm trong khoảng từ 2021 đến 2022. Với table chưa được partition, chúng ta sẽ nhận được kết quả sau:

[source,console,role="transcript"]
....
   world_temperatures=# explain analyze select extract (year from insert_
   time) as year, avg(temperature) avg_temp from basilea where insert_time
   >='2021-01-01' and insert_time < '2023-01-01' group by 1 order by 2 desc
   limit 5;


   QUERY PLAN


   ------------------------------------------------------------
    Limit (cost=11498.05..11498.06 rows=5 width=64) (actual
   time=24.532..28.875 rows=2 loops=1)
      -> Sort (cost=11498.05..11544.43 rows=18554 width=64) (actual
   time=24.529..28.871 rows=2 loops=1)
              Sort Key: (avg(temperature)) DESC
              Sort Method: quicksort        Memory: 25kB
            -> Finalize HashAggregate (cost=10911.56..11189.87 rows=18554
   width=64) (actual time=24.467..28.859 rows=2 loops=1)
                     Group Key: (EXTRACT(year FROM insert_time))
                     Batches: 1     Memory Usage: 793kB
                  -> Gather (cost=9133.43..10795.60 rows=15462 width=64)
   (actual time=24.159..28.707 rows=6 loops=1)
                             Workers Planned: 2
                             Workers Launched: 2
                        -> Partial HashAggregate (cost=8133.43..8249.40
   rows=7731 width=64) (actual time=20.170..20.211 rows=2 loops=3)
                                    Group Key: EXTRACT(year FROM insert_time)
                                    Batches: 1     Memory Usage: 409kB
                                    Worker 0:     Batches: 1    Memory Usage: 409kB
                                    Worker 1:     Batches: 1    Memory Usage: 409kB
                              -> Parallel Seq Scan on basilea
   (cost=0.00..8094.78 rows=7731 width=40) (actual time=16.211..18.330
   rows=5840 loops=3)
                                    Filter: ((insert_time >= '2021-01-01
   00:00:00+00'::timestamp with time zone) AND (insert_time < '2023-01-01
   00:00:00+00'::timestamp with time zone))
                                       Rows Removed by Filter: 207464
    Planning Time: 0.248 ms
    Execution Time: 30.043 ms
   (20 rows)
....

.SQL
[source,sql]
....
EXPLAIN analyze SELECT extract (year FROM insert_
   time) AS year, avg(temperature) avg_temp FROM basilea WHERE insert_time
   >='2021-01-01' AND insert_time < '2023-01-01' GROUP BY 1 ORDER BY 2 DESC
   LIMIT 5;
....

.Output
[source,output]
....
   QUERY PLAN


   ------------------------------------------------------------
    Limit (cost=11498.05..11498.06 rows=5 width=64) (actual
   time=24.532..28.875 rows=2 loops=1)
      -> Sort (cost=11498.05..11544.43 rows=18554 width=64) (actual
   time=24.529..28.871 rows=2 loops=1)
              Sort Key: (avg(temperature)) DESC
              Sort Method: quicksort        Memory: 25kB
            -> Finalize HashAggregate (cost=10911.56..11189.87 rows=18554
   width=64) (actual time=24.467..28.859 rows=2 loops=1)
                     Group Key: (EXTRACT(year FROM insert_time))
                     Batches: 1     Memory Usage: 793kB
                  -> Gather (cost=9133.43..10795.60 rows=15462 width=64)
   (actual time=24.159..28.707 rows=6 loops=1)
                             Workers Planned: 2
                             Workers Launched: 2
                        -> Partial HashAggregate (cost=8133.43..8249.40
   rows=7731 width=64) (actual time=20.170..20.211 rows=2 loops=3)
                                    Group Key: EXTRACT(year FROM insert_time)
                                    Batches: 1     Memory Usage: 409kB
                                    Worker 0:     Batches: 1    Memory Usage: 409kB
                                    Worker 1:     Batches: 1    Memory Usage: 409kB
                              -> Parallel Seq Scan on basilea
   (cost=0.00..8094.78 rows=7731 width=40) (actual time=16.211..18.330
   rows=5840 loops=3)
                                    Filter: ((insert_time >= '2021-01-01
   00:00:00+00'::timestamp with time zone) AND (insert_time < '2023-01-01
   00:00:00+00'::timestamp with time zone))
                                       Rows Removed by Filter: 207464
    Planning Time: 0.248 ms
    Execution Time: 30.043 ms
   (20 rows)
....


Với partitioned table, kết quả như sau:

[source,console,role="transcript"]
....
   world_temperatures=# explain analyze select extract (year from insert_
   time) as year, avg(temperature) avg_temp from basilea_partitioned where
   insert_time >='2021-01-01' and insert_time < '2023-01-01' group by 1 order
   by 2 desc limit 5;


   QUERY PLAN


   ---------------------------------------------------------
    Limit (cost=618.10..618.11 rows=5 width=64) (actual time=15.205..15.208
   rows=2 loops=1)
      -> Sort (cost=618.10..618.60 rows=200 width=64) (actual
   time=15.203..15.205 rows=2 loops=1)
             Sort Key: (avg(basilea_partitioned.temperature)) DESC
             Sort Method: quicksort    Memory: 25kB
            -> HashAggregate (cost=611.78..614.78 rows=200 width=64)
   (actual time=15.190..15.194 rows=2 loops=1)
                   Group Key: (EXTRACT(year FROM basilea_partitioned.insert_
   time))
                   Batches: 1    Memory Usage: 40kB
                  -> Append (cost=0.00..524.19 rows=17517 width=40) (actual
   time=0.032..8.804 rows=17520 loops=1)
                        -> Seq Scan on basilea_partitioned_2021
   basilea_partitioned_1 (cost=0.00..217.30 rows=8758 width=40) (actual
   time=0.030..4.466 rows=8759 loops=1)
                              Filter: ((insert_time >= '2021-01-01
   00:00:00+00'::timestamp with time zone) AND (insert_time < '2023-01-01
   00:00:00+00'::timestamp with time zone))
                                 Rows Removed by Filter: 1
                        -> Seq Scan on basilea_partitioned_2022
   basilea_partitioned_2 (cost=0.00..218.30 rows=8758 width=40) (actual
   time=0.003..2.930 rows=8760 loops=1)
                              Filter: ((insert_time >= '2021-01-01
   00:00:00+00'::timestamp with time zone) AND (insert_time < '2023-01-01
   00:00:00+00'::timestamp with time zone))
                        -> Seq Scan on basilea_partitioned_2023 basilea_
   partitioned_3 (cost=0.00..1.02 rows=1 width=40) (actual time=0.006..0.006
   rows=1 loops=1)
                              Filter: ((insert_time >= '2021-01-01
   00:00:00+00'::timestamp with time zone) AND (insert_time < '2023-01-01
   00:00:00+00'::timestamp with time zone))
       Planning Time: 0.439 ms
       Execution Time: 15.311 ms
   (17 rows)
....

.SQL
[source,sql]
....
EXPLAIN analyze SELECT extract (year FROM insert_
   time) AS year, avg(temperature) avg_temp FROM basilea_partitioned WHERE
   insert_time >='2021-01-01' AND insert_time < '2023-01-01' GROUP BY 1 ORDER
   BY 2 DESC LIMIT 5;
....

.Output
[source,output]
....
   QUERY PLAN


   ---------------------------------------------------------
    Limit (cost=618.10..618.11 rows=5 width=64) (actual time=15.205..15.208
   rows=2 loops=1)
      -> Sort (cost=618.10..618.60 rows=200 width=64) (actual
   time=15.203..15.205 rows=2 loops=1)
             Sort Key: (avg(basilea_partitioned.temperature)) DESC
             Sort Method: quicksort    Memory: 25kB
            -> HashAggregate (cost=611.78..614.78 rows=200 width=64)
   (actual time=15.190..15.194 rows=2 loops=1)
                   Group Key: (EXTRACT(year FROM basilea_partitioned.insert_
   time))
                   Batches: 1    Memory Usage: 40kB
                  -> Append (cost=0.00..524.19 rows=17517 width=40) (actual
   time=0.032..8.804 rows=17520 loops=1)
                        -> Seq Scan on basilea_partitioned_2021
   basilea_partitioned_1 (cost=0.00..217.30 rows=8758 width=40) (actual
   time=0.030..4.466 rows=8759 loops=1)
                              Filter: ((insert_time >= '2021-01-01
   00:00:00+00'::timestamp with time zone) AND (insert_time < '2023-01-01
   00:00:00+00'::timestamp with time zone))
                                 Rows Removed by Filter: 1
                        -> Seq Scan on basilea_partitioned_2022
   basilea_partitioned_2 (cost=0.00..218.30 rows=8758 width=40) (actual
   time=0.003..2.930 rows=8760 loops=1)
                              Filter: ((insert_time >= '2021-01-01
   00:00:00+00'::timestamp with time zone) AND (insert_time < '2023-01-01
   00:00:00+00'::timestamp with time zone))
                        -> Seq Scan on basilea_partitioned_2023 basilea_
   partitioned_3 (cost=0.00..1.02 rows=1 width=40) (actual time=0.006..0.006
   rows=1 loops=1)
                              Filter: ((insert_time >= '2021-01-01
   00:00:00+00'::timestamp with time zone) AND (insert_time < '2023-01-01
   00:00:00+00'::timestamp with time zone))
       Planning Time: 0.439 ms
       Execution Time: 15.311 ms
   (17 rows)
....


Điều đầu tiên có thể thấy là PostgreSQL kiểm tra ít child table hơn khi có một `where` clause trên column được dùng để partition; parameter `constraint_exclusion` trong `postgresql.conf` cho phép điều này:

[source,console,role="transcript"]
....
   world_temperatures=# select * from pg_settings where name ='constraint_
   exclusion';
   -[ RECORD 1 ]-
   name               | constraint_exclusion
   setting            | partition
   unit               |


   category           | Query Tuning / Other Planner Options
   short_desc         | Enables the planner to use constraints to optimize
   queries.
   extra_desc      | Table scans will be skipped if their constraints
   guarantee that no rows match the query.
   context            | user
   vartype            | enum
   source             | default
   min_val            |


   max_val            |

   enumvals            | {partition,on,off}
   boot_val            | partition
   reset_val           | partition
   sourcefile          |


   sourceline          |
   pending_restart | f
....

.SQL
[source,sql]
....
SELECT *
FROM pg_settings
WHERE name = 'constraint_ exclusion';
....

.Output
[source,output]
....
   -[ RECORD 1 ]-
   name               | constraint_exclusion
   setting            | partition
   unit               |


   category           | Query Tuning / Other Planner Options
   short_desc         | Enables the planner to use constraints to optimize
   queries.
   extra_desc      | Table scans will be skipped if their constraints
   guarantee that no rows match the query.
   context            | user
   vartype            | enum
   source             | default
   min_val            |


   max_val            |

   enumvals            | {partition,on,off}
   boot_val            | partition
   reset_val           | partition
   sourcefile          |


   sourceline          |
   pending_restart | f
....


Parameter này cho phép query optimizer loại một số child table khỏi quá trình tìm kiếm. Như có thể thấy trong đoạn code trên, các giá trị có thể có của parameter `constraint_exclusion` là:

* `on`: Khi đặt giá trị này, PostgreSQL kiểm tra tất cả các table.
* `off`: Khi đặt giá trị này, PostgreSQL không kiểm tra bất kỳ constraint nào.
* `partition`: Với giá trị này, PostgreSQL kiểm tra constraint của các subquery `UNION ALL` và chỉ kiểm tra các child table của inheritance. `partition` là thiết lập mặc định.

Để biết thêm thông tin, hãy xem https://www.postgresql.org/docs/current/runtime-config-query.html#GUC-CONSTRAINT-EXCLUSION.
