= Sử dụng `limit` và `offset`

`limit` clause cho phép PostgreSQL giới hạn số row trong kết quả của query, còn `offset` clause dùng để bỏ qua một số row cụ thể trong kết quả đó.

`limit` và `offset` được dùng để trả về một phần dữ liệu từ result set do query tạo ra; `limit` clause dùng để giới hạn số row trong output, còn `offset` clause chỉ định vị trí trong result set mà từ đó PostgreSQL bắt đầu trả về dữ liệu.

Có thể sử dụng chúng độc lập hoặc kết hợp với nhau.

Bây giờ, hãy thử dùng `limit` và `offset` với các query sau:

[source,console,role="transcript"]
....
forumdb=> select * from categories order by pk limit 1;
 pk |    title    |            description
 ----+----------+------------------------------
  1 | Database    | Database related discussions
(1 row)
....

.SQL
[source,sql]
....
SELECT *
FROM categories
ORDER BY pk
LIMIT 1;
....

.Output
[source,output]
....
 pk |    title    |            description
 ----+----------+------------------------------
  1 | Database    | Database related discussions
(1 row)
....


Query trên chỉ trả về row đầu tiên được insert; đó là vì column `pk` có kiểu integer và giá trị mặc định của nó luôn được tạo dưới dạng identity.

Nếu muốn xem hai row đầu tiên được insert, chúng ta phải thực hiện query sau:

[source,console,role="transcript"]
....
forumdb=> select * from categories order by pk limit 2;
 pk |    title    |            description
 ----+----------+------------------------------
  1 | Database    | Database related discussions
  2 | Unix        | Unix and Linux discussions
(2 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM categories
ORDER BY pk
LIMIT 2;
....

.Output
[source,output]
....
 pk |    title    |            description
 ----+----------+------------------------------
  1 | Database    | Database related discussions
  2 | Unix        | Unix and Linux discussions
(2 rows)
....


Nếu chỉ muốn xem row thứ hai được insert, chúng ta phải thực hiện query sau:

[source,console,role="transcript"]
....
forumdb=> select * from categories order by pk offset 1 limit 1;
 pk | title |            description
----+-------+----------------------------
  2 | Unix  | Unix and Linux discussions
(1 row)
....

.SQL
[source,sql]
....
SELECT *
FROM categories
ORDER BY pk
OFFSET 1
LIMIT 1;
....

.Output
[source,output]
....
 pk | title |            description
----+-------+----------------------------
  2 | Unix  | Unix and Linux discussions
(1 row)
....


`offset` và `limit` rất hữu ích khi muốn trả về dữ liệu theo từng trang.

Một công dụng hữu ích khác của `limit` là tạo table mới từ table hiện có. Ví dụ, nếu muốn tạo table `new_categories` dựa trên table `categories`, chúng ta phải thực thi statement sau:

[source,console,role="transcript"]
....
forumdb=> create table new_categories as select * from categories limit 0;
SELECT 0
....

.SQL
[source,sql]
....
CREATE TABLE new_categories AS SELECT * FROM categories LIMIT 0;
....

.Output
[source,output]
....
SELECT 0
....


Statement này chỉ sao chép cấu trúc dữ liệu của table `categories` sang table `new_categories`.

`SELECT 0` có nghĩa là không có dữ liệu nào được sao chép vào table `new_categories`; chỉ có cấu trúc dữ liệu được sao chép, như minh họa dưới đây:

[source,console,role="transcript"]
....
forumdb=> \d new_categories
               Table "forum.new_categories"
  Column     |   Type     | Collation | Nullable | Default
-------------+---------+-----------+----------+---------
 pk           | integer |               |            |
 title        | text       |            |            |
 description | text       |            |            |
....

.SQL
[source,sql]
....
\d new_categories
....

.Output
[source,output]
....
               Table "forum.new_categories"
  Column     |   Type     | Collation | Nullable | Default
-------------+---------+-----------+----------+---------
 pk           | integer |               |            |
 title        | text       |            |            |
 description | text       |            |            |
....
