= Yêu cầu kỹ thuật

Trong GitHub repository của Learn PostgreSQL, bạn có thể tìm thấy ba Docker image:

* `chapter17_streaming`: asynchronous replication giữa primary và replica. Khởi động container bằng command sau, rồi chạy command replica bên dưới để sử dụng replica container:

[source,text]
....
  chapter_17$ bash run-pg-docker.sh chapter17_streaming
....

  Sau đó, chạy:

[source,text]
....
  chapter_17$ bash run-pg-docker_replica.sh chapter17_streaming
....

* `chapter17_synchronous`: synchronous replication giữa primary và replica. Khởi động container bằng command sau, rồi chạy command replica bên dưới để sử dụng replica container:

[source,text]
....
  chapter_17$ bash run-pg-docker.sh chapter17_synchronous
....

  Sau đó, chạy:

[source,text]
....
  chapter_17$ bash run-pg-docker_replica.sh chapter17_synchronous
....

* `chapter17_delayed`: primary/replica với delayed replication. Khởi động container bằng command sau, rồi chạy command replica bên dưới để sử dụng replica container:

[source,text]
....
  chapter_17$ bash run-pg-docker.sh chapter17_delayed
....

  Sau đó, chạy:

[source,text]
....
  chapter_17$ bash run-pg-docker_replica.sh chapter17_delayed
....

Khi thoát khỏi primary container, tất cả replica container cũng sẽ dừng.

Trong chương này, chúng ta sẽ đề cập đến các chủ đề sau:

* Khám phá các khái niệm cơ bản về replication
* Quản lý streaming replication
