= Tạo extension của riêng bạn

Trong phần này, chúng ta sẽ xây dựng một extension từ đầu để bạn hiểu rõ hơn extension được cấu thành như thế nào. Mục tiêu là giúp bạn biết cách chuyển ngay cả những script SQL của riêng mình thành một extension, cùng với toàn bộ lợi ích về khả năng quản lý mà extension mang lại.

== Định nghĩa extension mẫu

Để minh họa cách xây dựng extension của riêng bạn, chúng ta sẽ tạo một tập hợp chức năng đơn giản cho database `forum`, bổ sung một số tính năng. Cụ thể, chúng ta sẽ định nghĩa một extension có tên `tagext`, cung cấp một utility function nhận một tag cụ thể trong table `tag` và trả về full path tới tag đó, cùng với toàn bộ ancestor của nó.

Ví dụ, tag `Linux` là con của tag `Operating Systems`, vì vậy path tới tag `Linux` là `Operating System > Linux`.

Cụ thể, chúng ta muốn extension cung cấp một function có tên `tag_path`; khi nhận một tag, function này trả về tag path như trong ví dụ sau:

[source,console,role="transcript"]
....
   forumdb=> SELECT tag_path( 'Kubuntu' );
                           tag_path
   ----------------------------------------------
      Operating Systems > Linux > Ubuntu > Kubuntu
   (1 row)
....

.SQL
[source,sql]
....
SELECT tag_path('Kubuntu');
....

.Output
[source,output]
....
                           tag_path
   ----------------------------------------------
      Operating Systems > Linux > Ubuntu > Kubuntu
   (1 row)
....


Trong các phần tiếp theo, bạn sẽ thấy cách đạt được kết quả này bằng việc triển khai extension mẫu. Tất cả file cần thiết đều có trong repository mã nguồn của cuốn sách.

== Tạo các file của extension

Trước tiên, hãy bắt đầu với control file, nơi chúng ta khai báo một số thông tin cơ bản về extension. Tạo file có tên `tagext.control` và đặt vào một thư mục, chẳng hạn `/src/tagext`. File này có nội dung như sau:

[source,text]
....
   comment = 'Tag Programming Example Extension'
   default_version = '1.0'
   superuser           = false
   relocatable         = true
....

[quote]
____
Trong Docker image được dùng cho các ví dụ của chương này, bạn sẽ tìm thấy các file của extension trong thư mục `/src/tagext` và có thể cài đặt extension bằng cách chuyển vào thư mục đó.

____
Control file này chứa một comment mô tả extension cho các administrator khác, chỉ định `default_version`, tức version sẽ được cài đặt nếu người dùng không chỉ định version nào, đồng thời quy định rằng bất kỳ người dùng nào cũng có thể cài đặt extension này (`superuser = false`) và extension có thể được chuyển sang schema bất kỳ do người dùng chọn (`relocatable = true`).

Tiếp theo là Makefile, file dùng để build và cài đặt extension:

[source,text]
....
   EXTENSION = tagext
   DATA = tagext--1.0.sql


   PG_CONFIG = pg_config
....

[source,text]
....
   PGXS := $(shell $(PG_CONFIG) --pgxs)
   include $(PGXS)
....

Makefile này rất đơn giản và có thể dùng làm khung mẫu cho các Makefile của extension khác. Cụ thể, chúng ta khai báo tên extension được Makefile này quản lý và file dùng để tạo nội dung của extension. File đó được chỉ định trong biến `DATA`, nên hệ thống sẽ sử dụng file `tagext--1.0.sql` để tạo các object mà extension cung cấp.

Các dòng cuối khai báo việc sử dụng hạ tầng build PGXS. Cụ thể, chúng được dùng để include Makefile cơ sở của PGXS, với đường dẫn được xác định từ output của command `pg_config`.

Khi đã có toàn bộ hạ tầng, chúng ta có thể định nghĩa nội dung của extension. Vì vậy, file `tagext--1.0.sql` chứa định nghĩa một function (xem *Chương 7, Lập trình phía server*) nhận một tag cụ thể và trả về biểu diễn dạng text của tag path cùng toàn bộ ancestor của nó:

[source,console,role="transcript"]
....
   CREATE OR REPLACE FUNCTION tag_path( tag_to_search text )
   RETURNS TEXT
   AS $CODE$
   DECLARE
      tag_path text;
      current_parent_pk int;
   BEGIN


      tag_path = tag_to_search;


      SELECT parent
      INTO      current_parent_pk
      FROM      tags
      WHERE     tag = tag_to_search;


      -- here we must loop
      WHILE current_parent_pk IS NOT NULL LOOP
             SELECT parent, tag || ' > ' || tag_path
             INTO    current_parent_pk, tag_path
             FROM    tags
             WHERE   pk = current_parent_pk;
      END LOOP;


      RETURN tag_path;
   END
   $CODE$
   LANGUAGE plpgsql;
....

.Command
[source,bash]
....
   CREATE OR REPLACE FUNCTION tag_path( tag_to_search text )
   RETURNS TEXT
   AS $CODE$
   DECLARE
      tag_path text;
      current_parent_pk int;
   BEGIN


      tag_path = tag_to_search;


      SELECT parent
      INTO      current_parent_pk
      FROM      tags
      WHERE     tag = tag_to_search;


      -- here we must loop
      WHILE current_parent_pk IS NOT NULL LOOP
             SELECT parent, tag || ' > ' || tag_path
             INTO    current_parent_pk, tag_path
             FROM    tags
             WHERE   pk = current_parent_pk;
      END LOOP;


      RETURN tag_path;
   END
CODE$
....

.Output
[source,output]
....
   LANGUAGE plpgsql;
....


Function này nhận một tag làm argument, sau đó query table `tags` để lấy primary key của parent rồi lặp qua từng tag cha. Ở mỗi vòng lặp, tên của tag cha được thêm vào giá trị text `tag_path`, để kết quả có dạng `parent 1 > parent 2 > child`.

Khi tất cả file đã sẵn sàng, ta có cấu trúc như sau, gồm Makefile, control file và file chứa nội dung extension:

[source,console,role="transcript"]
....
   $ ls -1 /src/tagext
   Makefile
   tagext--1.0.sql
   tagext.control
....

.Command
[source,bash]
....
ls -1 /src/tagext
....

.Output
[source,output]
....
   Makefile
   tagext--1.0.sql
   tagext.control
....


== Cài đặt extension

Khi đã có đủ các thành phần, bạn có thể dùng Makefile để cài đặt (triển khai) extension vào cluster. Vì extension sẽ được cài đặt vào các thư mục PostgreSQL, bạn có thể cần dùng một người dùng có đặc quyền để cài đặt extension:

[source,console,role="transcript"]
....
   $ sudo make install
....

.Command
[source,bash]
....
sudo make install
....


Bây giờ, bạn có thể cài đặt extension trong database `forumdb` bằng `CREATE EXTENSION`, rồi thử thực thi function do extension định nghĩa:

[source,console,role="transcript"]
....
   forumdb=> CREATE EXTENSION tagext;
   CREATE EXTENSION


                                                         List of installed extensions
          Name             | Version |      Schema     |
   Description


   --------------------+---------+------------+------------------------------
   --------------------------
   ----------------
   pg_stat_statements | 1.10           | public         | track planning and execution
   statistics of all SQL stat
   ements executed
   plpgsql                 | 1.0       | pg_catalog | PL/pgSQL procedural language
   tagext                  | 1.0       | forum          | Tag Programming Example
   Extension


   forumdb=> SELECT tag_path( 'Kubuntu' );
                           tag_path
   ----------------------------------------------
    Operating Systems > Linux > Ubuntu > Kubuntu
   (1 row)
....

.SQL
[source,sql]
....
CREATE EXTENSION tagext;
SELECT tag_path('Kubuntu');
....

.Output
[source,output]
....
   CREATE EXTENSION


                                                         List of installed extensions
          Name             | Version |      Schema     |
   Description


   --------------------+---------+------------+------------------------------
   --------------------------
   ----------------
   pg_stat_statements | 1.10           | public         | track planning and execution
   statistics of all SQL stat
   ements executed
   plpgsql                 | 1.0       | pg_catalog | PL/pgSQL procedural language
   tagext                  | 1.0       | forum          | Tag Programming Example
   Extension


                           tag_path
   ----------------------------------------------
    Operating Systems > Linux > Ubuntu > Kubuntu
   (1 row)
....


Function này hoạt động và có thể xây dựng một tag tree hoặc path cho tag được chỉ định cùng toàn bộ ancestor của nó; đồng thời, PostgreSQL cũng cho biết extension đang ở version 1.0.

== Tạo bản nâng cấp cho extension

Giả sử chúng ta muốn mở rộng function của extension để người dùng có thể chỉ định dấu phân cách tag trong path output. Chúng ta có thể tạo một version mới của function, xóa version cũ và cho phép người dùng nâng cấp extension bằng nội dung mới.

Trước tiên, hãy tạo bản nâng cấp cho nội dung của extension, tức function mới mà extension cung cấp. Tạo file có tên `tagext--1.0--1.1.sql` và đặt nội dung sau vào đó:

[source,console,role="transcript"]
....
   DROP FUNCTION IF EXISTS tag_path( text );


   CREATE OR REPLACE FUNCTION tag_path( tag_to_search text,
                                                 delimiter text DEFAULT ' > ' )
   RETURNS TEXT
   AS $CODE$
   DECLARE
      tag_path text;
      current_parent_pk int;
   BEGIN


      tag_path = tag_to_search;


      SELECT parent
      INTO    current_parent_pk
      FROM    tags
      WHERE   tag = tag_to_search;


      -- here we must loop
      WHILE current_parent_pk IS NOT NULL LOOP
           SELECT parent, tag || delimiter || tag_path
           INTO     current_parent_pk, tag_path
           FROM     tags
           WHERE    pk = current_parent_pk;
      END LOOP;


      RETURN tag_path;
   END
   $CODE$
   LANGUAGE plpgsql;
....

.Command
[source,bash]
....
   DROP FUNCTION IF EXISTS tag_path( text );


   CREATE OR REPLACE FUNCTION tag_path( tag_to_search text,
                                                 delimiter text DEFAULT ' > ' )
   RETURNS TEXT
   AS $CODE$
   DECLARE
      tag_path text;
      current_parent_pk int;
   BEGIN


      tag_path = tag_to_search;


      SELECT parent
      INTO    current_parent_pk
      FROM    tags
      WHERE   tag = tag_to_search;


      -- here we must loop
      WHILE current_parent_pk IS NOT NULL LOOP
           SELECT parent, tag || delimiter || tag_path
           INTO     current_parent_pk, tag_path
           FROM     tags
           WHERE    pk = current_parent_pk;
      END LOOP;


      RETURN tag_path;
   END
CODE$
....

.Output
[source,output]
....
   LANGUAGE plpgsql;
....


File này trước tiên xóa version cũ của function (nếu version đó tồn tại và đã được cài đặt bởi version trước của extension). Sau đó, nó tạo một function mới có thêm một parameter tùy chọn. Function này thực hiện chính xác công việc như version trước, nhưng lần này sử dụng biến `delimiter` để phân tách các tag.

Vì đã thêm một file mới vào extension, chúng ta cần thông báo cho Makefile về file đó. Do vậy, phải thêm file mới vào biến `DATA` để Makefile có nội dung như sau:

[source,text]
....
   EXTENSION = tagext
   DATA = tagext--1.0.sql tagext--1.0--1.1.sql


   PG_CONFIG = pg_config
   PGXS := $(shell $(PG_CONFIG) --pgxs)
   include $(PGXS)
....

== Nâng cấp extension

Với Makefile mới và file `tagext--1.0--1.1.sql`, cấu trúc file trên disk sẽ như sau:

[source,console,role="transcript"]
....
   $ ls -1 /src/tagext
   Makefile
   tagext--1.0--1.1.sql
   tagext--1.0.sql
   tagext.control
....

.Command
[source,bash]
....
ls -1 /src/tagext
....

.Output
[source,output]
....
   Makefile
   tagext--1.0--1.1.sql
   tagext--1.0.sql
   tagext.control
....


Do đó, bây giờ có thể cài đặt (triển khai) extension vào cluster bằng cách chạy lại command install:

[source,console,role="transcript"]
....
   $ make install
   /bin/mkdir -p '/usr/local/share/postgresql/extension'
   /bin/mkdir -p '/usr/local/share/postgresql/extension'
   /usr/bin/install -c -m 644 .//tagext.control '/usr/local/share/postgresql/
   extension/'
   /usr/bin/install -c -m 644 .//tagext--1.0.sql .//tagext--1.0--1.1.sql                   '/
   usr/local/share/postgresql/extension/'
....

.Command
[source,bash]
....
make install
....

.Output
[source,output]
....
   /bin/mkdir -p '/usr/local/share/postgresql/extension'
   /bin/mkdir -p '/usr/local/share/postgresql/extension'
   /usr/bin/install -c -m 644 .//tagext.control '/usr/local/share/postgresql/
   extension/'
   /usr/bin/install -c -m 644 .//tagext--1.0.sql .//tagext--1.0--1.1.sql                   '/
   usr/local/share/postgresql/extension/'
....


Trong database, bạn có thể nâng cấp extension bằng `ALTER EXTENSION`:

[source,console,role="transcript"]
....
   forumdb=> ALTER EXTENSION tagext UPDATE TO '1.1';
   ALTER EXTENSION


   forumdb=> \dx tagext
                        List of installed extensions
      Name   | Version | Schema |                   Description
    --------+---------+--------+-----------------------------------
     tagext | 1.1         | public | Tag Programming Example Extension
   (1 row)
....

.SQL
[source,sql]
....
ALTER EXTENSION tagext UPDATE TO '1.1';
\dx tagext
....

.Output
[source,output]
....
   ALTER EXTENSION


                        List of installed extensions
      Name   | Version | Schema |                   Description
    --------+---------+--------+-----------------------------------
     tagext | 1.1         | public | Tag Programming Example Extension
   (1 row)
....


Như bạn thấy, version của extension hiện là 1.1, vì vậy có thể gọi function `tag_path` có hoặc không có đối số mới:

[source,console,role="transcript"]
....
   forumdb=> SELECT tag_path( 'Kubuntu' );
                          tag_path
   ----------------------------------------------
       Operating Systems > Linux > Ubuntu > Kubuntu
   (1 row)


   forumdb=> SELECT tag_path( 'Kubuntu', ' --> ' );
                               tag_path
   ----------------------------------------------------
       Operating Systems --> Linux --> Ubuntu --> Kubuntu
   (1 row)
....

.SQL
[source,sql]
....
SELECT tag_path('Kubuntu');
SELECT tag_path('Kubuntu', ' --> ');
....

.Output
[source,output]
....
                          tag_path
   ----------------------------------------------
       Operating Systems > Linux > Ubuntu > Kubuntu
   (1 row)


                               tag_path
   ----------------------------------------------------
       Operating Systems --> Linux --> Ubuntu --> Kubuntu
   (1 row)
....


Bây giờ bạn đã biết cách quản lý toàn bộ vòng đời của extension.
