= Savepoint

Một transaction là một khối công việc phải thành công hoặc thất bại toàn bộ. Savepoint cho phép chia một transaction thành các khối nhỏ hơn có thể rollback độc lập. Nhờ savepoint, bạn có thể chia một transaction lớn (chứa nhiều statement) thành các phần nhỏ hơn, để một phần của transaction đó thất bại mà không khiến toàn bộ transaction thất bại. PostgreSQL không hỗ trợ transaction nesting, nên bạn không thể phát hành một nhóm statement `BEGIN` hoặc `COMMIT`/`ROLLBACK` lồng nhau. Tuy nhiên, savepoint cho phép PostgreSQL mô phỏng việc lồng các transaction block.

Savepoint được đánh dấu bằng một tên dễ nhớ; bạn có thể dùng tên đó để commit hoặc rollback. Tên phải là duy nhất trong transaction; nếu lặp lại cùng một tên, các savepoint trước đó có cùng tên sẽ bị loại bỏ. Hãy xem một ví dụ:

[source,console,role="transcript"]
....
   forumdb=> BEGIN;
   BEGIN
   forumdb=> INSERT INTO tags( tag ) VALUES ( 'Eclipse IDE' );
   INSERT 0 1
   forumdb=> SAVEPOINT other_tags;
   SAVEPOINT
   forumdb=> INSERT INTO tags( tag ) VALUES ( 'Netbeans IDE' );
   INSERT 0 1
   forumdb=> INSERT INTO tags( tag ) VALUES ( 'Comma IDE' );
   INSERT 0 1
   forumdb=> ROLLBACK TO SAVEPOINT other_tags;
....

.SQL
[source,sql]
....
BEGIN;
INSERT INTO tags (tag)
VALUES ('Eclipse IDE');
SAVEPOINT other_tags;
INSERT INTO tags (tag)
VALUES ('Netbeans IDE');
INSERT INTO tags (tag)
VALUES ('Comma IDE');
ROLLBACK TO SAVEPOINT other_tags;
....

.Output
[source,output]
....
   BEGIN
   INSERT 0 1
   SAVEPOINT
   INSERT 0 1
   INSERT 0 1
....


[source,console,role="transcript"]
....
ROLLBACK
forumdb=> INSERT INTO tags( tag ) VALUES ( 'IntelliJIdea IDE' );
INSERT 0 1
forumdb=> COMMIT;
COMMIT


forumdb=> SELECT tag FROM tags WHERE tag like '%IDE';
         tag
------------------
   Eclipse IDE
   IntelliJIdea IDE
(2 rows)
....

.SQL
[source,sql]
....
ROLLBACK
INSERT INTO tags (tag) VALUES ('IntelliJIdea IDE');
COMMIT;
SELECT tag
FROM tags
WHERE tag like '%IDE';
....

.Output
[source,output]
....
INSERT 0 1
COMMIT


         tag
------------------
   Eclipse IDE
   IntelliJIdea IDE
(2 rows)
....


Trong transaction trước, statement đầu tiên không thuộc savepoint nào nên tuân theo vòng đời của explicit transaction. Sau khi savepoint `other_tags` được tạo, mọi statement tiếp theo tuân theo vòng đời của savepoint đó; vì vậy, khi phát hành `ROLLBACK TO SAVEPOINT`, các statement trong savepoint sẽ bị loại bỏ. Các statement sau đó thuộc về explicit transaction, nên tuân theo vòng đời của transaction đó. Kết quả cuối cùng là mọi thứ được thực thi bên ngoài savepoint đều được lưu trong table.

Sau khi đã định nghĩa một savepoint, bạn cũng có thể đổi ý và release savepoint đó để các statement trong savepoint tuân theo cùng vòng đời với transaction chính. Đây là một ví dụ:

[source,console,role="transcript"]
....
   forumdb=> BEGIN;
   BEGIN
   forumdb=> SAVEPOINT editors;
   SAVEPOINT
   forumdb=> INSERT INTO tags( tag ) VALUES ( 'Emacs Editor' );
   INSERT 0 1
   forumdb=> INSERT INTO tags( tag ) VALUES ( 'Vi Editor' );
   INSERT 0 1
   forumdb=> RELEASE SAVEPOINT editors;
   RELEASE
   forumdb=> INSERT INTO tags( tag ) VALUES ( 'Atom Editor' );
   INSERT 0 1
   forumdb=> COMMIT;
   COMMIT

   forumdb=> SELECT tag FROM tags WHERE tag LIKE '%Editor';
             tag
   --------------
     Emacs Editor
     Vi Editor
     Atom Editor
   (3 rows)
....

.SQL
[source,sql]
....
BEGIN;
SAVEPOINT editors;
INSERT INTO tags (tag)
VALUES ('Emacs Editor');
INSERT INTO tags (tag)
VALUES ('Vi Editor');
RELEASE SAVEPOINT editors;
INSERT INTO tags (tag)
VALUES ('Atom Editor');
COMMIT;
SELECT tag
FROM tags
WHERE tag LIKE '%Editor';
....

.Output
[source,output]
....
   BEGIN
   SAVEPOINT
   INSERT 0 1
   INSERT 0 1
   RELEASE
   INSERT 0 1
   COMMIT

             tag
   --------------
     Emacs Editor
     Vi Editor
     Atom Editor
   (3 rows)
....


Khi phát hành `RELEASE SAVEPOINT`, savepoint gần như biến mất, nên hai statement `INSERT` tuân theo vòng đời của transaction chính. Nói cách khác, kết quả giống như savepoint chưa từng được định nghĩa.

Trong một transaction, bạn có thể có nhiều savepoint, nhưng khi rollback về một savepoint, tất cả savepoint được tạo sau nó cũng sẽ bị rollback:

[source,console,role="transcript"]
....
   forumdb=> BEGIN;
   BEGIN
   forumdb=> SAVEPOINT perl;
   SAVEPOINT
   forumdb=> INSERT INTO tags( tag ) VALUES ( 'Rakudo Compiler' );
   INSERT 0 1
   forumdb=> SAVEPOINT gcc;
   SAVEPOINT
   forumdb=> INSERT INTO tags( tag ) VALUES ( 'Gnu C Compiler' );
   INSERT 0 1
   forumdb=> ROLLBACK TO SAVEPOINT perl;
   ROLLBACK
   forumdb=> COMMIT;
   COMMIT


   forumdb=> SELECT tag FROM tags WHERE tag LIKE '%Compiler';
     tag
   -----
   (0 rows)
....

.SQL
[source,sql]
....
BEGIN;
SAVEPOINT perl;
INSERT INTO tags (tag)
VALUES ('Rakudo Compiler');
SAVEPOINT gcc;
INSERT INTO tags (tag)
VALUES ('Gnu C Compiler');
ROLLBACK TO SAVEPOINT perl;
COMMIT;
SELECT tag
FROM tags
WHERE tag LIKE '%Compiler';
....

.Output
[source,output]
....
   BEGIN
   SAVEPOINT
   INSERT 0 1
   SAVEPOINT
   INSERT 0 1
   ROLLBACK
   COMMIT


     tag
   -----
   (0 rows)
....


Như bạn có thể thấy, ngay cả khi transaction đã thực thi `COMMIT`, mọi thứ được thực hiện sau savepoint `perl` cũng đã bị rollback; perl là savepoint mà transaction đã rollback về.

Nói cách khác, rollback về một savepoint nghĩa là rollback mọi thứ được thực hiện sau khi savepoint đó được tạo.

Transaction có thể dẫn đến một tình huống mà cluster không thể tiếp tục xử lý. Những tình huống này được gọi là deadlock và sẽ được mô tả trong phần tiếp theo.
