= Tóm tắt

Hy vọng chương này mang đến nhiều ý tưởng thú vị cho developer và DBA. Trong chương này, chúng ta đã tìm hiểu về các query phức tạp; sau đó xem xét statement `SELECT` và cách sử dụng các clause `LIKE`, `ILIKE`, `DISTINCT`, `OFFSET`, `LIMIT`, `IN` và `NOT IN`. Tiếp theo, chúng ta bắt đầu tìm hiểu về aggregate thông qua các clause `GROUP BY` và `HAVING`, đồng thời giới thiệu một số aggregate function như `SUM()`, `COUNT()`, `AVG()`, `MIN()` và `MAX()`.

Sau đó, chúng ta đã đi sâu vào subquery và join. Một nhóm chủ đề rất thú vị khác được đề cập trong chương này là các query `UNION`, `EXCEPT` và `INTERSECT`. Cuối cùng, khi xem xét các tùy chọn nâng cao của các statement `INSERT`, `DELETE`, `UPDATE` và `MERGE`, đồng thời đề cập đến CTE, chúng ta đã thấy sức mạnh của ngôn ngữ SQL mà PostgreSQL cung cấp.

Liên quan đến khái niệm aggregate, trong chương tiếp theo, chúng ta sẽ tìm hiểu một cách mới để tạo aggregate bằng window function. Với window function, chúng ta sẽ thấy rằng có thể tạo tất cả aggregate và aggregate function được mô tả trong chương này, đồng thời vẫn có tùy chọn tạo các aggregate function mới.
