= File pgbackrest.conf

Sau khi sửa `postgresql.conf`, hãy tiếp tục sửa file `pgbackrest.conf` trên PostgreSQL server. Lưu ý rằng PostgreSQL server có `ip= 192.168.122.170`, còn IP của disaster recovery server là `192.168.122.170`. Hãy chỉnh sửa file `/etc/pgbackrest.conf`, xóa nội dung hiện có rồi thêm các dòng sau:

[source,text]
....
[global]
backup-host=192.168.122.120
backup-user=postgres
backup-ssh-port=22
log-level-console=info
log-level-file=info

[pg1]
pg1-path = /var/lib/postgresql/16/main
pg1-port = 5432
....

Tương tự repository configuration, file này gồm một global section và một section cho mỗi stanza.

Trong global section, có các option sau:

* `backup-host`: Host của repository.
* `backup-user`: User được sử dụng để thực hiện backup.
* `backup-ssh-port`: SSH port.
* `log-level-console=info` và `log-level-file=info`: Như đã nêu ở section trước.

Trong stanza section, có các option sau:

* `pg1-path = /var/lib/postgresql/16/main`: Path trên PostgreSQL cluster nơi lưu dữ liệu. Có thể tìm thấy path này trong parameter `data_directory` của file `postgresql.conf`.
* `pg1-port = 5432`: Listen port của remote PostgreSQL server.
