= Disaster recovery với `pgbackrest`

Trong Chapter 18, Logical Replication, chúng ta đã đề cập đến disaster recovery và PITR, đồng thời xem cách thực hiện các tác vụ này bằng chương trình. Trong thực tế, DBA thường phải quản lý nhiều PostgreSQL server, vì vậy các công cụ giúp đơn giản hóa công việc rất hữu ích. Hệ sinh thái open source cung cấp nhiều giải pháp để xử lý disaster recovery dễ dàng hơn. Một số công cụ được liệt kê dưới đây:

* WAL-E
* pgbarman
* OmniPITR
Còn nhiều công cụ khác; tại https://wiki.postgresql.org/wiki/Binary_Replication_Tools, bạn có thể xem một bản so sánh khá tốt về tất cả các công cụ này.

Trong phần này, chúng ta sẽ giới thiệu ngắn gọn về `pgbackrest`. Đây là một trong những công cụ được sử dụng phổ biến nhất cho disaster recovery vì cho phép dễ dàng scale trên nhiều core, đồng thời lưu dữ liệu vào các bucket dưới dạng nén và mã hóa. `pgbackrest` là công cụ dành cho PostgreSQL disaster recovery và PITR, được thiết kế cho các server có tải lớn. URL chính thức là https://pgbackrest.org/.

Dưới đây là một số tính năng của công cụ này:

* Hỗ trợ backup và restore song song.
* Có thể tạo full base backup, incremental backup hoặc differential backup.
* Có thể chọn thực hiện thao tác local hoặc remote.
* Có thể thiết lập retention policy cho backup và archive expiration.
* Hỗ trợ tiếp tục backup bị gián đoạn.
* Hỗ trợ streaming compression và checksum.
* Khi restore, có thể sử dụng delta restore.
* Có thể sử dụng WAL archiving song song.
* Hỗ trợ tablespace và link.
* Hỗ trợ mã hóa dữ liệu.
* Hỗ trợ SFTP để lưu repository.
* Hỗ trợ lưu trữ bằng object store trên S3, GCP và Azure.

== Các khái niệm cơ bản

Công cụ `pgbackrest` sử dụng khái niệm stanza và có thể dùng một local repository hoặc một external repository:

* Stanza là configuration mô tả một remote server dùng cho backup. Đây là tập hợp các target cần backup. Một stanza configuration có thể chứa nhiều server; khi đó, server đầu tiên (`pg1`) là master, còn các server còn lại là standby server.
* Repository là nơi lưu trữ local hoặc remote (SSH) dùng để lưu backup; repository có thể được mã hóa. Một repository có thể chứa nhiều definition, nhưng hiện tại chỉ definition đầu tiên (`repo1`) được hỗ trợ.
* Cần trao đổi public key giữa các user sử dụng `pgbackrest`. Cách đơn giản nhất là trao đổi public key giữa Postgres user của PostgreSQL server và Postgres user trên server lưu repository `pgbackrest`.

== Thiết lập môi trường

Phần này không sử dụng Docker container. Vì vậy, trước khi bắt đầu và kiểm thử `pgbackrest`, hãy xác định các yêu cầu cần thiết. Chúng ta cần:

* Một PostgreSQL server đang chạy.
* Một server để cài đặt và cấu hình `pgbackrest`, cùng với một postgres user.

Trong kịch bản này, chúng ta tiếp tục sử dụng PostgreSQL server `pg1` với `ip= 192.168.122.170`. Ngoài ra, cần thêm một server tên `pgbackrest`, có địa chỉ IP `192.168.122.120`.

== Trao đổi public key

Bây giờ, chúng ta sẽ xem cách trao đổi public key trước khi cài đặt `pgbackrest`:

. Trước hết, hãy tạo một SSH key cho Postgres user trên cả hai server. Với tư cách user PostgreSQL, hãy thực thi:

[source,console,role="transcript"]
....
   postgres@pgbackrest:~$ ssh-keygen -t rsa -b 4096
   Generating public/private rsa key pair.
   Enter file in which to save the key (/home/postgres/.ssh/id_rsa):
   Created directory '/home/postgres/.ssh'.
   Enter passphrase (empty for no passphrase):
   Enter same passphrase again:
   Your identification has been saved in /home/postgres/.ssh/id_rsa
   Your public key has been saved in /home/postgres/.ssh/id_rsa.pub
   The key fingerprint is:
   SHA256:5BPkarhop6Z82WeWWtYM1i5gHseFHAVJEoKy8GFSHjQ postgres@
   pgbackrest
   The key's randomart image is:
   +---[RSA 4096]----+
   | oE. oo+=.         |
   |+ooo. o+o          |
   |o=..     o+.       |
   |. .    ..+o.       |
   |      .+o=S.         |
   |    .oo= =.          |
   |   o =. +.+          |
   |...= .o=.            |
    |.+o    .=            |
    +----[SHA256]-----+
....

.Command
[source,bash]
....
ssh-keygen -t rsa -b 4096
....

.Output
[source,output]
....
   Generating public/private rsa key pair.
   Enter file in which to save the key (/home/postgres/.ssh/id_rsa):
   Created directory '/home/postgres/.ssh'.
   Enter passphrase (empty for no passphrase):
   Enter same passphrase again:
   Your identification has been saved in /home/postgres/.ssh/id_rsa
   Your public key has been saved in /home/postgres/.ssh/id_rsa.pub
   The key fingerprint is:
   SHA256:5BPkarhop6Z82WeWWtYM1i5gHseFHAVJEoKy8GFSHjQ postgres@
   pgbackrest
   The key's randomart image is:
   +---[RSA 4096]----+
   | oE. oo+=.         |
   |+ooo. o+o          |
   |o=..     o+.       |
   |. .    ..+o.       |
   |      .+o=S.         |
   |    .oo= =.          |
   |   o =. +.+          |
   |...= .o=.            |
    |.+o    .=            |
    +----[SHA256]-----+
....


[source,console,role="transcript"]
....
    postgres@pg1:~$ ssh-keygen -t rsa -b 4096
    Generating public/private rsa key pair.
    Enter file in which to save the key (/home/postgres/.ssh/id_rsa):
    Created directory '/home/postgres/.ssh'.
    Enter passphrase (empty for no passphrase):
    Enter same passphrase again:
    Your identification has been saved in /home/postgres/.ssh/id_rsa
    Your public key has been saved in /home/postgres/.ssh/id_rsa.pub
    The key fingerprint is:
    SHA256:g/amWaxcTGsmx2WQ91U/23UcBXmDtSsfRYhqE7dMWko postgres@pg1
    The key's randomart image is:
    +---[RSA 4096]----+
    |                 .+*=|
    |             .E =.o==|
    |            o..X ..+B|
    |         . o*.o.    O|
    |        o S.o... +.|
    |       . * =      o .|
    |        . &        . |
    |       . %           |
    |        =            |
    +----[SHA256]-----+
....

.Command
[source,bash]
....
ssh-keygen -t rsa -b 4096
....

.Output
[source,output]
....
    Generating public/private rsa key pair.
    Enter file in which to save the key (/home/postgres/.ssh/id_rsa):
    Created directory '/home/postgres/.ssh'.
    Enter passphrase (empty for no passphrase):
    Enter same passphrase again:
    Your identification has been saved in /home/postgres/.ssh/id_rsa
    Your public key has been saved in /home/postgres/.ssh/id_rsa.pub
    The key fingerprint is:
    SHA256:g/amWaxcTGsmx2WQ91U/23UcBXmDtSsfRYhqE7dMWko postgres@pg1
    The key's randomart image is:
    +---[RSA 4096]----+
    |                 .+*=|
    |             .E =.o==|
    |            o..X ..+B|
    |         . o*.o.    O|
    |        o S.o... +.|
    |       . * =      o .|
    |        . &        . |
    |       . %           |
    |        =            |
    +----[SHA256]-----+
....


    Trên cả hai server, khi chạy command `ssh-keygen`, chỉ cần nhấn phím *Enter* mỗi khi được yêu cầu nhập passphrase.

[%start=2]
. Bây giờ, trên cả hai server, thư mục `~/.ssh` của postgres user sẽ chứa hai file:

[source,console,role="transcript"]
....
   postgres@pgbackrest:~/.ssh$ ls -l
   total 8
   -rw------- 1 postgres postgres 3389 Jul 10 08:34 id_rsa
   -rw-r--r-- 1 postgres postgres         745 Jul 10 08:34 id_rsa.pub
....

.Command
[source,bash]
....
ls -l
....

.Output
[source,output]
....
   total 8
   -rw------- 1 postgres postgres 3389 Jul 10 08:34 id_rsa
   -rw-r--r-- 1 postgres postgres         745 Jul 10 08:34 id_rsa.pub
....


[source,console,role="transcript"]
....
   postgres@pg1:~/.ssh$ ls -l
   total 8
   -rw------- 1 postgres postgres 3381 Jul 10 08:34 id_rsa
   -rw-r--r-- 1 postgres postgres       738 Jul 10 08:34 id_rsa.pub
....

.Command
[source,bash]
....
ls -l
....

.Output
[source,output]
....
   total 8
   -rw------- 1 postgres postgres 3381 Jul 10 08:34 id_rsa
   -rw-r--r-- 1 postgres postgres       738 Jul 10 08:34 id_rsa.pub
....


. Cách nhanh nhất để trao đổi public key giữa hai server là dùng command `ssh-copy-id`:

[source,console,role="transcript"]
....
   postgres@pg1:~/.ssh$ ssh-copy-id 192.168.122.120
   [.. cutted..]
   Number of key(s) added: 1


   Now try logging into the machine, with:          "ssh '192.168.122.120'"
   and check to make sure that only the key(s) you wanted were added.

   postgres@pgbackrest:~/.ssh$ ssh-copy-id 192.168.122.170
   [.. cutted..]

   Number of key(s) added: 1

   Now try logging into the machine, with:  "ssh '192.168.122.170'"
   and check to make sure that only the key(s) you wanted were added
....

.Command
[source,bash]
....
ssh-copy-id 192.168.122.120
ssh-copy-id 192.168.122.170
....

.Output
[source,output]
....
   [.. cutted..]
   Number of key(s) added: 1


   Now try logging into the machine, with:          "ssh '192.168.122.120'"
   and check to make sure that only the key(s) you wanted were added.

   [.. cutted..]

   Number of key(s) added: 1

   Now try logging into the machine, with:  "ssh '192.168.122.170'"
   and check to make sure that only the key(s) you wanted were added
....


Bây giờ, postgres user có thể kết nối hai server với nhau mà không cần cung cấp password.

== Cài đặt pgbackrest

Trước khi cài đặt, cần kiểm tra xem repository của mỗi host có cùng version `pgbackrest` hay không. Sau đó, cài đặt nó trên server `pgbackrest` và server `pg1`. Trên một server kiểu Debian, với quyền root user, hãy chạy các command sau trên cả hai server:

[source,text]
....
root@pg1:~# apt-get update
root@pgbackrest:~# apt-get update


root@pg1:~# apt-get install pgbackrest
root@pgbackrest:~# apt-get install pgbackrest
....

Nếu sử dụng RHEL server, phải dùng command `yum` thay cho command `apt-get`.

== Cấu hình pgbackrest

Bây giờ, hãy xem cách cấu hình công cụ `pgbackrest`. Công cụ này cần có configuration trên cả hai server: configuration của repository server, nơi lưu dữ liệu, và configuration của PostgreSQL server, để server này có thể gửi toàn bộ dữ liệu đến repository server. Vì vậy, chúng ta sẽ lần lượt xử lý hai configuration:

* Repository configuration của server `pgbackrest`.
* PostgreSQL configuration của server `pg1`.

== Cấu hình repository

Configuration file của server `pgbackrest` nằm tại:

[source,text]
....
/etc/pgbackrest.conf
....

Có thể sử dụng một configuration file khác, nhưng phải chỉ định file đó nhất quán trong mỗi lần chạy chương trình, vì vậy tốt nhất là dùng file mặc định. Mỗi parameter trong configuration file có thể bị override bởi parameter tương ứng truyền trên command line. Mỗi parameter thuộc một section và được chỉ định bằng một key-value pair. Trong stanza configuration, parameter của mỗi cluster luôn bắt đầu bằng `pgN-`, trong đó N là số thứ tự tăng dần. Cluster chính (primary) luôn mang số 1, còn các standby cluster được đánh số tuần tự từ số 2. Tương tự, trong global parameter, repository được đánh số bắt đầu từ 1 (`repo1`), nhưng hiện tại chưa hỗ trợ nhiều repository. `pgbackrest` hoạt động đối xứng, nghĩa là mọi command đều có thể chạy trên backup machine hoặc target machine. Chúng ta sẽ có một configuration file cho repository server và một configuration file cho PostgreSQL server; hai configuration file này khác nhau. Theo mặc định, `pgbackrest` bật compression cho WAL segment và base backup với compression factor bằng 6. Có thể buộc compression sử dụng level khác bằng directive `compress-level`; ví dụ, đặt compression level bằng 9 để đạt compression tối đa.

Repository cũng có thể được encrypted bằng cơ chế do `pgbackrest` quản lý; tính năng này hữu ích, chẳng hạn khi lưu backup trên cloud có chi phí thấp.

Bây giờ, hãy bắt đầu với một configuration đơn giản, trước hết là global configuration section trên server `pgbackrest`:

[source,text]
....
[global]
start-fast=y
archive-async=y
process-max=2
repo-path=/var/lib/pgbackrest
repo1-retention-full=2
repo1-retention-archive=5
repo1-retention-diff=3
log-level-console=info
log-level-file=info
....

Các option trên có ý nghĩa như sau:

* `start-fast=y`: Buộc thực hiện checkpoint trên remote server để `pg_start_backup ()` bắt đầu sớm nhất có thể.
* `archive-async=y`: Bật transfer WAL bất đồng bộ cho các operation push/pull.
* `process-max=2`: Đặt số process tối đa mà hệ thống có thể sử dụng cho các operation transfer/compression.
* `repo-path=/var/lib/pgbackrest`: Đặt path nơi lưu repository; user chạy command `pgbackrest` phải có quyền read/write trên thư mục này.
* `repo1-retention-full=2`: Số full backup cần giữ lại. Khi một full backup hết hạn, tất cả differential và/hoặc incremental backup gắn với full backup đó cũng hết hạn. Nếu không định nghĩa option này, hệ thống sẽ phát cảnh báo. Nếu muốn retention vô thời hạn, đặt option này ở giá trị tối đa (9,999,999).
* `repo1-retention-archive=5`: Đại diện cho số WAL file của backup cần giữ lại. Các WAL segment cần thiết để tạo một backup nhất quán luôn được giữ cho đến khi backup hết hạn, bất kể configuration của option này. Nếu không đặt giá trị này, archive sắp hết hạn sẽ tự động hết hạn theo giá trị `repo-retention-full` (hoặc `repo-retention-diff`) tương ứng với loại `repo-retention archive`, nếu loại này được đặt thành `full` (hoặc `diff`). Điều này bảo đảm WAL file chỉ hết hạn đối với các backup đã hết hạn.
* `repo1-retention-diff = 3`: Số differential backup cần giữ lại. Khi một differential backup hết hạn, tất cả incremental backup gắn với differential backup đó cũng hết hạn. Nếu không định nghĩa, mọi differential backup sẽ được giữ cho đến khi các full backup mà chúng phụ thuộc vào hết hạn.
* `log-level-console=info/log-level-file=info log`: Các thiết lập quản lý log: đặt log level trên terminal (`log-level-console`) và trong log file (`log-level-file`).

Configuration file trên chỉ là một ví dụ đơn giản; nếu muốn thêm tính năng, chỉ cần bổ sung chúng vào configuration file.

Ví dụ, nếu muốn thay đổi compression level và tăng lên level 9, có thể thêm các dòng sau:

[source,text]
....
compress = y
compress-level = 9
compress-level-network = 9
....

Tương tự, nếu muốn thêm tính năng cipher, có thể thêm các dòng sau:

[source,text]
....
repo1-cipher-type = aes-256-cbc
repo1-cipher-pass = LearnPostgreSQL
....

Sau khi cấu hình global section, chúng ta có thể cấu hình stanza. `pgbackrest` đưa vào khái niệm stanza; về bản chất, mỗi stanza có thể gắn với một database cluster. Dưới đây là một ví dụ về stanza; việc tên stanza là `[pg1]` và trùng với tên cluster chỉ là sự trùng hợp. Cần tạo một stanza cho mỗi remote PostgreSQL server mà chúng ta muốn quản lý backup bằng `pgbackrest`. Mỗi stanza phải có tên riêng:

[source,text]
....
[pg1]
pg1-host = 192.168.122.170
pg1-host-user = postgres
pg1-path = /var/lib/postgresql/16/main
pg1-port = 5432
....

Các option trên có ý nghĩa như sau:

* `pg1-host`: Đây là remote host của PostgreSQL master server.
* `pg1-host-user = postgres`: Khi parameter `pg-host` được đặt, đây là user dùng để truy cập remote PostgreSQL server. User này cũng là owner của remote `pgbackrest` process; process đó khởi tạo connection đến PostgreSQL server. User này nên là owner của PostgreSQL database cluster. Thông thường, có thể dùng user mặc định postgres, vì vậy đây thường là user mà chúng ta đã trao đổi public key.
* `pg1-path = /var/lib/postgresql/16/main`: Đây là path trên PostgreSQL cluster nơi lưu dữ liệu. Có thể tìm thấy path này trong parameter `data_directory` bên trong file `postgresql.conf`.
* `pg1-port = 5432`: Listen port của remote PostgreSQL server.

== Sử dụng pgbackrest với object store

`pgbackrest` hỗ trợ object store trên Azure, GCP và Amazon S3; nghĩa là `pgbackrest` có thể lưu toàn bộ dữ liệu trực tiếp vào một bucket chi phí thấp, sử dụng cơ chế mã hóa dữ liệu đã đề cập ở trên.

Configuration khá đơn giản; ví dụ, với một GCP bucket, cần chỉ định các parameter sau:

[source,text]
....
repo1-type=gcs
repo1-path=/path_on the bucket
repo1-gcs-bucket=bucket_name
repo1-gcs-key=/etc/pgbackrest-key.json
....

Sau khi thêm các parameter này, `pgbackrest` có thể lưu toàn bộ dữ liệu vào một Google bucket; tính năng này rất hữu ích cho DBA vì cho phép lưu trữ và mã hóa dữ liệu trên cloud với chi phí thấp.

Nhờ đó, chúng ta không cần lo lắng về kích thước disk lưu repository mà `pgbackrest` sử dụng. Đồng thời, vì chi phí trên mỗi GB của bucket rất thấp, chúng ta có thể tăng retention đáng kể. Để biết thêm thông tin về configuration của `pgbackrest` với bucket S3, Azure và GCP, hãy truy cập các liên kết sau:

* https://pgbackrest.org/user-guide.html#azure-support
* https://pgbackrest.org/user-guide.html#s3-support
* https://pgbackrest.org/user-guide.html#gcs-support

== Cấu hình PostgreSQL server

Bây giờ, chuyển sang configuration của PostgreSQL server. Trên server `pg1`, cần sửa file `postgresql.conf` và cũng cần thiết lập file `pgbackrest.conf`.
