= 16. Configuration and Monitoring

Một trong những nhiệm vụ của database administrator là configure cluster để nó hoạt động tốt với workload và context hiện tại. Configuration không static: phần lớn thời gian, bạn sẽ thấy mình đang thực hiện các thay đổi đối với configuration, vì vậy điều quan trọng là bạn cảm thấy thoải mái khi inspect và thay đổi configuration của cluster.

Một task quan trọng khác, có liên quan một phần đến configuration, là monitoring cluster để hiểu hệ thống thực sự đang hoạt động như thế nào và có bottleneck hay problem nào cần giải quyết hay không. Những problem như vậy đôi khi có thể được giải quyết bằng cách thay đổi configuration của cluster, sử dụng hardware khác (ví dụ tăng memory khả dụng), và sửa các application có thể đang gây bottleneck.

Chapter này sẽ chỉ cho bạn cách quản lý và inspect cluster configuration, generate configuration từ đầu, tìm error và mistake trong configuration hiện tại, cũng như interactively monitor activity của cluster thông qua rich statistics subsystem. Cuối cùng, bạn sẽ khám phá một extension rất mạnh và thường được sử dụng tên là `pg_stat_statements`, cho phép bạn monitor activity của cluster với mức độ chi tiết và flexibility cao.

Chapter này sẽ bao quát các chủ đề sau:

* Cluster configuration
* Monitoring cluster
* Advanced statistics với `pg_stat_statements`

Bắt đầu thôi!
