= Khám phá extension `pg_trgm`

Bây giờ, hãy quay lại Chapter 13, Indexes and Performance Optimization, tại section Indexes. Khi tìm hiểu về indexing, chúng ta đã học cách tăng tốc query bằng index. Tuy nhiên, B-tree index không thể index mọi loại thao tác. Hãy xét các data type dạng text (`char`, `varchar` hoặc `text`). Ta sẽ thấy rằng B-tree, khi dùng operator class `varchar_pattern_ops`, có thể index các query trên text có chuỗi bắt đầu bằng `search%`, nhưng không thể index các query trên text có chuỗi kết thúc bằng `%search` hoặc chứa `%search%`:

. Trước khi đi vào ví dụ, hãy đặt `enable_seqscan` thành `off` để buộc PostgreSQL sử dụng index nếu có. Cần làm vậy vì trong ví dụ này, theo mặc định PostgreSQL luôn sử dụng sequential scan: table chỉ có vài row và toàn bộ dữ liệu trong table được lưu trên một page duy nhất:

[source,console,role="transcript"]
....
   forumdb=> set enable_seqscan to 'off';
   SET
....

.SQL
[source,sql]
....
SET enable_seqscan to 'off';
....

.Output
[source,output]
....
   SET
....


. Bây giờ, trong database, chúng ta có thể chạy query sau trên table `categories`:

[source,console,role="transcript"]
....
   forumdb=> select pk,title from categories;
    pk |             title
   ----+-----------------------
       1 | Database
       2 | Unix
       3 | Programming Languages
....

.SQL
[source,sql]
....
SELECT
    pk,
    title
FROM categories;
....

.Output
[source,output]
....
    pk |             title
   ----+-----------------------
       1 | Database
       2 | Unix
       3 | Programming Languages
....


. Hãy tạo một B-tree index dùng varchar opclass để kiểm tra xem PostgreSQL có sử dụng index access để truy cập table khi chạy query với operator `like` hay không:

[source,console,role="transcript"]
....
   forumdb=> create index on categories using btree(title varchar_
   pattern_ops);
   CREATE INDEX
....

.SQL
[source,sql]
....
CREATE INDEX ON categories USING btree(title varchar_
   pattern_ops);
....

.Output
[source,output]
....
   CREATE INDEX
....


   Bây giờ, hãy thực hiện một số query `like`:

[%start=4]
. Trong ví dụ đầu tiên, hãy chạy một query `like` với predicate `‘search%'`:

[source,console,role="transcript"]
....
   forumdb=> explain analyze select * from categories where title like
   'Da%';
                                                                                   QUERY PL
   AN
   ---------------------------------------------------------
    Index Scan using categories_title_idx on categories
   (cost=0.13..8.15 rows=1 width=68)
   (actual time=0.033..0.037 rows=1 loops=1)
        Index Cond: ((title ~>=~ 'Da'::text) AND (title ~<~ 'Db'::text))
        Filter: (title ~~ 'Da%'::text)
    Planning Time: 0.172 ms
    Execution Time: 0.075 ms
   (5 rows)
....

.SQL
[source,sql]
....
EXPLAIN analyze SELECT * FROM categories WHERE title like
   'Da%';
....

.Output
[source,output]
....
                                                                                   QUERY PL
   AN
   ---------------------------------------------------------
    Index Scan using categories_title_idx on categories
   (cost=0.13..8.15 rows=1 width=68)
   (actual time=0.033..0.037 rows=1 loops=1)
        Index Cond: ((title ~>=~ 'Da'::text) AND (title ~<~ 'Db'::text))
        Filter: (title ~~ 'Da%'::text)
    Planning Time: 0.172 ms
    Execution Time: 0.075 ms
   (5 rows)
....


. Trong ví dụ thứ hai, hãy chạy một query `like` với predicate `‘%search'`:

[source,console,role="transcript"]
....
   forumdb=> explain analyze select * from categories where title like
   '%Da%';
                                                                              QUERY PLAN
   ---------------------------------------------------------
    Seq Scan on categories (cost=10000000000.00..10000000001.04 rows=1
   width=68) (actual time=17.278..17.283 rows=1 loops=1)
        Filter: (title ~~ '%Da%'::text)
        Rows Removed by Filter: 2
   Planning Time: 0.101 ms
   JIT:
     Functions: 2
     Options: Inlining true, Optimization true, Expressions true,
   Deforming true
       Timing: Generation 0.477 ms, Inlining 5.469 ms, Optimization
   7.027 ms, Emission 4.750 ms, Total 17.722 ms
    Execution Time: 17.834 ms
   (9 rows)
....

.SQL
[source,sql]
....
EXPLAIN analyze SELECT * FROM categories WHERE title like
   '%Da%';
....

.Output
[source,output]
....
                                                                              QUERY PLAN
   ---------------------------------------------------------
    Seq Scan on categories (cost=10000000000.00..10000000001.04 rows=1
   width=68) (actual time=17.278..17.283 rows=1 loops=1)
        Filter: (title ~~ '%Da%'::text)
        Rows Removed by Filter: 2
   Planning Time: 0.101 ms
   JIT:
     Functions: 2
     Options: Inlining true, Optimization true, Expressions true,
   Deforming true
       Timing: Generation 0.477 ms, Inlining 5.469 ms, Optimization
   7.027 ms, Emission 4.750 ms, Total 17.722 ms
    Execution Time: 17.834 ms
   (9 rows)
....


Như có thể thấy, chỉ trong trường hợp đầu tiên PostgreSQL mới sử dụng index access. Trong trường hợp thứ hai, PostgreSQL sử dụng sequential scan vì không có index nào có thể dùng được. Để cải thiện kiểu tìm kiếm này, chúng ta có thể sử dụng extension `pg_trgm`; đây là extension chính thức, nằm trong gói contrib chính thức của PostgreSQL. Khi sử dụng extension này, PostgreSQL tách mỗi từ thành một tập trigram và tạo một GiST hoặc GIN index trên tập đó. Ví dụ, nếu xét từ `dog`, tập trigram của nó gồm `d`, `do`, `og` và `dog`. Hãy xem cách hoạt động này trong thực tế:

. Trước hết, hãy cài đặt extension:

[source,console,role="transcript"]
....
   forumdb=> create extension pg_trgm;
   CREATE EXTENSION
....

.SQL
[source,sql]
....
CREATE extension pg_trgm;
....

.Output
[source,output]
....
   CREATE EXTENSION
....


. Bây giờ, chúng ta có thể tạo GIN hoặc GiST index với trigram opclass. Ví dụ, hãy tạo một GIN index bằng opclass `gin_trgm_ops`:

[source,console,role="transcript"]
....
   forumdb=> create index           on categories using gin (title gin_trgm_
   ops);
   CREATE INDEX
....

.SQL
[source,sql]
....
CREATE INDEX ON categories USING gin (title gin_trgm_
   ops);
....

.Output
[source,output]
....
   CREATE INDEX
....


. Bây giờ, hãy thực hiện query `like`:

[source,console,role="transcript"]
....
   forumdb=> explain analyze select * from categories where title like
   'Da%';
                                                                                       QUERY PL
   AN
   ---------------------------------------------------------- Index
   Scan using categories_title_idx on categories (cost=0.13..8.15
   rows=1 width=68) (actual time=0.029..0.032 rows=1 loops=1)
        Index Cond: ((title ~>=~ 'Da'::text) AND (title ~<~ 'Db'::text))
        Filter: (title ~~ 'Da%'::text)
    Planning Time: 0.217 ms
    Execution Time: 0.069 ms
   (5 rows)
....

.SQL
[source,sql]
....
EXPLAIN analyze SELECT * FROM categories WHERE title like
   'Da%';
....

.Output
[source,output]
....
                                                                                       QUERY PL
   AN
   ---------------------------------------------------------- Index
   Scan using categories_title_idx on categories (cost=0.13..8.15
   rows=1 width=68) (actual time=0.029..0.032 rows=1 loops=1)
        Index Cond: ((title ~>=~ 'Da'::text) AND (title ~<~ 'Db'::text))
        Filter: (title ~~ 'Da%'::text)
    Planning Time: 0.217 ms
    Execution Time: 0.069 ms
   (5 rows)
....


Như có thể thấy, PostgreSQL giờ đây có thể dùng index để truy cập table với một query `like`. Điều tương tự cũng đúng với mọi loại query `like` và `ilike`; extension `pg_trgm` cho phép truy cập các table bằng index trong những query này. Để biết thêm thông tin về extension `pg_trgm`, hãy xem https://www.postgresql.org/docs/current/pgtrgm.html.

Extension `pg_trgm` giúp công việc của DBA dễ dàng hơn trong mọi trường hợp cần tối ưu query `like` và `ilike`. Bây giờ, chúng ta sẽ chuyển sang extension tiếp theo, `postgres_fdw`.
