= Sử dụng clause LIKE

Giả sử chúng ta muốn tìm tất cả row có giá trị trong column `title` bắt đầu bằng chuỗi Prog.

Để làm điều đó, chúng ta phải sử dụng điều kiện LIKE:

[source,console,role="transcript"]
....
forumdb=> \x
Expanded display is on.
forumdb=> select * from categories where title like 'Prog%';
-[ RECORD 1 ]--------------------------------
pk           | 3
title        | Programming Languages
description | All about programming languages
....

.SQL
[source,sql]
....
\x SELECT * FROM categories WHERE title like 'Prog%';
....

.Output
[source,output]
....
Expanded display is on.
-[ RECORD 1 ]--------------------------------
pk           | 3
title        | Programming Languages
description | All about programming languages
....


Như minh họa, query trên trả về tất cả row có giá trị trong column `title` bắt đầu bằng chuỗi Prog. Tương tự, nếu muốn tìm tất cả row có giá trị trong column title kết thúc bằng từ Languages, chúng ta sẽ viết như sau:

[source,console,role="transcript"]
....
forumdb=> select * from categories where title like '%Languages';
-[ RECORD 1 ]--------------------------------
pk           | 3
title        | Programming Languages
description | All about programming languages
....

.SQL
[source,sql]
....
SELECT *
FROM categories
WHERE title like '%Languages';
....

.Output
[source,output]
....
-[ RECORD 1 ]--------------------------------
pk           | 3
title        | Programming Languages
description | All about programming languages
....


Hai cách tìm kiếm này cũng có thể kết hợp. Ví dụ, nếu muốn tìm tất cả row chứa chuỗi con `discuss`, chúng ta sẽ viết như sau:

[source,console,role="transcript"]
....
forumdb=> \x
Expanded display is off
forumdb=> select * from categories where description like '%discuss%';
 pk |   title   |           description
----+----------+------------------------------
1 | Database | Database related discussions
2 | Unix       | Unix and Linux discussions
(2 rows)
....

.SQL
[source,sql]
....
\x SELECT * FROM categories WHERE description like '%discuss%';
....

.Output
[source,output]
....
Expanded display is off
 pk |   title   |           description
----+----------+------------------------------
1 | Database | Database related discussions
2 | Unix       | Unix and Linux discussions
(2 rows)
....


Query này trả về tất cả row có giá trị trong column `description` chứa chuỗi con discuss.

Bây giờ, hãy thử chạy query sau để xem điều gì xảy ra:

[source,console,role="transcript"]
....
forumdb=> select * from categories where title like 'prog%';
(0 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM categories
WHERE title like 'prog%';
....

.Output
[source,output]
....
(0 rows)
....


Như có thể thấy, query không trả về kết quả nào. Điều này xảy ra vì các phép tìm kiếm bằng LIKE phân biệt chữ hoa và chữ thường.

Bây giờ, hãy tìm hiểu function `upper` (text). Function này nhận một chuỗi đầu vào và trả về chính chuỗi đó với mọi ký tự được viết hoa, như sau:

[source,console,role="transcript"]
....
forumdb=> select upper('prog');
 upper
-------
 PROG
(1 row)
....

.SQL
[source,sql]
....
SELECT upper('prog');
....

.Output
[source,output]
....
 upper
-------
 PROG
(1 row)
....


[quote]
____
Trong PostgreSQL, có thể gọi function mà không cần viết `FROM`. PostgreSQL không cần dummy table để thực thi statement `SELECT`. Nếu dùng Oracle DB, query tương tự phải được viết như sau: `select upper('prog') from DUAL;`.

____
Quay lại ví dụ trước, nếu muốn thực hiện một phép tìm kiếm bằng LIKE không phân biệt chữ hoa và chữ thường, chúng ta phải viết statement như sau:

[source,console,role="transcript"]
....
forumdb=> select * from categories where upper(description) like
'%DISCUSS%';
 pk |  title   |            description
----+----------+------------------------------
   1 | Database | Database related discussions
   2 | Unix       | Unix and Linux discussions
(2 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM categories
WHERE upper(description) like '%DISCUSS%';
....

.Output
[source,output]
....
 pk |  title   |            description
----+----------+------------------------------
   1 | Database | Database related discussions
   2 | Unix       | Unix and Linux discussions
(2 rows)
....


Đến đây, chúng ta đã trình bày mọi cách sử dụng operator `like`.
