= Khám phá PGXN client

PGXN client là một ứng dụng bên ngoài, được viết bằng Python và hoạt động như một command-line interface cho PGXN. Ứng dụng này có tên `pgxnclient` và thực hiện các command như install, download, uninstall, v.v.; nhờ đó, database administrator có thể tương tác với PGXN và các extension.

[quote]
____
Ở một mức độ nào đó, `pgxnclient` hoạt động tương tự command `cpan` (hoặc `cpanm`) của Perl, `zef` của Raku, `pip` của Python, v.v.

Vì là một ứng dụng bên ngoài, `pgxnclient` không được phân phối cùng PostgreSQL, nên bạn cần cài đặt nó trên máy trước khi có thể sử dụng. Việc cài đặt `pgxnclient` không bắt buộc để sử dụng các extension của PostgreSQL, nhưng có thể giúp công việc của bạn dễ dàng hơn nhiều.

____
Trong các phần tiếp theo, bạn sẽ thấy cách cài đặt `pgxnclient` trên các hệ điều hành Unix và Unix-like chính. Trước hết, điều quan trọng cần biết là sau khi cài đặt, bạn sẽ thấy hai executable trên hệ thống: `pgxn` và `pgxnclient`. Bạn có thể xem chúng là alias của nhau, dù điều này không hoàn toàn chính xác (một executable bao bọc executable kia); tuy nhiên, bạn có thể dùng executable nào cũng được và nhận được cùng một kết quả. Trong chương này, chúng ta sẽ dùng `pgxn` làm executable chính.

[quote]
____
Trong các Docker image trong repository của cuốn sách, chương trình `pgxnclient` đã được cài đặt sẵn, nên bạn không cần cài đặt nó.

Hướng dẫn chi tiết về cách cài đặt `pgxnclient` nằm ngoài phạm vi của cuốn sách này; vì vậy, nếu bạn không thể khiến ứng dụng hoạt động đúng, hãy kiểm tra lại tài liệu của dự án và hướng dẫn cài đặt.

____
== Cài đặt pgxnclient trên Debian GNU/Linux và các bản phân phối dẫn xuất

`pgxnclient` được đóng gói cho Debian GNU/Linux và các bản phân phối dẫn xuất, nghĩa là bạn chỉ cần dùng `apt` để cài đặt nó:

[source,console,role="transcript"]
....
$ sudo apt install pgxnclient
....

.Command
[source,bash]
....
sudo apt install pgxnclient
....


Sau khi chương trình được cài đặt, bạn có thể kiểm tra bằng option `--version`; option này sẽ in ra version number của bản bạn đã cài đặt:

[source,console,role="transcript"]
....
$ pgxn --version
pgxnclient 1.3.2
....

.Command
[source,bash]
....
pgxn --version
....

.Output
[source,output]
....
pgxnclient 1.3.2
....


== Cài đặt pgxnclient trên Fedora Linux và các bản phân phối dựa trên Red Hat

`pgxnclient` cũng được đóng gói cho Fedora, vì vậy bạn có thể cài đặt nó bằng package manager của hệ điều hành:

[source,console,role="transcript"]
....
$ sudo dnf install -y pgxnclient
....

.Command
[source,bash]
....
sudo dnf install -y pgxnclient
....


Sau khi quá trình hoàn tất, bạn có thể gọi ứng dụng để xác minh rằng nó thực sự hoạt động:

[source,console,role="transcript"]
....
$ pgxn --version
pgxnclient 1.3.2
....

.Command
[source,bash]
....
pgxn --version
....

.Output
[source,output]
....
pgxnclient 1.3.2
....


== Cài đặt pgxnclient trên FreeBSD

`pgxnclient` được đóng gói cho FreeBSD, vì vậy bạn có thể cài đặt nó bằng công cụ `pkg` hoặc hệ thống ports. Cách nhanh nhất là dùng `pkg`; bạn chỉ cần yêu cầu cài đặt chương trình:

[source,console,role="transcript"]
....
$ sudo pkg install --yes pgxnclient
....

.Command
[source,bash]
....
sudo pkg install --yes pgxnclient
....


== Cài đặt pgxnclient từ source

Bạn luôn có thể cài đặt `pgxnclient` từ source, dù cách này chỉ được khuyến nghị khi bạn đang dùng một hệ điều hành không cung cấp bản đóng gói hoặc version hiện tại đã quá cũ so với nhu cầu của bạn. Bạn có thể tải bản nén của release mới nhất từ repository GitHub chính thức của dự án, chẳng hạn:

[source,console,role="transcript"]
....
$ wget https://github.com/pgxn/pgxnclient/archive/refs/tags/v1.3.2.zip
....

.Command
[source,bash]
....
wget https://github.com/pgxn/pgxnclient/archive/refs/tags/v1.3.2.zip
....


Sau khi có tập tin nén, bạn cần giải nén rồi chuyển vào thư mục được tạo ra. Thư mục này được đặt tên theo version của PGXN mà bạn đã tải xuống; trong trường hợp này là `pgxnclient-3.1.2`. Khi đã ở trong thư mục, bạn có thể chạy Python script `setup.py` để cài đặt ứng dụng:

[source,console,role="transcript"]
....
$ unzip v1.3.2.zip
$ cd pgxnclient-1.3.2
$ sudo python setup.py install
...
Finished processing dependencies for pgxnclient==1.3.2
....

.Command
[source,bash]
....
unzip v1.3.2.zip
cd pgxnclient-1.3.2
sudo python setup.py install
....

.Output
[source,output]
....
...
Finished processing dependencies for pgxnclient==1.3.2
....


Sau khi hoàn tất cài đặt, bạn có thể gọi ứng dụng để xác minh rằng nó đang hoạt động:

[source,console,role="transcript"]
....
$ pgxn --version
pgxnclient 1.3.2
....

.Command
[source,bash]
....
pgxn --version
....

.Output
[source,output]
....
pgxnclient 1.3.2
....


== Giao diện dòng lệnh của pgxnclient

PGXN client cung cấp một giao diện dòng lệnh tương tự các ứng dụng khác, chẳng hạn như `cpanm` và `git`. Bạn có thể xem danh sách các command chính bằng cách yêu cầu trợ giúp:

[source,console,role="transcript"]
....
$ pgxn help
usage: pgxn [--version] [--help] COMMAND ...


Interact with the PostgreSQL Extension Network (PGXN).


optional arguments:
   --version     print the version number and exit
   --help        show this help message and exit


available commands:
   COMMAND       the command to execute. The complete list is available using
                 'pgxn help --all'. Builtin commands are:
      check      run a distribution's test
      download
                 download a distribution from the network
      help       display help and other program information
      info       print information about a distribution
      install    download, build and install a distribution
      load       load a distribution's extensions into a database
      mirror      return information about the available mirrors
      search      search in the available extensions
      uninstall
                 remove a distribution from the system
      unload      unload a distribution's extensions from a database
....

.Command
[source,bash]
....
pgxn help
....

.Output
[source,output]
....
usage: pgxn [--version] [--help] COMMAND ...


Interact with the PostgreSQL Extension Network (PGXN).


optional arguments:
   --version     print the version number and exit
   --help        show this help message and exit


available commands:
   COMMAND       the command to execute. The complete list is available using
                 'pgxn help --all'. Builtin commands are:
      check      run a distribution's test
      download
                 download a distribution from the network
      help       display help and other program information
      info       print information about a distribution
      install    download, build and install a distribution
      load       load a distribution's extensions into a database
      mirror      return information about the available mirrors
      search      search in the available extensions
      uninstall
                 remove a distribution from the system
      unload      unload a distribution's extensions from a database
....


Thông thường, bạn sẽ dùng nhóm command sau:

* `search` để tìm distribution theo keyword
* `info` để xem chi tiết hơn về một extension
* `download` để tải xuống (nhưng không cài đặt) một extension
* `install` để tải xuống và cài đặt một extension vào cluster
* `load` để thực thi `CREATE EXTENSION` trong một database cụ thể
* `unload` để thực thi `DROP EXTENSION` trong một database cụ thể
* `uninstall` để xóa một extension khỏi cluster

Nhóm command tối thiểu mà có lẽ bạn sẽ dùng là `search`, `install` và `uninstall`.

Với mỗi command, bạn có thể xem thông tin trợ giúp chi tiết hơn bằng cách truyền tên command đó làm argument cho command `help`. Ví dụ, để biết thêm thông tin về command `search`, bạn có thể thực hiện như sau:

[source,console,role="transcript"]
....
$ pgxn help search
usage: pgxn search [--help] [--mirror URL] [--verbose] [--yes]
                       [--docs | --dist | --ext]
                       TERM [TERM ...]


search in the available extensions


positional arguments:
    TERM            a string to search


optional arguments:
    --help          show this help message and exit
    --docs          search in documentation [default]
    --dist          search in distributions
    --ext           search in extensions
....

.Command
[source,bash]
....
pgxn help search
....

.Output
[source,output]
....
usage: pgxn search [--help] [--mirror URL] [--verbose] [--yes]
                       [--docs | --dist | --ext]
                       TERM [TERM ...]


search in the available extensions


positional arguments:
    TERM            a string to search


optional arguments:
    --help          show this help message and exit
    --docs          search in documentation [default]
    --dist          search in distributions
    --ext           search in extensions
....


[source,text]
....
global options:
  --mirror URL    the mirror to interact with [default: https://api.pgxn.
org/]
  --verbose       print more information
  --yes           assume affirmative answer to all questions
....

Trong các phần tiếp theo, bạn sẽ thấy cách sử dụng PGXN hiệu quả để cài đặt một extension.
