= Tóm tắt

Hy vọng chapter này mang đến nhiều ý tưởng thú vị cho developer và DBA. Trong chapter này, chúng ta đã nói về các query phức tạp; sau đó xem statement `SELECT` và cách sử dụng các clause `LIKE`, `ILIKE`, `DISTINCT`, `OFFSET`, `LIMIT`, `IN` và `NOT IN`. Tiếp theo, chúng ta bắt đầu nói về aggregate thông qua các clause `GROUP BY` và `HAVING`, đồng thời giới thiệu một số aggregate function như `SUM()`, `COUNT()`, `AVG()`, `MIN()` và `MAX()`.

Sau đó, chúng ta đã nói sâu về subquery và join. Một nhóm chủ đề rất thú vị khác được đề cập trong chapter này là các query `UNION`, `EXCEPT` và `INTERSECT`. Cuối cùng, bằng cách xem xét các option nâng cao của các instruction `INSERT`, `DELETE`, `UPDATE` và `MERGE`, cũng như đề cập đến CTE, chúng ta đã thấy được sức mạnh của ngôn ngữ SQL do PostgreSQL cung cấp.

Xét về khái niệm aggregate, trong chapter tiếp theo chúng ta sẽ thấy một cách mới để tạo aggregate bằng window function. Thông qua window function, chúng ta sẽ thấy rằng có thể tạo tất cả aggregate và aggregate function được mô tả trong chapter này, nhưng cũng có tùy chọn tạo các aggregate function mới.
