= Kiểm tra kiến thức

* Trong PostgreSQL 15 và PostgreSQL, một user thông thường có thể thực hiện DDL không?

  Không. Xem phần PostgreSQL và public schema để biết thêm chi tiết.

* Lệnh `psql` nào dùng để liệt kê tất cả database cùng với kích thước tương ứng?

[source,console,role="transcript"]
....
  postgres=# \l+
....

.SQL
[source,sql]
....
\l+
....


  Xem phần Xác nhận kích thước database để biết thêm chi tiết.

* Nếu table được định nghĩa như sau:

[source,sql]
....
CREATE TABLE mytable (id integer, city_name varchar(60));
....

  Liệu query sau có hiển thị tất cả row có giá trị NULL trong column `city_name` không?

[source,sql]
....
SELECT *
FROM mytable
WHERE city_name = '';
....

  Không. Query đúng là:

[source,sql]
....
SELECT *
FROM mytable
WHERE city_name IS NULL;
....

  Xem phần Giá trị `NULL` để biết thêm chi tiết.

* Có thể tạo database mới dựa trên một database hiện có không?

  Có. Có thể sử dụng tùy chọn `TEMPLATE`.

  Xem phần Tạo database mới từ một template đã sửa đổi để biết thêm chi tiết.

* Query sau có phải là cách tốt nhất để xóa tất cả row trong table có tên `mytable` không?

[source,sql]
....
DELETE FROM mytable;
....

  Không. Cách tốt nhất để xóa toàn bộ row trong một table là sử dụng statement `TRUNCATE`.

  Xem phần Xóa dữ liệu để biết thêm chi tiết.
