= Dump toàn bộ cluster

`pg_dumpall` là công cụ dùng để dump toàn bộ một cluster. Nói ngắn gọn, `pg_dumpall` duyệt qua tất cả database trong cluster và thực hiện một `pg_dump` trên từng database, sau đó dump các object cụ thể ở cấp cluster, chẳng hạn như role.

`pg_dumpall` hoạt động tương tự như `pg_dump`, vì vậy gần như mọi khái niệm và option bạn đã thấy ở các phần trước cũng áp dụng cho `pg_dumpall`. Nếu không chỉ định cả output format lẫn file, `pg_dumpall` sẽ in tất cả SQL statement cần thiết ra standard output. Nếu muốn lưu toàn bộ nội dung của các database vào một SQL file duy nhất, command line sau sẽ tạo một full backup:

[source,console,role="transcript"]
....
$ pg_dumpall -f cluster.sql
....

.Command
[source,bash]
....
pg_dumpall -f cluster.sql
....


File này có thể nhanh chóng trở nên rất lớn; phần đầu file tạo tất cả role cần thiết:

[source,console,role="transcript"]
....
$ less cluster.sql
...
CREATE ROLE book_authors;
ALTER ROLE book_authors WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB
NOLOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE enrico;
ALTER ROLE enrico WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN
NOREPLICATION NOBYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:PiAJvQ9sn/TcrlcfhJF
isQ==$+gEEKa0oYVLPYNS1o4zO4Jng0qAwajBe3DHirEkJT40=:gek2heWOJT+G+8dJa
zqtn4x3Wl5zYY0DyyyKed7pvXY=';
CREATE ROLE forum;

...
....

.Command
[source,bash]
....
less cluster.sql
....

.Output
[source,output]
....
...
CREATE ROLE book_authors;
ALTER ROLE book_authors WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB
NOLOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE enrico;
ALTER ROLE enrico WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN
NOREPLICATION NOBYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:PiAJvQ9sn/TcrlcfhJF
isQ==$+gEEKa0oYVLPYNS1o4zO4Jng0qAwajBe3DHirEkJT40=:gek2heWOJT+G+8dJa
zqtn4x3Wl5zYY0DyyyKed7pvXY=';
CREATE ROLE forum;

...
....


Sau đó, script tiếp tục restore từng database, bao gồm cả `template1`. Tiếp theo, tất cả database được populate bằng các SQL statement do từng lần chạy `pg_dump` riêng lẻ tạo ra.

`pg_dumpall` chỉ tạo SQL script, vì vậy bạn cần restore cluster bằng `psql` hoặc thông qua một connection interactive. Tất cả option chính có thể dùng với `pg_dump` và đã được trình bày ở các phần trước cũng áp dụng cho `pg_dumpall`.

`pg_dumpall` cung cấp một option đặc biệt hữu ích là `--globals-only`, dùng để chỉ dump các object ở cấp cluster, chẳng hạn như role, tablespace và replication slot. Option này hữu ích khi dump và restore các object đó giữa những cluster khác nhau:

[source,console,role="transcript"]
....
$ pg_dumpall --globals-only -f cluster.sql
....

.Command
[source,bash]
....
pg_dumpall --globals-only -f cluster.sql
....
