= Thực hiện selective restore

Khi thực hiện plain SQL database dump, bạn có thể chỉnh sửa thủ công kết quả vì đó là plain text, rồi loại bỏ có chọn lọc những phần không muốn restore. Với custom format và `pg_restore`, bạn cũng có thể làm đúng như vậy, nhưng cần thực hiện một vài bước.

Trước hết, bạn luôn có thể kiểm tra nội dung của binary dump bằng `pg_restore` và option `--list`; option này in mục lục (Table of Contents, viết tắt là ToC) ra màn hình. Sau `--list`, bạn cần chỉ định một file đơn lẻ hoặc một directory chứa backup để in ToC:

[source,console,role="transcript"]
....
$ pg_restore --list backup.d
;
; Archive created at 2023-09-29 15:35:12 UTC
;     dbname: forumdb
;     TOC Entries: 39
;     Compression: -1
;     Dump Version: 1.14-0
;     Format: DIRECTORY
;
;
; Selected TOC Entries:
;
6; 2615 16653 SCHEMA - forum forum
215; 1259 16654 TABLE forum categories forum
216; 1259 16659 SEQUENCE forum categories_pk_seq forum
217; 1259 16660 TABLE forum delete_posts forum
218; 1259 16665 TABLE forum j_posts_tags forum
219; 1259 16668 TABLE forum new_categories forum
220; 1259 16673 TABLE forum posts forum
221; 1259 16682 SEQUENCE forum posts_pk_seq forum
222; 1259 16683 TABLE forum tags forum
223; 1259 16688 SEQUENCE forum tags_pk_seq forum
224; 1259 16689 TABLE forum users forum
225; 1259 16694 SEQUENCE forum users_pk_seq forum
3368; 0 16654 TABLE DATA forum categories forum
3370; 0 16660 TABLE DATA forum delete_posts forum
3371; 0 16665 TABLE DATA forum j_posts_tags forum
3372; 0 16668 TABLE DATA forum new_categories forum
3373; 0 16673 TABLE DATA forum posts forum
3375; 0 16683 TABLE DATA forum tags forum
3377; 0 16689 TABLE DATA forum users forum
3385; 0 0 SEQUENCE SET forum categories_pk_seq forum
...
....

.Command
[source,bash]
....
pg_restore --list backup.d
....

.Output
[source,output]
....
;
; Archive created at 2023-09-29 15:35:12 UTC
;     dbname: forumdb
;     TOC Entries: 39
;     Compression: -1
;     Dump Version: 1.14-0
;     Format: DIRECTORY
;
;
; Selected TOC Entries:
;
6; 2615 16653 SCHEMA - forum forum
215; 1259 16654 TABLE forum categories forum
216; 1259 16659 SEQUENCE forum categories_pk_seq forum
217; 1259 16660 TABLE forum delete_posts forum
218; 1259 16665 TABLE forum j_posts_tags forum
219; 1259 16668 TABLE forum new_categories forum
220; 1259 16673 TABLE forum posts forum
221; 1259 16682 SEQUENCE forum posts_pk_seq forum
222; 1259 16683 TABLE forum tags forum
223; 1259 16688 SEQUENCE forum tags_pk_seq forum
224; 1259 16689 TABLE forum users forum
225; 1259 16694 SEQUENCE forum users_pk_seq forum
3368; 0 16654 TABLE DATA forum categories forum
3370; 0 16660 TABLE DATA forum delete_posts forum
3371; 0 16665 TABLE DATA forum j_posts_tags forum
3372; 0 16668 TABLE DATA forum new_categories forum
3373; 0 16673 TABLE DATA forum posts forum
3375; 0 16683 TABLE DATA forum tags forum
3377; 0 16689 TABLE DATA forum users forum
3385; 0 0 SEQUENCE SET forum categories_pk_seq forum
...
....


Các dòng bắt đầu bằng dấu chấm phẩy là comment. Như bạn có thể thấy, một vài dòng đầu tiên tạo thành phần banner mô tả nội dung của backup, thời điểm backup được thực hiện, format (trong ví dụ này là “directory”) và số entry (object) trong backup.

Mỗi dòng không phải là comment đại diện cho một database object hoặc một thao tác riêng lẻ mà quá trình restore sẽ thực hiện. Ví dụ, hãy xem dòng sau:

[source,text]
....
222; 1259 16683 TABLE forum tags forum
....

Dòng này cho biết table `tags` sẽ được restore bởi user `forum` trong schema `forum`.

Dòng sau cho biết data cũng sẽ được nạp vào table đó:

[source,text]
....
3373; 0 16673 TABLE DATA forum posts forum
....

Nhờ ToC này, bạn có thể kiểm soát quá trình restore. Cụ thể, nếu di chuyển hoặc xóa các dòng khỏi ToC, bạn có thể yêu cầu `pg_restore` thay đổi cách thực thi. Trước hết, hãy lưu ToC vào một file text:

[source,console,role="transcript"]
....
$ pg_restore --list backup.d > custom_toc.txt
....

.Command
[source,bash]
....
pg_restore --list backup.d > custom_toc.txt
....


Bây giờ, hãy chỉnh sửa file `custom_toc.txt` bằng editor bạn yêu thích và comment out phần cần bỏ bằng một trong hai cách sau: đặt dấu chấm phẩy ở ký tự đầu tiên của dòng, hoặc xóa các dòng nạp table `tags` và join table liên quan:

[source,text]
....
;3373; 0 16673 TABLE DATA forum posts forum
;3371; 0 16665 TABLE DATA forum j_posts_tags forum
....

Bây giờ, hãy lưu file `custom_toc.txt`. Sau đó, bạn có thể restore database bằng `pg_restore`, nhưng phải yêu cầu chương trình tuân theo ToC riêng thay vì ToC đầy đủ, chưa chỉnh sửa đi kèm với backup. Vì mục đích này, `pg_restore` cho phép chỉ định flag `-L` cùng với ToC cần dùng:

[source,console,role="transcript"]
....
$ psql -c 'DROP DATABASE forumdb;'
DROP DATABASE

$ pg_restore -C -d postgres -L custom_toc.txt                backup.d
$ psql -c 'SELECT count(*) FROM forum.tags;' forumdb
count
-------
     0
(1 row)
....

.Command
[source,bash]
....
psql -c 'DROP DATABASE forumdb;'
pg_restore -C -d postgres -L custom_toc.txt                backup.d
psql -c 'SELECT count(*) FROM forum.tags;' forumdb
....

.Output
[source,output]
....
DROP DATABASE

count
-------
     0
(1 row)
....


Như bạn có thể thấy, table đã được tạo nhưng đang rỗng. Điều này minh họa cách bạn có thể kiểm soát quá trình restore từ một backup để chọn lọc các object cần restore.

Cũng có thể sắp xếp lại các dòng để một số object được restore trước những object khác, nhưng việc này phức tạp hơn nhiều, đặc biệt khi có cross-reference và dependency giữa các object. Dù vậy, đây là một cách cực kỳ linh hoạt để quyết định có chọn lọc những gì cần restore; hơn nữa, bạn có thể tạo một ToC khác để restore cùng một format backup trong các working set khác nhau.
