= Kiểm tra kiến thức

* *Lệnh `pg_ctl` là gì?*

  `pg_ctl` là một lệnh đi kèm với PostgreSQL, cho phép bạn khởi động, khởi động lại, dừng cluster và thực hiện các thao tác khác trên cluster. Lệnh này thường được dùng để quản lý toàn bộ cluster. Xem phần về `pg_ctl` để biết thêm chi tiết.

* *Template database là gì?*

  Template database là một database có thể được dùng làm cơ sở để clone một database khác. Ban đầu, database mới sẽ chứa các object giống như trong template database. Xem phần *Các template database* để biết thêm chi tiết.

* *Lệnh `psql` là gì?*

  `psql` là client chính thức để kết nối tới một database PostgreSQL. Đây là một ứng dụng dòng lệnh có thể dùng để nhập các SQL statement và lấy kết quả từ cluster. Nó được cung cấp trong mọi phiên bản PostgreSQL. Xem phần *Client dòng lệnh psql* để biết thêm chi tiết.

* *Connection string là gì?*

  Connection string là một URI chỉ định mọi parameter cần thiết để kết nối tới một database, thường bao gồm username, host, database, v.v. Xem phần *Giới thiệu về connection string* để biết thêm chi tiết.

* *Các lệnh đặc biệt của psql là gì?*

  Đây là các lệnh ngắn bắt đầu bằng ký hiệu backslash, chẳng hạn `\d`; chúng cung cấp thông tin và chỉ dùng được trong `psql client`. Xem phần *Tổng quan về các command của psql* để biết thêm chi tiết.
