= Kiểm tra kiến thức

* Có thể thực hiện declarative partitioning trong PostgreSQL không?

  Có, kể từ PostgreSQL 10, có thể sử dụng declarative partitioning.

  Xem section Exploring declarative partitioning để biết thêm chi tiết.

* Nếu có một table như sau:

[source,sql]
....
       CREATE TABLE mytable (
             pk serial NOT NULL,
             create_date date not null default now()::date,
             primary key (pk)
       )
....

* Có thể partition table đó theo range không? Có, có thể thực hiện bằng cách viết như sau:

[source,sql]
....
       CREATE TABLE mytable (
             pk serial NOT NULL,
             create_date date not null default now()::date,
             primary key (pk,creat_edate)
       )PARTITION BY RANGE (create_date);
       CREATE TABLE


       forumdb=> CREATE TABLE part_tags_date_01 PARTITION OF part_tags FOR
       VALUES FROM (‘2023-01-01’) TO (‘2023-06-31’);
       forumdb=> CREATE TABLE part_tags_date_01 PARTITION OF part_tags FOR
       VALUES FROM (‘2023-07-01’) TO (‘2023-12-31’);
....

  Xem section Exploring declarative partitioning để biết thêm chi tiết.

* Default partition dùng để làm gì?

  Default partition bảo đảm không có data nào bị mất; nếu PostgreSQL không tìm thấy child table nào để lưu record, record sẽ được lưu trong default partition.

  Xem section The default partition để biết thêm chi tiết.

* Có thể chia data trên các disk khác nhau không?

  Có, có thể dùng tablespace.

  Xem section Partitioning and tablespaces để biết thêm chi tiết.

* PostgreSQL có quản lý index trên partitioned table không?

  Có, PostgreSQL quản lý index trên partitioned table; nếu build một index trên parent table, PostgreSQL sẽ tự build index đó trên tất cả child table.
