= Thống kê nâng cao với pg_stat_statements

Mặc dù PostgreSQL statistics collector rất phong phú và mature, việc monitor connection activity có thể hơi phức tạp vì catalog `pg_stat_activity` không cung cấp thông tin lịch sử. Ví dụ, như đã giải thích trước đó, sẽ chỉ có một tuple chứa statement được thực thi gần nhất, vì vậy sẽ không có history hay chi tiết mở rộng nào được cung cấp.

Extension `pg_stat_statements` giải quyết vấn đề này bằng cách cung cấp một view duy nhất cho bạn toàn bộ history của các statement đã thực thi, timing và những chi tiết nhỏ khác có thể rất hữu ích khi thực hiện introspection. Hơn nữa, `pg_stat_statements` cung cấp số lần cùng một statement đã được thực thi, tạo ra thông tin quan trọng mà các query có thể cần được chú ý để phục vụ mục đích optimization.

Một số monitoring tool yêu cầu `pg_stat_statements` được cài đặt để thu thập data.

Trong các subsection sau, bạn sẽ học cách cài đặt extension này và sử dụng nó.

== Cài đặt extension pg_stat_statements

Extension này được đóng gói cùng PostgreSQL, vì vậy việc duy nhất bạn cần làm là cấu hình database cluster để sử dụng nó. Vì `pg_stat_statements` yêu cầu một shared library, bạn cần cấu hình setting `shared_preload_libraries` trong configuration của mình (file `postgresql.conf`) và restart cluster.

Bước đầu tiên là đặt giá trị sau trong `postgresql.conf`:

[source,text]
....
shared_preload_libraries = 'pg_stat_statements'
....

Hoặc sử dụng `ALTER SYSTEM` như sau:

[source,text]
....
ALTER SYSTEM SET shared_preload_libraries to 'pg_stat_statements';
....

Vì `pg_shared_preload_libraries` là một parameter có context `postmaster`, bạn cần restart cluster để áp dụng các thay đổi.

`pg_stat_statements` thu thập thông tin về tất cả cluster của bạn, nhưng chỉ export thông tin đó trong database nơi bạn tạo extension; trong ví dụ của chúng ta, đó là database `forumdb`:

[source,text]
....
$ psql -U postgres -c "CREATE EXTENSION pg_stat_statements;" forumdb
CREATE EXTENSION
....

Extension hiện đã sẵn sàng để sử dụng.

[quote]
____
Trong Docker image của chapter này, extension `pg_stat_statements` đã được cài đặt và load vào database `forumdb`.

____
== Sử dụng pg_stat_statements

Khi `pg_stat_statements` được enable, nó sẽ bắt đầu thu thập thông tin. Runtime overhead của extension thực sự rất nhỏ, vì vậy bạn cũng có thể giữ nó được enable trong production system.

Vì `pg_stat_statements` thu thập data từ toàn bộ cluster, việc join special view `pg_stat_statements` với các catalog khác, chẳng hạn `pg_database` và `pg_authid`, sẽ hữu ích để lần lượt thu thập thông tin về database và username nơi một statement đã được thực thi. Query sau đây cung cấp một ví dụ:

[source,text]
....
forumdb=# SELECT auth.rolname,query, db.datname, calls, min_exec_time,
max_exec_time
 FROM pg_stat_statements
          JOIN pg_authid auth ON auth.oid = userid
          JOIN pg_database db ON db.oid = dbid
 ORDER BY calls DESC;
...
rolname            | postgres
query         | SELECT count(*) FROM forum.posts WHERE last_edited_on >=
CURRENT_DATE - $1
datname            | forumdb
calls              | 17
min_exec_time | 0.037292
max_exec_time | 0.04165
....

Ví dụ trước cho thấy query đã được thực thi 17 lần kể từ khi `pg_stat_statements` bắt đầu thu thập data, và cần từ 0.037 đến 0.042 milliseconds để chạy. Tùy thuộc vào frequency và timing của từng query, việc inspect và optimize query bằng một index có thể đáng làm.

Trong ví dụ trên, query được báo cáo dưới dạng normalized query: mọi parameter, kể cả literal, đã bị loại bỏ và thay thế bằng placemark `$1` (các parameter khác sẽ được đánh dấu là `$2`, `$3`, v.v.): `SELECT count(*) FROM forum.posts WHERE last_edited_on >= CURRENT_DATE - $1`.

Ý tưởng là theo dõi một nhóm query có cùng normalized text, để bạn có thể biết một nhóm như vậy đã được thực thi bao nhiêu lần, ngay cả khi chúng có các argument khác nhau.

Special view `pg_stat_statements` theo dõi các query được thực thi thường xuyên nhất cho đến giá trị của configuration parameter `pg_stat_statements.max`, mặc định là 5000. Khi đạt đến giới hạn, các query được thực thi ít nhất sẽ bị loại bỏ để nhường chỗ cho các query mới. Điều này bảo đảm không gian mà table `pg_stat_statements` chiếm dụng sẽ gần như không đổi, bất kể số statement đã được thực thi.

View `pg_stat_statements` cung cấp nhiều field không thể được thảo luận chi tiết ở đây, từ planning time đến buffer và I/O activity. Extension này rất hữu ích khi bạn muốn xử lý workload của cluster.

== Reset data được thu thập từ pg_stat_statements

Bất kỳ lúc nào, database administrator cũng có thể reset toàn bộ data đã được extension thu thập bằng cách gọi function `pg_stat_statements_reset()`. Function này sẽ xóa toàn bộ data đã được thu thập và cho phép extension thu thập data mới từ đầu. Điều này có thể hữu ích khi bạn muốn test configuration hoặc hardware mới mà không để data đã thu thập bị bias do statistics cũ:

[source,text]
....
forumdb=# SELECT pg_stat_statements_reset();
....

Theo mặc định, data của `pg_stat_statements` được giữ lại qua các lần shutdown và restart database một cách bình thường.

== Tuning pg_stat_statements

Extension cho phép database administrator giới hạn lượng data được thu thập. Cụ thể, bạn có thể tune các parameter sau trong configuration file `postgresql.conf`:

* `pg_stat_statements.max` cho biết số query riêng lẻ tối đa cần thu thập.
* `pg_stat_statements.save` là một Boolean cho biết content của data đã thu thập có phải tồn tại sau một lần system reboot bình thường hay không. Theo mặc định, setting này là true.
* `pg_stat_statements.track` cho phép bạn chỉ định nesting level cần theo dõi. Với giá trị `top`, extension sẽ thu thập data về query được issue trực tiếp bên trong client và các nested statement được theo dõi. Việc này được kích hoạt bởi execution của các statement khác (ví dụ, trong function statement). Với giá trị `all`, extension sẽ trigger mọi statement và các descendant của chúng, còn với `none`, sẽ không có data nào được thu thập về user statement.
* `pg_stat_statements.track_utility` theo dõi mọi statement không phải `SELECT`, `INSERT`, `UPDATE` hoặc `DELETE` - nói cách khác là các statement “non-ordinary”. Theo mặc định, setting này là `on`.

Thông thường, bạn không cần tune các setting này vì `pg_stat_statements` đã được cấu hình sẵn để theo dõi những gì hầu hết use case cần.
