= 14. Logging và auditing

PostgreSQL cung cấp một hạ tầng logging rất phong phú. Khả năng kiểm tra log là một kỹ năng then chốt đối với mọi database administrator, vì log cung cấp manh mối và thông tin về những gì cluster đã làm, đang làm và những gì đã xảy ra trong quá khứ. Chương này giải thích các khái niệm cơ bản về log configuration của PostgreSQL, đồng thời hướng dẫn cách cấu hình logging machinery để thu thập thông tin cần thiết về hoạt động của cluster. Log có thể được phân tích thủ công, nhưng database administrator cũng thường tận dụng các công cụ tự động để có được cái nhìn toàn diện hơn về hoạt động của cluster. Auditing có liên quan đến logging và cho phép theo dõi ai đã làm gì trên dữ liệu nào. Auditing thường được áp dụng do yêu cầu của pháp luật, thay vì do nhu cầu của database administrator. Tuy nhiên, một hệ thống audit tốt cũng có thể giúp administrator xác định điều gì đã xảy ra trong database.

Trong chương này, bạn sẽ tìm hiểu các chủ đề sau:

* Giới thiệu về logging
* Trích xuất thông tin từ log bằng pgBadger
* Triển khai auditing
