= Lệnh COPY

Xét về thiết kế, `COPY` không phải là một công cụ backup, nhưng nó rất hiệu quả để bulk load data và do đó cũng hiệu quả trong việc restore backup như đã đề cập. Tuy nhiên, command này có thể được dùng để load data theo cả hai chiều: với `COPY`, bạn có thể extract data từ một table (tức là thực hiện dump) hoặc load data vào một table (tức là thực hiện restore). Ngoài ra, `COPY` có thể tương tác với external program; nghĩa là nó có thể gửi (hoặc nhận) data trực tiếp từ một process khác.

`COPY` có hai chế độ hoạt động chính:

* `COPY TO` lấy data từ một table và gửi data đó tới một file trên filesystem hoặc tới một external application hay process khác.
* `COPY FROM` load data từ một file trên filesystem hoặc một external application rồi insert data vào table được chỉ định.

[quote]
____
Khi làm việc với file hoặc program bên ngoài, command `COPY` yêu cầu superuser privilege (hoặc ít nhất user phải thuộc group `pg_write_server_files`). Vì lý do này, các ví dụ trong phần này sẽ được chạy bằng user `postgres`, một superuser.

____
Trong một ví dụ đơn giản, giả sử chúng ta cần extract toàn bộ data từ table `categories`; đây là command dạng `COPY TO`, như minh họa dưới đây:

[source,console,role="transcript"]
....
forumdb=# COPY forum.categories TO '/tmp/categories.backup.txt';
COPY 5
....

.SQL
[source,sql]
....
COPY forum.categories TO '/tmp/categories.backup.txt';
....

.Output
[source,output]
....
COPY 5
....


Trong ví dụ trên, nội dung của table được ghi vào local file `/tmp/categories.backup.txt`; file chỉ chứa các tuple, không chứa bất kỳ SQL instruction cụ thể nào:

[source,console,role="transcript"]
....
$ cat /tmp/categories.backup.txt
5         Software engineering           Software engineering discussions
1         Database               Database related discussions
2         Unix      Unix and Linux discussions
3         Programming Languages          All about programming languages
4         A.I       Machine Learning discussions
....

.Command
[source,bash]
....
cat /tmp/categories.backup.txt
....

.Output
[source,output]
....
5         Software engineering           Software engineering discussions
1         Database               Database related discussions
2         Unix      Unix and Linux discussions
3         Programming Languages          All about programming languages
4         A.I       Machine Learning discussions
....


Command `COPY` hỗ trợ rất nhiều option, cho phép user xác định field delimiter, có thêm table header (tức column name) hay không, chọn quoting character, v.v. Nhờ đó, việc tự xây dựng một tập data ở dạng comma-separated values (CSV) trở nên rất đơn giản:

[source,console,role="transcript"]
....
forumdb=# COPY forum.categories TO '/tmp/categories.csv'
WITH ( HEADER on, DELIMITER ';' );
COPY 5

$ cat /tmp/categories.csv
pk;title;description
5;Software engineering;Software engineering discussions
1;Database;Database related discussions
2;Unix;Unix and Linux discussions
3;Programming Languages;All about programming languages
4;A.I;Machine Learning discussions
....

.Command
[source,bash]
....
cat /tmp/categories.csv
....

.SQL
[source,sql]
....
COPY forum.categories TO '/tmp/categories.csv'
WITH (HEADER ON, DELIMITER ';');
....

.Output
[source,output]
....
COPY 5

pk;title;description
5;Software engineering;Software engineering discussions
1;Database;Database related discussions
2;Unix;Unix and Linux discussions
3;Programming Languages;All about programming languages
4;A.I;Machine Learning discussions
....


Như có thể thấy trong ví dụ trên, mọi field đều được phân tách bằng dấu chấm phẩy và row đầu tiên trong file là danh sách column của table. Cần lưu ý rằng `COPY` có sẵn một CSV format được định nghĩa, có thể chỉ định bằng option `FORMAT csv`:

[source,console,role="transcript"]
....
forumdb=# COPY forum.categories TO '/tmp/categories.csv'
WITH ( FORMAT csv );
COPY 5
....

.SQL
[source,sql]
....
COPY forum.categories TO '/tmp/categories.csv'
WITH (FORMAT csv);
....

.Output
[source,output]
....
COPY 5
....


Khi đã có file CSV chứa data, `COPY FROM` có thể load data vào một table. Nói cách khác, `COPY` không chỉ là một bulk loader hiệu quả; nó còn là một tool hữu ích để load data từ các external resource, chẳng hạn như spreadsheet, vào database.

Giả sử chúng ta cần load data từ file `categories.csv` vào một table khác có tên `categories_reloaded`:

[source,console,role="transcript"]
....
forumdb=# CREATE TABLE forum.categories_reloaded( LIKE forum.categories );
CREATE TABLE
forumdb=# COPY forum.categories_reloaded
               FROM '/tmp/categories.csv'
               WITH (FORMAT csv);
COPY 5
....

.SQL
[source,sql]
....
CREATE TABLE forum.categories_reloaded(LIKE forum.categories);
COPY forum.categories_reloaded
    FROM '/tmp/categories.csv'
    WITH (FORMAT csv);
....

.Output
[source,output]
....
CREATE TABLE
COPY 5
....


Bạn cũng có thể chỉ định một `WHERE` clause để filter data được load; ví dụ, giả sử chúng ta chỉ muốn load các row lẻ:

[source,console,role="transcript"]
....
forumdb=# COPY forum.categories_reloaded
               FROM '/tmp/categories.csv'
          WITH (FORMAT csv)
          WHERE pk % 2 = 1;
....

.SQL
[source,sql]
....
COPY forum.categories_reloaded
         FROM '/tmp/categories.csv'
    WITH (FORMAT csv)
    WHERE pk % 2 = 1;
....


`COPY TO` không cho phép `WHERE` clause, nhưng có thể copy kết quả của một query để filter tuple:

[source,console,role="transcript"]
....
forumdb=# COPY
    ( SELECT * FROM forum.categories
          WHERE pk % 2 = 1 )
    TO '/tmp/categories.odd.csv'
    WITH (FORMAT csv);
....

.SQL
[source,sql]
....
COPY
    (SELECT * FROM forum.categories
          WHERE pk % 2 = 1)
    TO '/tmp/categories.odd.csv'
    WITH (FORMAT csv);
....


Bạn cũng có thể lấy tuple từ một external application, như minh họa trong ví dụ đơn giản sau:

[source,console,role="transcript"]
....
forumdb=# COPY forum.categories_reloaded
FROM PROGRAM $CODE$
/bin/bash -c 'for i in {1..10}; do echo "$i,Title$i,A generated row";
done' $CODE$
WITH (FORMAT csv);
....

.SQL
[source,sql]
....
COPY forum.categories_reloaded
FROM PROGRAM $CODE$
/bin/bash -c 'for i in {1..10}; do echo "$i,Title$i,A generated row";
....

.Output
[source,output]
....
done' $CODE$
WITH (FORMAT csv);
....


Trong ví dụ trên, một shell process được khởi chạy; process đó tạo ra 10 tuple ở dạng CSV. Command `COPY` lấy các tuple từ standard output của command rồi insert chúng vào table. Cơ chế này hoạt động như một pipe của operating system giữa các table PostgreSQL và external process.

Tương tự, bạn cũng có thể gửi data tới một external program, như minh họa trong ví dụ đơn giản sau:

[source,console,role="transcript"]
....
forumdb=# COPY forum.categories
           TO PROGRAM $CODE$ awk '{print $2;}' > /tmp/titles.txt $CODE$;
COPY 5

$ cat /tmp/titles.txt
Software
Database
Unix
Programming
A.I
....

.Command
[source,bash]
....
cat /tmp/titles.txt
....

.SQL
[source,sql]
....
COPY forum.categories
    TO PROGRAM $CODE$ awk '{print $2;}' > /tmp/titles.txt $CODE$;
....

.Output
[source,output]
....
COPY 5

Software
Database
Unix
Programming
A.I
....


Trong ví dụ trên, toàn bộ data trong table được gửi tới `awk(1)`; tool này chỉ extract column thứ hai (tức column `title`) rồi redirect output vào một file. Kết quả cuối cùng là một dạng pseudo-filtering đối với nội dung của table.

[quote]
____
Cần lưu ý rằng `COPY` hỗ trợ single-column list, nghĩa là bạn có thể chỉ định những column nào cần extract hoặc insert vào.

____
Khi sử dụng `COPY` để làm việc với file hoặc program bên ngoài, user chạy command phải là superuser hoặc phải thuộc group `pg_write_server_files`.

Nói cách khác, user không có privilege không thể sử dụng `COPY`. Để giải quyết vấn đề này, `psql` cung cấp một command thay thế cho `COPY`, có tên là `\copy`; command này stream content (theo cả hai chiều) giữa `psql` client và các file mà client có thể truy cập. Nhờ đó, user có thể sử dụng `COPY` mà không cần server privilege đặc biệt nào như `pg_write_server`.

Vì vậy, user không có privilege muốn extract data từ một query và ghi data đó vào file có thể thực hiện như sau:

[source,console,role="transcript"]
....
forumdb=> \COPY
( SELECT * FROM forum.categories
 WHERE pk % 2 = 1 )
TO '/tmp/categories.odd.csv'
WITH (FORMAT csv);
COPY 3
....

.SQL
[source,sql]
....
\COPY
....

.Output
[source,output]
....
( SELECT * FROM forum.categories
 WHERE pk % 2 = 1 )
TO '/tmp/categories.odd.csv'
WITH (FORMAT csv);
COPY 3
....


Lưu ý rằng ví dụ này sử dụng `\copy` thay vì `COPY`.

Nhờ `COPY` và wrapper `\copy` của psql, user có thể dễ dàng bulk-load data và extract data từ database.

Sau khi đã tìm hiểu về logical backup, hãy chuyển sang physical backup.
