= Kiểm tra kiến thức

* Record `NEW` là gì?

  Record `NEW` là record sẽ được xử lý trước khi thực thi statement `INSERT` hoặc `UPDATE`, ví dụ:

[source,text]
....
  insert into mytable(id,city_name) values (1,'New York')
....

[source,text]
....
  NEW.id = 1
  NEW.city_name = 'New York'
....

  Xem phần *Khám phá rule trong PostgreSQL* để biết thêm chi tiết.

* Có thể dùng rule để thực hiện một `INSERT` trên hai table trong cùng một transaction không?

  Có; có thể thực hiện việc này bằng clause `ALSO`. Xem phần *Khám phá rule trong PostgreSQL* để biết thêm chi tiết.

* Có thể dùng trigger để làm mọi việc có thể làm bằng rule không?

  Có; trigger cho phép thực hiện mọi việc rule có thể làm và còn nhiều hơn nữa. Xem phần *Quản lý trigger trong PostgreSQL* để biết thêm chi tiết.

* Có thể xác định một trigger được kích hoạt bởi event `INSERT`, `UPDATE` hay `DELETE` không?

  Có, bằng cách sử dụng biến `TG_OP`. Xem phần *Quản lý trigger trong PostgreSQL* để biết thêm chi tiết.

* Có thể viết một audit procedure để thông báo khi một statement DDL đã được thực thi không?

  Có, bằng cách sử dụng event trigger. Xem phần *Event trigger* để biết thêm chi tiết.
