= Kiểm tra kiến thức

* *Extension là gì?*

  Extension là một tập hợp các database object liên quan, có thể được cài đặt, nâng cấp hoặc xóa như một thể thống nhất. Xem phần *Giới thiệu extension* để biết thêm chi tiết.

* *Command pgxnclient là gì?*

  pgxnclient là một command hỗ trợ làm việc với PGXN, cho phép tải xuống, cài đặt và xóa extension. Xem phần *Khám phá PGXN client* để biết thêm chi tiết.

* *Extension control file là gì?*

  Control file là một file văn bản định nghĩa các thuộc tính chính của extension, chẳng hạn như tên, version và các dependency khác. Xem phần *Thành phần của extension* để biết thêm chi tiết.

* *Làm thế nào để kiểm tra những extension đã được tạo trong một database?*

  Catalog đặc biệt `pg_extension` cung cấp thông tin về các extension đã cài đặt; trong `psql`, meta-command `\dx` hiển thị thông tin tóm tắt về các extension này. Xem phần *Xem các extension đã cài đặt* để biết thêm chi tiết.

* *Làm thế nào để nâng cấp một extension lên version khác?*

  Statement `ALTER EXTENSION UPDATE TO` có thể dùng để chỉ định version đích khi nâng cấp extension. Xem phần *Sửa đổi extension hiện có* để biết thêm chi tiết.
