= Kiểm tra kiến thức

* Nếu chạy query này và dữ liệu trong table có tên `mytable` không thay đổi, chúng ta có luôn nhận được cùng một kết quả không?

[source,sql]
....
SELECT *
FROM mytable
....

  Không, vì thứ tự các row có thể khác nhau.

  Xem phần *Tìm hiểu statement SELECT* để biết thêm chi tiết.

* Có thể dùng một query để chỉ nhận về 3 row không?

  Có, có thể dùng clause `LIMIT`.

  Xem phần *Sử dụng LIMIT và OFFSET* để biết thêm chi tiết.

* Nếu có 2 table: table A có 3 row, trong đó column `id` là primary key, còn table B có 2 row, trong đó column `id` là primary key, chúng ta phải dùng loại join nào để lấy tất cả các row có cùng ID trong table A và table B?

  Chúng ta phải dùng một query với INNER JOIN:

[source,sql]
....
SELECT tableA.id
FROM tableA inner JOIN tableB USING(id)
....

  Xem phần *Sử dụng INNER JOIN* để biết thêm chi tiết.

* Nếu có 2 table: table A có 3 row, trong đó column `id` là primary key, còn table B có 2 row, trong đó column `id` là primary key, khi sử dụng clause `NOT EXISTS`, làm thế nào để viết một query hiển thị tất cả các row có trong table A nhưng không có trong table B?

[source,sql]
....
SELECT *
FROM tableA
WHERE NOT EXISTS (SELECT 1 FROM tableB WHERE tableA.id = tableB.id)
....

  Xem phần *Subquery và điều kiện EXISTS/NOT EXISTS* để biết thêm chi tiết.

* PostgreSQL 11 và PostgreSQL 16 có cùng cách sử dụng CTE không?

  Không. PostgreSQL 11 luôn materialize dữ liệu. PostgreSQL 16, nếu không có chỉ định khác, chỉ materialize dữ liệu khi CTE được tham chiếu ít nhất hai lần trong query.

  Xem phần *Subquery và điều kiện EXISTS/NOT EXISTS* và *Tìm hiểu về CTE* để biết thêm chi tiết.
