= Mã hóa password của role

Password dùng để đăng nhập của role luôn được lưu dưới dạng đã mã hóa, ngay cả khi role được tạo mà không chỉ định property `ENCRYPTED PASSWORD`. PostgreSQL xác định encryption algorithm dùng cho password dựa trên option `password_encryption` trong configuration file `postgresql.conf`. Mặc định, option này có giá trị là `scram-sha-256`:

[source,console,role="transcript"]
....
      forumdb=> show password_encryption;
      password_encryption
      ---------------------
      scram-sha-256
      (1 row)
....

.SQL
[source,sql]
....
show password_encryption;
....

.Output
[source,output]
....
      password_encryption
      ---------------------
      scram-sha-256
      (1 row)
....


PostgreSQL giới thiệu encryption algorithm SCRAM-SHA-256 trong version 10. Trước đó, encryption algorithm được đặt thành `md5`, vốn kém an toàn hơn và là option duy nhất còn lại (nhưng hiện không còn được khuyến nghị).

Điều quan trọng cần lưu ý là không thể thay đổi password encryption algorithm trên một live system mà không reset toàn bộ password của các role đang active. Nói cách khác, nếu quyết định migrate từ `md5` cũ sang SCRAM-SHA-256 mới hơn (hoặc ngược lại), bạn cần chạy các statement `ALTER ROLE` phù hợp để thiết lập password mới cho mọi role được định nghĩa trong database.

[quote]
____
Vì giá trị của field `pg_authid.rolpassword` bắt đầu bằng encryption algorithm, có thể là `md5` hoặc SCRAM-SHA-256, nên việc kiểm tra system catalog để tìm các role chưa được cập nhật sang encryption algorithm mới khá đơn giản.

____
