= Các khái niệm cơ bản

Trước hết, hãy tìm hiểu tại sao chúng ta cần partition dữ liệu. Một đặc điểm chung của mọi database là kích thước luôn tăng. Vì vậy, sau vài tháng tăng trưởng, một database có thể đạt kích thước gigabyte, terabyte hoặc thậm chí petabyte.

Một điều khác cần luôn ghi nhớ là không phải mọi table đều tăng với cùng tốc độ hoặc đạt cùng kích thước; một số table lớn hơn các table khác và một số index cũng lớn hơn các index khác.

Chúng ta cũng cần biết rằng một phần RAM của server được chia sẻ giữa tất cả process PostgreSQL và dùng để quản lý dữ liệu hiện diện trong các table. Phần RAM này được gọi là `shared_buffers`.

PostgreSQL hoạt động như sau:

. Dữ liệu được đọc từ hard disk.
. Dữ liệu được đặt vào shared buffers.
. Dữ liệu được xử lý trong shared buffers.
. Dữ liệu được ghi xuống disk.

Thông thường, trên một dedicated server chỉ dành cho PostgreSQL, kích thước của `shared_buffers` vào khoảng một phần ba hoặc một phần tư tổng RAM của server. Một liên kết hữu ích để thiết lập một số parameter cấu hình của PostgreSQL, bao gồm kích thước `shared_buffers` được khuyến nghị, là https://pgtune.leopard.in.ua.

Khi một table trở nên quá lớn so với kích thước của `shared_buffers`, hiệu năng có thể giảm. Trong trường hợp này, partitioning dữ liệu có thể hữu ích. Partitioning dữ liệu là việc chia một table rất lớn thành các table nhỏ hơn theo cách trong suốt đối với client program. Client program sẽ cho rằng server vẫn chỉ có một table, nhưng các table nhỏ hơn cũng đồng nghĩa với các index nhỏ hơn, có nhiều khả năng nằm trong memory hơn, từ đó cải thiện hiệu năng khi truy cập dữ liệu. Ngoài ra, các table nhỏ hơn cho phép các process VACUUM làm việc trên lượng dữ liệu nhỏ hơn, giúp giảm thời gian thực thi của các process VACUUM. Cuối cùng, khi chạy `vacuum full`, dung lượng disk mà table sử dụng sẽ tăng gấp đôi; do đó, có nhiều table nhỏ thay vì một table lớn sẽ giảm đáng kể ảnh hưởng của vấn đề này. Partitioning dữ liệu có thể được thực hiện theo hai cách:

* Sử dụng table inheritance (cách duy nhất có thể sử dụng trước PostgreSQL 10)
* Sử dụng declarative partitioning (cách tốt nhất từ version 10 trở đi)

Sau khi hiểu khi nào nên partition dữ liệu, hãy xem chúng ta có thể thực hiện những loại table partitioning nào. PostgreSQL hỗ trợ ba loại declarative partitioning:

* Range partitioning
* List partitioning
* Hash partitioning

Bây giờ chúng ta sẽ mô tả chi tiết ba phương pháp này.

Trước khi bắt đầu, hãy nhớ khởi động Docker container có tên `chapter9` như dưới đây:

[source,console,role="transcript"]
....
$ bash run-pg-docker.sh chapter_09
postgres@learn_postgresql:~$ psql -U forum forumdb
....

.Command
[source,bash]
....
bash run-pg-docker.sh chapter_09
psql -U forum forumdb
....


== Range partitioning

Range partitioning là cách chia table thành các interval. Các interval không được chồng lấn và range được xác định bằng một column hoặc một nhóm column. Để biết thêm thông tin, xem https://www.postgresql.org/docs/current/ddl-partitioning.html.

Hãy xem một ví dụ về cách định nghĩa range partitioning. Giả sử chúng ta có table sau:

[cols="2*", options="header"]
|===
| field date | field_value
| 2023-03-01 | 1
| 2023-03-02 | 10
| 2023-04-01 | 12
| 2023-04-15 | 1
|===

*Table 9.1: Table trước khi áp dụng range partitioning*

Bây giờ, giả sử chúng ta muốn chia table này thành hai table. Table thứ nhất (*TABLE A*) sẽ chứa mọi row có giá trị `field_date` nằm trong khoảng từ 2023-03-01 đến 2023-03-31, còn table thứ hai (*TABLE B*) sẽ chứa mọi row có giá trị `field_date` nằm trong khoảng từ 2023-04-01 đến 2023-04-30. Vì vậy, mục tiêu là có hai table như sau:

[cols="2*", options="header"]
|===
| field date | field_value
| 2023-03-01 | 1
| 2023-03-02 | 10
|===

*Table 9.2: Table A*

[cols="2*", options="header"]
|===
| field date | field_value
| 2023-04-01 | 12
| 2023-04-15 | 1
|===

*Table 9.3: Table B*

Ví dụ trên là một trường hợp partitioning theo range. Cách này hữu ích khi chúng ta có các table lớn, trong đó dữ liệu có thể được chia theo time range, ví dụ như table doanh thu, audit table hoặc log table.

== List partitioning

Trong list partitioning, table được partition dựa trên một danh sách các giá trị.

Hãy xem một ví dụ về cách định nghĩa list partitioning. Giả sử chúng ta có table sau:

[cols="2*", options="header"]
|===
| field_state | field_city
| United States | Washington
| United States | San Francisco
| Italy | Rome
| Japan | Tokyo
|===

*Table 9.4: Table trước khi áp dụng list partitioning*

Giả sử bây giờ chúng ta muốn chia table này thành `n` table, mỗi state có một table. Table thứ nhất (*TABLE A*) sẽ chứa mọi row có giá trị `field_state` bằng United States, table thứ hai (*TABLE B*) sẽ chứa mọi row có giá trị `field_state` bằng Italy, còn table thứ ba (*TABLE C*) sẽ chứa các row có giá trị `field_state` bằng Japan. Vì vậy, mục tiêu là có ba table như sau:

[cols="2*", options="header"]
|===
| field_state | field_city
| United States | Washington
| United States | San Francisco
|===

*Table 9.5: Table A*

[cols="2*", options="header"]
|===
| field_state | field_city
| Italy | Rome
|===

*Table 9.6: Table B*

[cols="2*", options="header"]
|===
| field_state | field_city
| Japan | Tokyo
|===

*Table 9.7: Table C*

Đây là một ví dụ về list partitioning. Cách này hữu ích khi chúng ta có các table lớn, trong đó dữ liệu có thể được chia theo một column duy nhất, chẳng hạn như column city hoặc state trong danh bạ điện thoại hoặc danh sách khách hàng.

== Hash partitioning

Khi sử dụng hash partitioning, table được partition dựa trên các hash value để phân bổ dữ liệu vào các table khác nhau.

Hãy xem một ví dụ về hash partitioning. Giả sử chúng ta có table sau:

[cols="2*", options="header"]
|===
| field date | field_value
| 2023-03-01 | 1
| 2023-03-02 | 1
| 2023-04-01 | 2
| 2023-04-15 | 2
|===

*Table 9.8: Table trước khi áp dụng hash partitioning*

Giả sử bây giờ chúng ta có một hash function chuyển đổi date thành một hash value; ví dụ, hãy xét toán tử `del mod` (`%`):

* `hash(1) = 1`
* `hash(1) = 1`
* `hash(2) = 0`
* `hash(2) = 0`

Vì vậy, sau quá trình partitioning, chúng ta sẽ có hai table:

[cols="2*", options="header"]
|===
| field date | field_value
| 2023-03-01 | 1
| 2023-03-02 | 1
|===

*Table 9.9: Table A*

[cols="2*", options="header"]
|===
| field date | field_value
| 2023-04-01 | 2
| 2023-04-15 | 2
|===

*Table 9.10: Table B*

Đây là một ví dụ về partitioning theo hash.

Trong các phần tiếp theo, chúng ta sẽ xem PostgreSQL triển khai list, range và hash partitioning như thế nào. Nhưng trước hết, hãy dành thời gian tìm hiểu table inheritance.

Để biết thêm thông tin về partitioning, xem https://www.postgresql.org/docs/current/ddl-partitioning.html.

== Table inheritance

Một khía cạnh khác cần xem xét là table inheritance. PostgreSQL áp dụng khái niệm database inheritance cho các object. Khái niệm này rất đơn giản và có thể tóm tắt như sau: giả sử chúng ta có hai table, *TABLE A* và *TABLE B*. Nếu định nghĩa *TABLE A* là parent table và *TABLE B* là child table, điều đó có nghĩa là mọi row trong *TABLE B* đều có thể được truy cập thông qua *TABLE A*.

Hãy xem một ví dụ cho mô tả trên:

. Hãy định nghĩa hai table như sau:

   Table thứ nhất, parent table, được định nghĩa như sau:

[source,console,role="transcript"]
....
   forumdb=> create table table_a (
   pk integer not null primary key,
   tag text,
   parent integer);
   CREATE TABLE
....

.SQL
[source,sql]
....
CREATE TABLE table_a (
   pk integer NOT NULL PRIMARY KEY,
   tag text,
   parent integer);
....

.Output
[source,output]
....
   CREATE TABLE
....


   Table thứ hai, child table, được định nghĩa như sau:

[source,console,role="transcript"]
....
   forumdb=> create table table_b () inherits (table_a);
   CREATE TABLE

   forumdb=> alter table table_b add constraint table_b_pk primary
   key(pk);
   ALTER TABLE
....

.SQL
[source,sql]
....
CREATE TABLE table_b () inherits (table_a);
ALTER TABLE table_b ADD CONSTRAINT table_b_pk PRIMARY
   KEY(pk);
....

.Output
[source,output]
....
   CREATE TABLE

   ALTER TABLE
....


[%start=2]
. Child table kế thừa tất cả column của parent table. Thông tin của parent table như sau:

[source,console,role="transcript"]
....
   forumdb=> \d table_a;
                       Table "forum.table_a"
    Column |     Type      | Collation | Nullable | Default


   --------+---------+-----------+----------+---------
    pk       | integer |                  | not null |


   tag     | text       |              |             |



   parent | integer |                  |             |



   Indexes:
         "table_a_pkey" PRIMARY KEY, btree (pk)
   Number of child tables: 1 (Use \d+ to list them.)
....

.SQL
[source,sql]
....
\d table_a;
....

.Output
[source,output]
....
                       Table "forum.table_a"
    Column |     Type      | Collation | Nullable | Default


   --------+---------+-----------+----------+---------
    pk       | integer |                  | not null |


   tag     | text       |              |             |



   parent | integer |                  |             |



   Indexes:
         "table_a_pkey" PRIMARY KEY, btree (pk)
   Number of child tables: 1 (Use \d+ to list them.)
....


   Để xem chi tiết hơn, hãy sử dụng meta-command `\d+`:

[source,console,role="transcript"]
....
   forumdb=> \d+ table_a;
                      Table "forum.table_a"
    Column | Type    | Collation | Nullable | Default | Storage              |
   Compression | Stats target | Description


   --------+---------+-----------+----------+---------+----------+-----
   --------+--------------+
    pk      | integer |                 | not null |              | plain    |
   |               |


   tag      | text       |             |           |           | extended |
   |                 |



   parent | integer |                  |             |           | plain    |
   |              |



   Indexes:
         "table_a_pkey" PRIMARY KEY, btree (pk)
   Child tables: table_b
   Access method: heap
....

.SQL
[source,sql]
....
\d+ table_a;
....

.Output
[source,output]
....
                      Table "forum.table_a"
    Column | Type    | Collation | Nullable | Default | Storage              |
   Compression | Stats target | Description


   --------+---------+-----------+----------+---------+----------+-----
   --------+--------------+
    pk      | integer |                 | not null |              | plain    |
   |               |


   tag      | text       |             |           |           | extended |
   |                 |



   parent | integer |                  |             |           | plain    |
   |              |



   Indexes:
         "table_a_pkey" PRIMARY KEY, btree (pk)
   Child tables: table_b
   Access method: heap
....


   Trong output cuối cùng này, có thể thấy `table_b` là child table của `table_a`.

[%start=3]
. Làm tương tự với table có tên `table_b`:

[source,console,role="transcript"]
....
   forumdb=> \d table_b;
                       Table "forum.table_b"
....

.SQL
[source,sql]
....
\d table_b;
....

.Output
[source,output]
....
                       Table "forum.table_b"
....


[source,output]
....
   Column |      Type    | Collation | Nullable | Default


  --------+---------+-----------+----------+---------
   pk       | integer |                | not null |


   tag      | text       |             |             |


   parent | integer |                  |             |


  Indexes:
        "table_b_pk" PRIMARY KEY, btree (pk)
  Inherits: table_a
....

Ở đây có thể thấy `table_b` là child table của `table_a`.

[%start=4]
. Bây giờ hãy xem hai table này hoạt động như thế nào khi chúng ta insert, sửa đổi hoặc delete dữ liệu. Ví dụ, hãy thực hiện một số thao tác insert:

[source,console,role="transcript"]
....
  forumdb=> insert into table_a (pk,tag,parent) values (1,'Operating
  Systems',0);
  INSERT 0 1


  forumdb=> insert into table_b (pk,tag,parent) values (2,'Linux',0);
  INSERT 0 1
....

.SQL
[source,sql]
....
INSERT INTO table_a (pk, tag, parent)
VALUES (1, 'Operating Systems', 0);
INSERT INTO table_b (pk, tag, parent)
VALUES (2, 'Linux', 0);
....

.Output
[source,output]
....
  INSERT 0 1


  INSERT 0 1
....


. Hãy xem dữ liệu thay đổi như thế nào khi thực thi command `select`:

[source,console,role="transcript"]
....
  forumdb=> select * from table_b ;
   pk |    tag    | parent


  ----+-------+--------
    2 | Linux |           0
  (1 row)
....

.SQL
[source,sql]
....
SELECT *
FROM table_b;
....

.Output
[source,output]
....
   pk |    tag    | parent


  ----+-------+--------
    2 | Linux |           0
  (1 row)
....


Có thể thấy `table_b` chứa một row.

[%start=6]
. Bây giờ hãy thực thi command sau:

[source,console,role="transcript"]
....
  forumdb=>      select * from table_a ;
   pk |            tag          | parent


  ----+-------------------+--------
    1 | Operating Systems |            0
    2 | Linux                   |      0
  (2 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM table_a;
....

.Output
[source,output]
....
   pk |            tag          | parent


  ----+-------------------+--------
    1 | Operating Systems |            0
    2 | Linux                   |      0
  (2 rows)
....


Có vẻ như `table_a` có hai row. Điều này xảy ra vì table này kế thừa các thuộc tính của table kia. Nếu thực thi command `SELECT` trên parent table, chúng ta sẽ thấy tất cả row thuộc về parent table và tất cả row thuộc về child table.

[%start=7]
. Nếu muốn xem tất cả row chỉ thuộc về `table_a`, chúng ta phải dùng `ONLY` clause như sau:

[source,console,role="transcript"]
....
  forumdb=>    select * from only      table_a ;
   pk |           tag           | parent


  ----+-------------------+--------
    1 | Operating Systems |            0
  (1 row)
....

.SQL
[source,sql]
....
SELECT *
FROM only table_a;
....

.Output
[source,output]
....
   pk |           tag           | parent


  ----+-------------------+--------
    1 | Operating Systems |            0
  (1 row)
....


. Hãy xem điều gì xảy ra nếu chúng ta `UPDATE` một số row; ví dụ, hãy thực thi câu lệnh sau:

[source,console,role="transcript"]
....
  forumdb=> update table_a set tag='BSD Unix' where pk=2;
  UPDATE 1
....

.SQL
[source,sql]
....
UPDATE table_a
SET
    tag = 'BSD Unix'
WHERE pk = 2;
....

.Output
[source,output]
....
  UPDATE 1
....


Chúng ta đã thực hiện thao tác update trên `table_a`, nhưng nhờ table inheritance, thao tác này được thực hiện về mặt vật lý trên `table_b`, như có thể thấy dưới đây:

[source,console,role="transcript"]
....
  forumdb=> select * from table_b;
   pk |     tag     | parent


  ----+----------+--------
    2 | BSD Unix |          0
  (1 row)
....

.SQL
[source,sql]
....
SELECT *
FROM table_b;
....

.Output
[source,output]
....
   pk |     tag     | parent


  ----+----------+--------
    2 | BSD Unix |          0
  (1 row)
....


[%start=9]
. Điều tương tự cũng xảy ra nếu chúng ta sử dụng một `delete` statement như sau:

[source,console,role="transcript"]
....
  forumdb=> delete from table_a where pk=2;
  DELETE 1
....

.SQL
[source,sql]
....
DELETE FROM table_a WHERE pk = 2;
....

.Output
[source,output]
....
  DELETE 1
....


Một lần nữa, thao tác delete trên `table_a` cũng ảnh hưởng đến `table_b`. Như có thể thấy dưới đây, `table_a` sẽ có các row sau:

[source,console,role="transcript"]
....
  forumdb=> select * from table_a;
   pk |           tag           | parent


  ----+-------------------+--------
    1 | Operating Systems |             0
  (1 row)
....

.SQL
[source,sql]
....
SELECT *
FROM table_a;
....

.Output
[source,output]
....
   pk |           tag           | parent


  ----+-------------------+--------
    1 | Operating Systems |             0
  (1 row)
....


Lúc này, `table_b` không còn row nào:

[source,console,role="transcript"]
....
  forumdb=>    select * from table_b;
   pk | tag | parent


  ----+-----+--------
  (0 rows)
....

.SQL
[source,sql]
....
SELECT *
FROM table_b;
....

.Output
[source,output]
....
   pk | tag | parent


  ----+-----+--------
  (0 rows)
....


Trong PostgreSQL, inheritance lan truyền các thao tác được thực hiện trên parent table đến các child table.

== Xóa table

Để kết thúc phần inheritance, cần nói về cách xóa table. Nếu muốn xóa một child table, chẳng hạn bằng cách drop `table_b`, chúng ta phải chạy statement sau:

[source,console,role="transcript"]
....
 forumdb=>     drop table table_b;
 DROP TABLE
....

.SQL
[source,sql]
....
DROP TABLE table_b;
....

.Output
[source,output]
....
 DROP TABLE
....


Nếu muốn drop một parent table cùng tất cả child table liên kết với nó, cần chạy như sau:

[source,console,role="transcript"]
....
 forumdb=>     drop table table_a cascade;
....

.SQL
[source,sql]
....
DROP TABLE table_a CASCADE;
....


Inheritance từng được dùng và vẫn có thể được dùng để triển khai table partitioning, nhưng kể từ version 10, declarative partitioning đã trở thành phương pháp được ưu tiên. Declarative partitioning sẽ được trình bày trong phần tiếp theo.
