= Kiểm tra kiến thức

* *Configuration context là gì?*

  Configuration context xác định cluster sẽ tiếp nhận các thay đổi đối với configuration parameter như thế nào - ví dụ, chỉ tại thời điểm boot hoặc tại connection tiếp theo. Xem section Configuration contexts để biết thêm chi tiết.

* *Sự khác biệt giữa các catalog `pg_settings` và `pg_file_settings` là gì?*

  Catalog `pg_settings` hiển thị giá trị của mọi configuration parameter, cùng các giá trị được chấp nhận và hợp lệ; catalog `pg_file_settings` hiển thị nơi (tức trong file nào và tại dòng nào) một configuration parameter được tìm thấy và load. Xem section Inspecting all configuration parameters để biết thêm chi tiết.

* *Ngoài việc edit configuration file, làm thế nào bạn có thể thay đổi configuration của cluster thông qua SQL statement?*

  Bạn có thể issue command `ALTER STATEMENT` để thay đổi giá trị của một configuration setting. Các thay đổi sẽ được ghi vào file `postgresql.auto.conf`. Xem section Modifying the configuration from a live system để biết thêm chi tiết.

* *Làm thế nào để lấy thông tin về connection, transaction và query đang chạy?*

  Special catalog `pg_stat_activity` cung cấp thông tin về mọi backend process, query đang chạy (hoặc đã chạy gần nhất) và transaction state của process đó. Xem section Information about running queries and connections để biết thêm chi tiết.

* *Extension `pg_stat_statements` thực hiện việc gì?*

  Extension `pg_stat_statements` cung cấp historical view về các query được lặp lại thường xuyên nhất, cùng thông tin về thời gian chạy, số lần execution và các chi tiết khác. Xem section Advanced statistics with pg_stat_statements để biết thêm chi tiết.
