= Kiểm tra kiến thức

* Xem xét hai query sau:

.. `select category,count(*) from posts group by category order by category;`
.. `select category, count(*) over (partition by category) from posts order by category;`

  Trong hai query, query nào trả về nhiều row hơn?

  Query thứ hai trả về nhiều row hơn.

  Để biết thêm chi tiết, xem phần Sử dụng window function trong các statement cơ bản.

* Xem xét hai query sau:

.. `select category,count(*) from posts group by category order by category;`
.. `select distinct category, count(*) over (partition by category) from posts order by category;`

  Trong hai query, query nào trả về nhiều row hơn?

  Hai query trả về cùng số row.

  Để biết thêm chi tiết, xem phần Sử dụng window function trong các statement cơ bản.

* Về mặt ngữ nghĩa, query nào trong hai query sau là đúng?

.. `select category,row_number() over w,title from posts WINDOW w as (partition by category order by title) order by category;`
.. `select category,row_number() over w,title from posts WINDOW w as (partition by category) order by category;`

  Query thứ nhất đúng về mặt ngữ nghĩa vì function `row_number()` phụ thuộc vào `order by`.

  Để biết thêm chi tiết, xem phần Function ROW_NUMBER.

* Có thể lấy giá trị đầu tiên trong một partition không?

  Có. Có thể thực hiện việc này bằng function `first_value()`. Để biết thêm chi tiết, xem phần `FIRST_VALUE`.

* Có thể tính tổng lũy kế cho từng row trong một table không?

  Có. Có thể thực hiện việc này bằng clause `BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW`.

  Để biết thêm chi tiết, xem phần Sử dụng window function trong các statement nâng cao.
