= Kiểm tra kiến thức

* Có thể mở rộng tính năng và data type trong PostgreSQL không?

  Có, PostgreSQL có thể được mở rộng bằng data type và function.

  Xem phần Khái niệm extensibility để biết thêm chi tiết.

* PostgreSQL chỉ hỗ trợ relational database thôi phải không?

  Không, PostgreSQL cũng hỗ trợ NoSQL database.

  Xem phần Data type NoSQL để biết thêm chi tiết.

* PostgreSQL có hỗ trợ SQL function không?

  Có, chúng ta có thể viết mọi loại SQL function.

  Xem phần SQL function để biết thêm chi tiết.

* PostgreSQL có một procedural language được tích hợp sẵn không?

  Có, PostgreSQL tích hợp sẵn một procedural language có tên là PL/pgSQL.

  Xem phần PL/pgSQL function để biết thêm chi tiết.

* User không có administrative privilege có thể đọc một table yêu cầu administrative permission không?

  Có. Với tư cách administrator, hãy tạo một function để đọc table, định nghĩa function bằng clause security definer, rồi cấp quyền thực thi trên function đó cho user không phải administrator.

  Xem phần Security definer để biết thêm chi tiết.
