= Mã hóa password của role

Password đăng nhập gắn với role luôn được lưu dưới dạng encrypted, ngay cả khi role được tạo mà không có property `ENCRYPTED PASSWORD`. PostgreSQL xác định algorithm dùng để encrypt password thông qua option `password_encryption` trong configuration file `postgresql.conf`. Mặc định, giá trị của option này là `scram-sha-256`:

[source,text]
....
      forumdb=> show password_encryption;
      password_encryption
      ---------------------
      scram-sha-256
      (1 row)
....

PostgreSQL giới thiệu encryption algorithm SCRAM-SHA-256 trong version 10; trước đó, encryption algorithm được đặt là `md5`, kém robust hơn, và cũng là option còn lại duy nhất (nhưng hiện đã bị discourage).

Điều quan trọng cần lưu ý là bạn không thể thay đổi password encryption algorithm của một live system mà không reset toàn bộ password của các role đang active. Nói cách khác, nếu quyết định migrate từ `md5` cũ sang SCRAM-SHA-256 mới hơn (hoặc ngược lại), bạn cần issue các statement `ALTER ROLE` thích hợp để thiết lập password mới cho mọi role đã định nghĩa trong database.

[quote]
____
Vì field `pg_authid.rolpassword` bắt đầu bằng encryption algorithm, hoặc `md5` hoặc SCRAM-SHA-256, nên việc inspect system catalog và tìm các role chưa được update bằng encryption algorithm mới là đơn giản.

____
